### ISSUE TITLE
Valgrind - OS X 10.10 - Darwin 14.5.0 x86_64

### ISSUE THREAD

**Issue by weinrank** [sctplab/usrsctp#10]
Memcheck, a memory error detector
    Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
    Using Valgrind-3.11.0.SVN and LibVEX; rerun with -h for copyright info
    Command: ./ekr_loop
    Parent PID: 68438
    
    Syscall param socketcall.setsockopt(optval) points to uninitialised byte(s)
       at 0x10036A93A: setsockopt (in /usr/lib/system/libsystem_kernel.dylib)
       by 0x100003944: recv_thread_init (user_recv_thread.c:1127)
       by 0x100052309: sctp_init (sctp_usrreq.c:170)
       by 0x1000010A7: main (ekr_loop.c:278)
     Address 0x104791914 is on thread 1's stack
     in frame #1, created by recv_thread_init (user_recv_thread.c:1081)
     Uninitialised value was created by a stack allocation
       at 0x10004AE5B: sctp_pcb_init (sctp_pcb.c:6850)
    
    Syscall param socketcall.setsockopt(optval) points to uninitialised byte(s)
       at 0x10036A93A: setsockopt (in /usr/lib/system/libsystem_kernel.dylib)
       by 0x100003C0A: recv_thread_init (user_recv_thread.c:1220)
       by 0x100052309: sctp_init (sctp_usrreq.c:170)
       by 0x1000010A7: main (ekr_loop.c:278)
     Address 0x104791914 is on thread 1's stack
     in frame #1, created by recv_thread_init (user_recv_thread.c:1081)
     Uninitialised value was created by a stack allocation
       at 0x10004AE5B: sctp_pcb_init (sctp_pcb.c:6850)
    
    Syscall param socketcall.setsockopt(optval) points to uninitialised byte(s)
       at 0x10036A93A: setsockopt (in /usr/lib/system/libsystem_kernel.dylib)
       by 0x100004125: recv_thread_init (user_recv_thread.c:1366)
       by 0x100052309: sctp_init (sctp_usrreq.c:170)
       by 0x1000010A7: main (ekr_loop.c:278)
     Address 0x104791914 is on thread 1's stack
     in frame #1, created by recv_thread_init (user_recv_thread.c:1081)
     Uninitialised value was created by a stack allocation
       at 0x10004AE5B: sctp_pcb_init (sctp_pcb.c:6850)
    
    Conditional jump or move depends on uninitialised value(s)
       at 0x10046AC3F: _platform_memchr$VARIANT$Haswell (in /usr/lib/system/libsystem_platform.dylib)
       by 0x10025E9F6: __sfvwrite (in /usr/lib/system/libsystem_c.dylib)
       by 0x100268E45: __vfprintf (in /usr/lib/system/libsystem_c.dylib)
       by 0x10028E80E: __v2printf (in /usr/lib/system/libsystem_c.dylib)
       by 0x10028EAE0: __xvprintf (in /usr/lib/system/libsystem_c.dylib)
       by 0x1002649D1: vfprintf_l (in /usr/lib/system/libsystem_c.dylib)
       by 0x100262837: printf (in /usr/lib/system/libsystem_c.dylib)
       by 0x10000126A: main (ekr_loop.c:360)
     Uninitialised value was created by a stack allocation
       at 0x100264A58: __vfprintf (in /usr/lib/system/libsystem_c.dylib)
    
    UNKNOWN host message [id 412, to mach_host_self(), reply 0x30f]
    UNKNOWN host message [id 222, to mach_host_self(), reply 0x30f]
    UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option
    UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 2 times)
    UNKNOWN mach_msg unhandled MACH_SEND_TRAILER option (repeated 4 times)
    Thread 8:
    Conditional jump or move depends on uninitialised value(s)
       at 0x10046AC47: _platform_memchr$VARIANT$Haswell (in /usr/lib/system/libsystem_platform.dylib)
       by 0x10025E9F6: __sfvwrite (in /usr/lib/system/libsystem_c.dylib)
       by 0x100268E45: __vfprintf (in /usr/lib/system/libsystem_c.dylib)
       by 0x10028E80E: __v2printf (in /usr/lib/system/libsystem_c.dylib)
       by 0x10028EAE0: __xvprintf (in /usr/lib/system/libsystem_c.dylib)
       by 0x1002649D1: vfprintf_l (in /usr/lib/system/libsystem_c.dylib)
       by 0x100262837: printf (in /usr/lib/system/libsystem_c.dylib)
       by 0x1000018C0: receive_cb (ekr_loop.c:121)
       by 0x100065BA3: sctp_append_to_readq (sctputil.c:5062)
       by 0x10001723E: sctp_service_reassembly (sctp_indata.c:464)
       by 0x100019A2A: sctp_process_data (sctp_indata.c:1236)
       by 0x1000210E9: sctp_common_input_processing (sctp_input.c:6151)
     Uninitialised value was created by a stack allocation
       at 0x100264A58: __vfprintf (in /usr/lib/system/libsystem_c.dylib)
    
    
    HEAP SUMMARY:
        in use at exit: 54,745 bytes in 449 blocks
      total heap usage: 22,036 allocs, 21,587 frees, 15,737,811 bytes allocated
    
    LEAK SUMMARY:
       definitely lost: 0 bytes in 0 blocks
       indirectly lost: 0 bytes in 0 blocks
         possibly lost: 0 bytes in 0 blocks
       still reachable: 19,970 bytes in 24 blocks
            suppressed: 34,775 bytes in 425 blocks
    Reachable blocks (those to which a pointer was found) are not shown.
    To see them, rerun with: --leak-check=full --show-leak-kinds=all
    
    For counts of detected and suppressed errors, rerun with: -v
    ERROR SUMMARY: 715 errors from 5 contexts (suppressed: 22 from 22)

**Comment by tuexen** [comment]
The above three issues are fixed in https://github.com/sctplab/usrsctp/commit/2be11d8ecc14e6ff84a3e85b29bdbcc11e8b2c7e
The other don't show up during CI.
