### ISSUE TITLE
Crash in sctp_add_to_readq()

### ISSUE THREAD

**Issue by jmquigs** [sctplab/usrsctp#105]
Hello

We use jitsi-videobridge which uses usrsctp internally to implement its data channels.  Under load in a production environment, we have observed frequent crashes in "sctp_add_to_readq()".  

We have modified the videobridge to receive a small message over the data channel for each connected client in a conference, which is then fanned out to other clients.  The message is sent at 10Hz per client.  Typically conferences are small (<10 users).  Usually only 1-2 clients per conference are sending the message simultaneously, often none are.

We've been unable to reproduce the crash in our testing environment.  We are able to reproduce a frequent "resource temporarily unavailable" message in our testing, which appears to originate in usrsctp itself when it detects that it can't add more data because the recipient's queue is already full (via a EWOULDBLOCK return code in sctp_output.c), but we don't know if that is related to the crash.

We have removed this excess use of the data channel, but will still observed at least one crash since deploying that code.  The usrsctp library that the videobridge uses is old and we are thinking of updating it to try to fix the issue.  Have there been any known fixes in this area, over the past year?

Here is the specific version we are using:
https://github.com/sctplab/usrsctp/blob/c53d43ee76673ee281806497eb43750c239c145f/usrsctplib/netinet/sctputil.c

Thanks

**Comment by tuexen** [comment]
The code has changed substantially in the last year. Whether the issue you are experiencing has been resolved or not is hard to tell. I would suggest to update to the latest code, test it and report if you find any issues.

**Comment by bbaldino** [comment]
We were seeing this same problem and updated to the latest and still see the issue.  The stack is:
C  [jna7288066205379263375.tmp+0x8200d]  sctp_add_to_readq+0x2b8
C  [jna7288066205379263375.tmp+0x7d9b0]
C  [jna7288066205379263375.tmp+0x7f31e]  sctp_ulp_notify+0x3bb
C  [jna7288066205379263375.tmp+0x8039d]  sctp_report_all_outbound+0xc19
C  [jna7288066205379263375.tmp+0x80721]  sctp_abort_notification+0xe9
C  [jna7288066205379263375.tmp+0x80981]  sctp_abort_an_association+0xfa
C  [jna7288066205379263375.tmp+0x3b8a6]
C  [jna7288066205379263375.tmp+0x3ca0a]  sctp_chunk_output+0x1d4
C  [jna7288066205379263375.tmp+0x7a6d6]  sctp_timeout_handler+0x413
C  [jna7288066205379263375.tmp+0x99534]
C  [jna7288066205379263375.tmp+0x99636]  user_sctp_timer_iterate+0xac
C  [libpthread.so.0+0x8184]

We're using the library via jni and are working getting logs enabled to try and get more information.  One piece we've gotten is that it appears the memory-tracking data structure is getting corrupted:
*** Error in `java': malloc(): smallbin double linked list corrupted: 0x00007fd3a4024b30 ***

This is on version e411f6652c2363e0a7ec89c4eab54fff73a5118c
