### ISSUE TITLE
File descriptor

### ISSUE THREAD

**Issue by diamantisk** [sctplab/usrsctp#106]
Hi there,
Im trying to modify a multiplatform project to adopt SCTP (including windows) and i think your project is a perfect fit. As far as i know, file descriptors actually are an integer number in comparison with windows that are a void handle. Usrsctp API is similar to sctp bsd sockets but it works with a socket struct instead of integers. What is the relation between the socket struct and file descriptors and how using this socket we will fetch the file descriptor number ? I need to dothis since all the other codebase of the project to which i am trying to use usrsctp works with FD integers, so if you can tell me how i will manage to get the fd from that socket it would be great. 
Thank you

**Comment by tuexen** [comment]
The userland stack does not provide file descriptors, just pointers to socket structures. So you have to deal with this. See the examples in programs/ how to deal with them.
