### ISSUE TITLE
C_FLAGS and CXX_FLAGS modified globally

### ISSUE THREAD

**Issue by jeremyong** [sctplab/usrsctp#107]
This is a pretty huge antipattern that prevents the project from being easily transitively included in an existing CMake project. Variables should only be set on a specific target

**Comment by weinrank** [comment]
You are talking about [these parts](https://github.com/sctplab/usrsctp/blob/master/usrsctplib/CMakeLists.txt#L261-L265) right?

Afaik CMake creates a new scope for every directory added by `add_subdirectory` as we do in the parent CMakeLists.txt. So adding variables to the CMAKE_C_FLAGS var by the CMakeLists.txt in the subdirectory shouldn't have any effect on other directories. 

I'm not that familiar with including projects. Improvements are always welcome! :)

**Comment by tuexen** [comment]
Closing since no feedback was provided.
