### ISSUE TITLE
Potential unaligned pointer value due to taking address of packed member.

### ISSUE THREAD

**Issue by ttsugriy** [sctplab/usrsctp#108]
usrsctp/usrsctplib/netinet/sctp_input.c:1708:15: error: taking address of packed member 'time_entered' of class or structure 'sctp_state_cookie' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                                                              &cookie->time_entered,
                                                               ^~~~~~~~~~~~~~~~~~~~
usrsctp/usrsctplib/netinet/sctp_input.c:2458:10: error: taking address of packed member 'time_entered' of class or structure 'sctp_state_cookie' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                                                  &cookie->time_entered, sctp_align_unsafe_makecopy,
                                                   ^~~~~~~~~~~~~~~~~~~~
2 errors generated.

usrsctp/usrsctplib/netinet/sctp_output.c:5928:30: error: taking address of packed member 'time_entered' of class or structure 'sctp_state_cookie' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
        (void)SCTP_GETTIME_TIMEVAL(&stc.time_entered);
                                    ^~~~~~~~~~~~~~~~
usrsctp/usrsctp#iphoneos-armv7,private-headers/netinet/sctp_constants.h:1020:46: note: expanded from macro 'SCTP_GETTIME_TIMEVAL'
#define SCTP_GETTIME_TIMEVAL(x) gettimeofday(x, NULL)
                                             ^
1 error generated.

After looking at how time_entered is used it seems like it's always passed by pointer, so wouldn't it make sense to change the sctp_state_cookie struct to use a pointer to time_entered instead?

**Comment by tuexen** [comment]
You can't put the pointer on the wire, you need to put the contents on the wire. I don't see why you would get an unaligned access, since the array in front of it has the length of 16 bytes.

**Comment by ttsugriy** [comment]
oh, sorry I didn't realize that this struct is sent over the wire. At the moment I don't get an unaligned access - this is just a compiler warning, which essentially means that this is not portable, since some platforms could have a different alignment, which would turn this into a bug. On the other hand, since it's sent over the wire, I'd be reluctant to change the format, since this will most likely break backwards compatibility :(
