### ISSUE TITLE
configure.ac:32: error: version mismatch.  This is Automake 1.15

### ISSUE THREAD

**Issue by valbok** [sctplab/usrsctp#110]
Hi

        $ git clone https://github.com/sctplab/usrsctp.git ;cd usrsctp; ./bootstrap
        configure.ac:32: error: version mismatch.  This is Automake 1.15,
        configure.ac:32: but the definition used by this AM_INIT_AUTOMAKE
        configure.ac:32: comes from Automake 1.11.  You should recreate
        configure.ac:32: aclocal.m4 with aclocal and run automake again.
        configure.ac:32: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
        configure.ac:32: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
        configure.ac:32: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
        configure.ac:35: installing './config.guess'
        configure.ac:35: installing './config.sub'
        configure.ac:32: installing './install-sh'
        configure.ac:32: installing './missing'
        programs/Makefile.am: installing './depcomp'

**Comment by tuexen** [comment]
I can't reproduce this on Mac OS X or FreeBSD HEAD. aclocal.m4 is locally generated. Is it possible that your autotools setup is inconsistent? Which OS are you seeing this on?

**Comment by valbok** [comment]
Hi Michael, probably you need Automake version 1.15 instead of 1.11.
I used Ubuntu 15.10.
Thanks

**Comment by tuexen** [comment]
Tested on Ubuntu 16.04 LTS, which uses automake 1.15. Please note that the FreeBSD I used for testing also uses that version and the Mac OS X machine uses automake 1.13.

What is the output of automake --version on your machine?

What is the first line of aclocal.m4 after running bootstrap?

**Comment by valbok** [comment]
Hi Michael,

    $ automake --version
    automake (GNU automake) 1.15
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

    $ head aclocal.m4 
    # generated automatically by aclocal 1.15 -*- Autoconf -*-

**Comment by valbok** [comment]
Seems I found the problem, had corrupted /usr/local/share/aclocal and have correct aclocal -I /usr/share/aclocal and now it works, thanks for time and work
