### ISSUE TITLE
Possible usage of uninitialised pointer in send_forward_tsn()

### ISSUE THREAD

**Issue by dreibh** [sctplab/usrsctp#114]
/tmp/buildd/libusrsctp-1.0.0~td100/usrsctplib/netinet/sctp_output.c: In function 'send_forward_tsn':
/tmp/buildd/libusrsctp-1.0.0~td100/usrsctplib/netinet/sctp_output.c:10975:21: error: 'strseq_m' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     strseq_m->flags = htons(PR_SCTP_UNORDERED_FLAG);
                     ^
/tmp/buildd/libusrsctp-1.0.0~td100/usrsctplib/netinet/sctp_output.c:10970:21: error: 'strseq' may be used uninitialized in this function [-Werror=maybe-uninitialized]
    strseq->sequence = htons((uint16_t)at->rec.data.stream_seq);

**Comment by dreibh** [comment]
This is probably a false positive, since the initialisation depends on the setting of "old". May be this could fix the warning, and make sure that an invalid pointer is not mistakenly used:
	if (old) {
		strseq = (struct sctp_strseq *)fwdtsn;
		strseq_m = NULL;
	} else {
		strseq = NULL;
		strseq_m = (struct sctp_strseq_mid *)fwdtsn;
	}

**Comment by tuexen** [comment]
Isn't this https://github.com/sctplab/usrsctp/issues/83?

**Comment by dreibh** [comment]
This is likely a duplicate of #83.

**Comment by tuexen** [comment]
Should be fixed by https://github.com/sctplab/usrsctp/commit/11e84cca0268816963c8d0909eab9030a19d5b5b
