### ISSUE TITLE
error: ‘chk’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

### ISSUE THREAD

**Issue by dreibh** [sctplab/usrsctp#119]
Building under Ubuntu 14.04 now results in this warning (=> error with -Werror):

/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_indata.c: In function ‘sctp_process_data’:
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_indata.c:1431:57: error: ‘chk’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     if (SCTP_TSN_GE(control->fsn_included, chk->rec.data.fsn)) {
                                                         ^
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_indata.c:1589:26: note: ‘chk’ was declared here
  struct sctp_tmit_chunk *chk;
                          ^
cc1: all warnings being treated as errors

**Comment by tuexen** [comment]
Why does it not complain about using chk in line 1413? Seems line a false positive, or am I missing something?

**Comment by dreibh** [comment]
I set "struct sctp_tmit_chunk *chk = NULL;" in line 1589. This fixes the warning. May be it is a false positive, since the warning does not appear e.g. under Ubuntu Xenial.

**Comment by tuexen** [comment]
It is a false positive.
