### ISSUE TITLE
Possible deadlock

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#131]
Hi guys,

I have a deadlock which I think is caused by something in the usrsctp library. The stack trace is indicating that, but unfortunately is not complete, because the binary was stripped:

```
(gdb) bt     
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:43
#1  0xb6edde7e in __pthread_cond_destroy (cond=0x308540 <sctp_it_ctl+48>) at pthread_cond_destroy.c:75
#2  0x0020cd74 in ?? ()
```

This deadlock happens when chrome somehow aborts the connection. At that point, 
usrsctp_sendv will fail with errno 104: Connection reset by peer
and usrsctp_recvv with errno 103: Software caused connection abort

@tuexen: is it possible that chrome did not upgraded the library yet?

**Comment by tuexen** [comment]
@shiretu I think Google is in the process of updating the sources. But I don't know which version they are using exactly or if they use local patches.

**Comment by shiretu** [comment]
I was informed that the deadlock can be reproduced relatively easy. I will compile everything without stripping, so we can get meaningful stack traces.

**Comment by shiretu** [comment]
@tuexen: quick question: is it possible to have some arbitrary textual information sent as part of the protocol datagrams and than use that to basically self describe the library version? I believe that will be very useful as it will enable us to see the exact version on both ends by just looking at the pcap file

**Comment by tuexen** [comment]
Great that it is easy to reproduce. Let me know once you have more information.
One could write a version string in the `COOKIE`, which is currently already being done. But only for identifying the stack at all. However, some people might call it information leakage.

**Comment by tuexen** [comment]
Any information available to reproduce the problem? Is it still reproducible with the lasted sources?

**Comment by shiretu** [comment]
@tuexen: no, is not happening anymore
