### ISSUE TITLE
how to compile library for armv7 ?

### ISSUE THREAD

**Issue by crookedbard** [sctplab/usrsctp#134]
I compiled the library for unix-like systems as written in git readme. When I compile the project with xcode on mac, it works. But when I try to link the library for Iphone 5 app then the linker throws an error: 
Showing All Messages
ld: warning: ld: warning: ignoring file /Users/....../libs/sctp/unix/lib/libusrsctp.a, file was built for archive which is not the architecture being linked (armv7): /Users/......./libs/sctp/unix/lib/libusrsctp.a ignoring file

**Comment by shiretu** [comment]
My configure line:

`./configure --enable-shared=no --disable-debug --prefix="${TEMP_FOLDER}/install/${LIBUSRSCTP_BASE_NAME}" ${LIBUSRSCTP_CUSTOM_CONFIGURE}`

For ARM:
```
IOS_SDK=iphoneos
IOS_ARCH_FLAGS="-arch armv7 -arch armv7s -arch arm64"
IOS_HOST_FLAGS="${IOS_ARCH_FLAGS} -miphoneos-version-min=7.0 -isysroot $(xcrun -sdk ${IOS_SDK} --show-sdk-path)"
OPT_FLAGS="-Os -g3"
export CC=$(xcrun -find -sdk ${IOS_SDK} cc)
export CPP=$(xcrun -find -sdk ${IOS_SDK} cpp)
export CXX=${CPP}
export CFLAGS="${IOS_HOST_FLAGS} ${OPT_FLAGS}"
export CXXFLAGS=${CFLAGS}
export LDFLAGS=${IOS_HOST_FLAGS}
export LIBUSRSCTP_CUSTOM_CONFIGURE="--host=arm-apple-darwin --enable-static --disable-shared --disable-inet --disable-inet6"
```

and for simulator:
```
IOS_SDK=iphonesimulator
IOS_ARCH_FLAGS="-arch i386 -arch x86_64"
IOS_HOST_FLAGS="${IOS_ARCH_FLAGS} -miphoneos-version-min=7.0 -isysroot $(xcrun -sdk ${IOS_SDK} --show-sdk-path)"
OPT_FLAGS="-Os -g3"
export CC=$(xcrun -find -sdk ${IOS_SDK} cc)
export CPP=$(xcrun -find -sdk ${IOS_SDK} cpp)
export CXX=${CPP}
export CFLAGS="${IOS_HOST_FLAGS} ${OPT_FLAGS}"
export CXXFLAGS=${CFLAGS}
export LDFLAGS=${IOS_HOST_FLAGS}
export LIBUSRSCTP_CUSTOM_CONFIGURE="--host=x86_64-apple-darwin --enable-static --disable-shared --disable-inet --disable-inet6"
```

**Comment by crookedbard** [comment]
Thank you! I am a bit of a novice in GNU make.  Can you tell me how you set those flags for ARM?
Do you add these flags 
```
IOS_SDK=iphoneos
IOS_ARCH_FLAGS="-arch armv7 -arch armv7s -arch arm64" .....
```
to a custom file and tell ./configure to use them? Or do you change makefile manually ?

**Comment by shiretu** [comment]
I do not touch the makefile. all those vars are used by configure script and the makefile will be generated. all lines with `export` defines variables which are used by configure script

**Comment by shiretu** [comment]
The rest are just temp vars used to compute the exported ones

**Comment by crookedbard** [comment]
sorry for silly questions but can you tell me once more.
I write this line in terminal: ./configure --enable-shared=no --disable-debug --prefix=/my custom path/
and what should I write in this place: ${LIBUSRSCTP_CUSTOM_CONFIGURE}
and where should I put those lines:
```
IOS_SDK=iphoneos
IOS_ARCH_FLAGS="-arch armv7 -arch armv7s -arch arm64"
...
```
if I write those lines in terminal it throws an error:
configure: WARNING: you should use --build, --host, --target
configure: error: unrecognized option: `-arch'

**Comment by tuexen** [comment]
If help is still needed, please re-open.
