### ISSUE TITLE
Add configuration setting to skip building programs

### ISSUE THREAD

**Issue by sorenskak** [sctplab/usrsctp#135]
Building usrsctp for Android we have the problem that one of the programs uses pthread_cancel() that is not available for android. Would be nice if there was a configuration setting to avoid building the test programs.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/281024f8e2e61d1f29fed7cc7bccfa003167b4cb for the autotools based build environment and in https://github.com/sctplab/usrsctp/commit/6c32195bf67a90bc4ce7e1c567778c1a1a642e7e for the cmake build environment.
