### ISSUE TITLE
Implicit declaration of function ‘mbuf_init’

### ISSUE THREAD

**Issue by sudeepb02** [sctplab/usrsctp#138]
Building from source exits with error code 1. Possible source of error is sctp_pcb.c:6815
Error : 
`error: implicit declaration of function ‘mbuf_init’ [-Werror=implicit-function-declaration]
  mbuf_init(NULL);
  ^~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:696: netinet/libusrsctp_la-sctp_pcb.lo] Error 1
make[1]: Leaving directory '/home/sudeep/usrsctp/usrsctplib'
make: *** [Makefile:405: all-recursive] Error 1
`

**Comment by krull** [comment]
@sudeepb02 agreed. Replicable results here as well:

```
netinet/sctp_pcb.c: In function 'sctp_pcb_init':
netinet/sctp_pcb.c:6815:2: error: implicit declaration of function 'mbuf_init' [-Werror=implicit-function-declaration]
  mbuf_init(NULL);
  ^
cc1: all warnings being treated as errors
Makefile:685: recipe for target 'netinet/libusrsctp_la-sctp_pcb.lo' failed
make[1]: *** [netinet/libusrsctp_la-sctp_pcb.lo] Error 1
make[1]: Leaving directory '/usr/local/src/usrsctp/usrsctplib'
Makefile:394: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by tuexen** [comment]
Thanks for reporting. I just fixed it. Sorry for the breakage.
