### ISSUE TITLE
Fedora 26 (upcoming version) build issues

### ISSUE THREAD

**Issue by dreibh** [sctplab/usrsctp#139]
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_pcb.c: In function 'sctp_load_addresses_from_init':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_pcb.c:7285:18: error: '%s' directive output truncated writing 74 bytes into a region of size 64 [-Werror=format-truncation=]
                 "%s:%d at %s", __FILE__, __LINE__, __func__);
                  ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_pcb.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 113 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_pcb.c:7379:18: error: '%s' directive output truncated writing 74 bytes into a region of size 64 [-Werror=format-truncation=]
                 "%s:%d at %s", __FILE__, __LINE__, __func__);
                  ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_pcb.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 113 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/build.make:402: usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_pcb.c.o] Error 1
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c: In function 'sctp_lower_sosend':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:14668:16: error: '%s' directive output truncated writing 77 bytes into a region of size 64 [-Werror=format-truncation=]
               "%s:%d at %s", __FILE__, __LINE__, __func__);
                ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 105 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c: In function 'sctp_sendall_iterator':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:7221:17: error: '%s' directive output truncated writing 77 bytes into a region of size 64 [-Werror=format-truncation=]
                "%s:%d at %s", __FILE__, __LINE__, __func__);
                 ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 108 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c: In function 'sctp_send_initiate_ack':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:5989:32: error: '%s' directive output truncated writing 77 bytes into a region of size 64 [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "%s:%d at %s", __FILE__, __LINE__, __func__);
                                ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 109 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: Leaving directory '/builddir/build/BUILD/libusrsctp-1.0.0~td114'
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/build.make:258: usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_output.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:160: usrsctplib/CMakeFiles/usrsctp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c: In function 'sctp_send_initiate_ack':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:5989:32: error: '%s' directive output truncated writing 77 bytes into a region of size 64 [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "%s:%d at %s", __FILE__, __LINE__, __func__);
                                ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 109 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c: In function 'sctp_lower_sosend':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:14668:16: error: '%s' directive output truncated writing 77 bytes into a region of size 64 [-Werror=format-truncation=]
               "%s:%d at %s", __FILE__, __LINE__, __func__);
                ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 105 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c: In function 'sctp_sendall_iterator':
/builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:7221:17: error: '%s' directive output truncated writing 77 bytes into a region of size 64 [-Werror=format-truncation=]
                "%s:%d at %s", __FILE__, __LINE__, __func__);
                 ^~            ~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os_userspace.h:434,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_os.h:72,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/usrsctplib/netinet/sctp_output.c:38:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 108 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [usrsctplib/CMakeFiles/usrsctp-static.dir/build.make:258: usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_output.c.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/libusrsctp-1.0.0~td114'
make[1]: Leaving directory '/builddir/build/BUILD/libusrsctp-1.0.0~td114'
make[1]: *** [CMakeFiles/Makefile2:123: usrsctplib/CMakeFiles/usrsctp-static.dir/all] Error 2
make: *** [Makefile:153: all] Error 2

**Comment by dreibh** [comment]
Reason: a buffer of size SCTP_DIAG_INFO_LEN is too small to store the whole snprintf() output.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/6cef329951cf0bd771f2f427373f4f160557d469.
