### ISSUE TITLE
Another Fedora 26 build issue

### ISSUE THREAD

**Issue by dreibh** [sctplab/usrsctp#140]
Another build issue, to to possibly too small buffer:

cd "/builddir/build/BUILD/libusrsctp-1.0.0~td114/programs" && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_timer.dir/link.txt --verbose=1
/builddir/build/BUILD/libusrsctp-1.0.0~td114/programs/datachan_serv.c:454:66: error: 'chan ' directive writing 5 bytes into a region of size 0 [-Werror=format-overflow=]
             sprintf((char *) &((&msg[0].reliability_params)[1]),"chan %d",stream);
                                                                  ^~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /builddir/build/BUILD/libusrsctp-1.0.0~td114/programs/datachan_serv.c:38:
/usr/include/bits/stdio2.h:33:10: note: '__builtin___sprintf_chk' output between 7 and 17 bytes into a destination of size 0
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: Leaving directory '/builddir/build/BUILD/libusrsctp-1.0.0~td114'


In programs/datachan_serv.c:
sprintf((char *) &((&msg[0].reliability_params)[1]),"chan %d",stream);
with:
struct rtcweb_datachannel_msg msg[4]; /* cheat to get space for label */

(This code is really ugly ...)

**Comment by tuexen** [comment]
I removed the file in https://github.com/sctplab/usrsctp/commit/8e4940f04c5c96847f6c35387b66cfb6006fee56.
