### ISSUE TITLE
question on heartbeat data sent

### ISSUE THREAD

**Issue by sonyangchang** [sctplab/usrsctp#148]
Hi  All.
 I have read the code in those days. But there is one thing that confused me a bit. Let me assume there is a state that no user data to be sent, but it has to send heart beat control packet. Is there a thread taking on such tasks?  It seems  the function sctp_heartbeat_timer calls sctp_send_hb which  puts the chunk in stcb->asoc.control_send_queue. But How does it sent out if there are no other datas to be sent?

**Comment by tuexen** [comment]
There is a timer running, which gets triggered from the timer thread.

**Comment by sonyangchang** [comment]
Yes, the timer is triggered to send a chunk in the queue(stcb->asoc.control_send_queue) in function(sctp_send_hb), but how the data get sent out?  This may not make myself clear. Or in other words, How the chunks in (asoc->control_send_queue) and (asoc->send_queue) are sent out? Is there is a thread that sends data out?  Because I just saw function put chunks in these two queues, how does the chunks being sent out is quite confusing.

**Comment by sonyangchang** [comment]
Ok I got it. It  is in deed the timer thread send the data out. sctp_timeout_handler(void *t){ sctp_chunk_output(inp, stcb, SCTP_OUTPUT_FROM_HB_TMR, SCTP_SO_NOT_LOCKED); }.
Thanks Tuexen!
