### ISSUE TITLE
Not able to connect multi homed

### ISSUE THREAD

**Issue by stfl** [sctplab/usrsctp#151]
I have big problems setting up a multi homed connection for testing purpose.. I am trying to set up CMT in the following but for now not even setting up primary and secondary paths works.

I have a test setup between two Linux VMs with two dedicated internal networks
```bash
11.1.1.1  <--->  11.1.1.2
12.1.1.1  <--->  12.1.1.2
````

When I do the following
```c
usrsctp_bindx(sctpsrc->sock, (struct sockaddr *)&addr4, 2, SCTP_BINDX_ADD_ADDR);
usrsctp_connectx(sctpsink->sock, (struct sockaddr *)&addr4_dest, 2, (sctp_assoc_t *)&(int){ SCTP_ASSOC_ID });
```
or even with 
```c
usrsctp_connect(sctpsink->sock, (struct sockaddr *)&addr4_dest[0], sizeof(struct sockaddr_in);
```
the route is not found properly.. I get ARP requests where 12.1.1.1 asks for 11.1.1.2...
If I bind to `INADDR_ANY` the same happens..

I looked at the debug and the code and it turns out that it tries `lo` which comes from a static index.. and then tries the last used addr..

```C
#define SCTP_GET_IF_INDEX_FROM_ROUTE(ro) 1 /* compiles...  TODO use routing socket to determine */
```

`arp` and `ip route` is set up properly on both machines so this shouldn't happen..

**Comment by stfl** [comment]
The same comes up when doing a regular `bind()` and `connect()` and adding the IPs once the connection is up..

```
SCTP_ASCONF
handle_asconf: asconf_limit=92, sequence=c606c3a4h
handle_asconf: Now processing first ASCONF. Try to delete old cache
process_asconf_add_ip: adding
IPv4 address: 12.1.1.2:2222
Adding an address (from:6) to the peer:
IPv4 address: 12.1.1.2:2222
Check for chunk output prw:131072 tqe:0 tf=0
Calling chunk OUTPUT
Calling ipv4 output routine from low level src addr:b010101
Destination is b010102
RTP route is 0x7f41a8014550 through
IP output returns 0
select 0
sctp_source_address_selection
Select source addr for:
IPv4 address: 12.1.1.2:2222
ifn lo
IPv6 address: 0:0:0:0:0:0:0:1:port:0 scope:0
IPv4 address: 127.0.0.1:0
Is destination preferred:
IPv4 address: 11.1.1.1:0
src_loop:0 src_priv:0 src_glob:1
dest_loop:0 dest_priv:0 dest_glob:1
YES
```

*Some of the output is added by me while looking at the code..*

**Comment by tuexen** [comment]
What happens if you don't bind to local addresses, but use the wildcard address. Binding local addresses works fine in the kernel stack, but not when running the code in userland...

**Comment by stfl** [comment]
the same happens if it is bound to `INADDR_ANY`
the interface that would be provided in FreeBSD by the struct sctp_route is `NULL` on linux.
Then addresses are only checked for the scope. like local, private or public..
not actual reachability..

`netinet/sctp_output.c:3164`
`sctp_choose_boundall()`

**Comment by tuexen** [comment]
Please note that source address selection doesn't really work with the userland stack, since you would need to duplicate the routing tree in the application. Can you try using UDP encaps? This would leave source address selection up to the kernel. I'm thinking that this might be a good workaround also for native SCTP...

**Comment by stfl** [comment]
I managed to trick the implementation now by setting different scope IP Addresses

```
192.168.0.1  <--->  192.168.0.2
12.1.1.1       <--->  12.1.1.2
```

it's not a clean solution but works for my experimentation setup..
I might test UDP encaps at one point.
