### ISSUE TITLE
why usrsctp undefine __APPLE__ macro

### ISSUE THREAD

**Issue by gyh007** [sctplab/usrsctp#152]
hello, i am new to usrsctp, i want to compile usrsctp as a static library, can you explain why usrsctp undefine  `__APPLE__` macro? thanks!

**Comment by tuexen** [comment]
The source is shared between multiple platforms. __APPLE__ is used when the code is compiled for running as a network kernel extension on Mac OS. This means running in the kernel. __Userspace_os_Darwin is used when the code is compiled as part of the userland on Mac  OS.

I know this is not perfect, but this is how it is now.

**Comment by pps83rbx** [comment]
That is insane. __APPLE__ is defined by apple compiler and should not be undefined. In my case suddenly something that I assumed to be 100% on apple builds suddenly wasn't working as expected thanks for that "novelty".

**Comment by tuexen** [comment]
> IMO it should be reopened as a bug that should be fixed.
Then do so. I agree, it should be improved.
