### ISSUE TITLE
sctp_userspace_get_mtu_from_ifn issues

### ISSUE THREAD

**Issue by lgrahl** [sctplab/usrsctp#157]
`if_indextoname` returns `ifname` or `NULL`. But the return value isn't being checked.

See: https://github.com/sctplab/usrsctp/blob/5b776478da5a4ed3ab935929c30c25d6e3fbf140/usrsctplib/netinet/sctp_userspace.c#L88:L105

From @jld's bug report, `if_index` is also always `0xffffffff`, so `if_indextoname` always fails which means a zerofilled interface name is being used in the `ioctl` call. (Formerly, it was stack garbage but Mozilla Core uses an old usrsctp version).

(This issue has been raised in https://bugzilla.mozilla.org/show_bug.cgi?id=1384292#c0 by @jld)

**Comment by tuexen** [comment]
Should be fixed in https://github.com/sctplab/usrsctp/commit/1313bd57676c1f22db222000059fc2e914ad94fa.
