### ISSUE TITLE
Need some information on sample for getting started ? 

### ISSUE THREAD

**Issue by peererror** [sctplab/usrsctp#164]
Hi, I wanted to ask what is the meaning of these ports  in samples 
[local_port] -- > local sctp port  
[local_encaps_port] --> local udp port ?  am I right here 
[remote_encaps_port] --> remote udp port ? am I right here 
What if I only want to use sctp over udp .. Can I do that with no raw sctp sockets is there any sample for that  ? and windows we do something like  

client.exe 192.168.1.2 9 0 5555 9999
why we provide 9 and 0 port here ? didn't  we already have given local and remote port .  

Thanks for your awesome  work

**Comment by tuexen** [comment]
You are missing [remote port] -> remote SCTP port, but the other port number are as you describe.
If you want to use UDP encaps, please provide the local and remote UDP encapsulation port. For example using `client.exe 192.168.1.2 9 0 5555 9999` that the client uses an ephemeral SCTP port as the local port, connects to the SCTP port 9, uses UDP encapsulation from UDP port 5555 to the UDP port 9999. There is no redundant information here.
