### ISSUE TITLE
question on infotype in send/recv function

### ISSUE THREAD

**Issue by sandylss** [sctplab/usrsctp#165]
Hi, I wonder if infotype in sendv() and recvv() must match? 
For example, if I use SCTP_SEND_SNDINFO in sendv(), do I have to use SCTP_RECVV_RCVINFO in recvv()?  What if I use other infotype?
Does socket do memory copy in terms of *info?

**Comment by lgrahl** [comment]
These questions should be covered by the [SCTP API Documentation [RFC6458]](https://tools.ietf.org/html/rfc6458#section-9.12).

> What if I use other infotype?

It can fail (with an error return code), produce undefined behaviour or provoke a crash.

> Does socket do memory copy in terms of *info?

If the question means whether you need to provide the memory for the info struct, then yes. Usually you'd just pass a reference from the stack as it doesn't require dynamic allocation.
