### ISSUE TITLE
New compile switches on older compilers

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#175]
Hi,

I get this on an older mac os x installation:

```
error: unknown warning option '-Wno-address-of-packed-member' [-Werror,-Wunknown-warning-option]
```

**Comment by tuexen** [comment]
Yepp, not all compilers support this. Is this critical?

**Comment by shiretu** [comment]
Hi Michael,

Is not unfixable. Would be nice to avoid using that switch tho. But I can upgrade the builders with newer compilers if needed.

Feel free to close this one with or without fix, I just need to know how should i proceed further.

Thanks!

**Comment by tuexen** [comment]
OK. Will fix the code such that `-Wnoaddress-of-packed-member` is not needed anymore.
