### ISSUE TITLE
Unable to set MTU when no SCTP association exists yet

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#180]
Hi,

I'm trying to manually set the MTU using the following code:

```
	struct sctp_paddrparams params;
	memset(&params, 0, sizeof (params));
	params.spp_flags = SPP_PMTUD_DISABLE;
	params.spp_pathmtu = 900;
	if (usrsctp_setsockopt(_pSCTPSocket, IPPROTO_SCTP, SCTP_PEER_ADDR_PARAMS, &params,
			sizeof (params)) < 0) {
		FATAL("Unable to disable MTU on the SCTP socket");
		return false;
	}
```

That call is executed after the socket is created and usrsctp_register_address called, before bind/connect calls.

The call succeeds, but the resulted MTU on the final packets is way above 900 (1284 to be more specific).

This interferes with some very restricted environments where the max MTU is 1000.

Is this an issue or am I doing something terribly wrong?

**Comment by tuexen** [comment]
The SCTP implementation (kernel stack or userland stack) does NOT support right now to set the MTU for future paths. According to [RFC6458](https://tools.ietf.org/html/rfc6458#section-8.1.12) this should be possible:
```
   spp_address:  This specifies which address is of interest.  If a
      wildcard address is provided, it applies to all current and future
      paths.
```
So this can be considered a bug.

What ist supported is setting this after the association exists. So do
```
	memset(&params, 0, sizeof (params));
	params.spp_address.ss_family = AF_CONN;
#ifdef HAVE_SCONN_LEN
	params.spp_address.ss_len = sizeof(struct sockaddr_conn);
#endif
	params.spp_flags = SPP_PMTUD_DISABLE;
	params.spp_pathmtu = 900;
	if (usrsctp_setsockopt(s_c, IPPROTO_SCTP, SCTP_PEER_ADDR_PARAMS, &params, sizeof(struct sctp_paddrparams)) < 0) {
		FATAL("Unable to disable MTU on the SCTP socket");
		return false;
	}
```
after the `usrsctp_connect()` call or the `usrsctp_accept()` call.

There was another bug, which is fixed in https://github.com/sctplab/usrsctp/commit/129f5ccdd697cd1c02f4aca9a7625c156890e242, resulting in sending packets 20 bytes too small.

What kind of networks need such an MTU?

**Comment by shiretu** [comment]
Thank you Michael,

I was missing the family setting. Will come back with the results after I apply the changes.

The link is through some exotic satellite Hw. I have a 700 ms constant delay. Any other settings you recommend for such environment?

Thank you

**Comment by tuexen** [comment]
No. But I'm not sure why it uses an MTU smaller than the minimum IPv6 one. So it can't handle IPv6 traffic. I just added another fix regarding the MTU setting: https://github.com/sctplab/usrsctp/commit/4f7f419c9fe3f531d0529a9209b2f4f52c645f70. You should now really see what is specified. The MTU value you provide is the space available for chunks in the packet. If not, please let me know. Will add a method for setting the MTU on the end-point.

**Comment by shiretu** [comment]
I have done the suggested changes to the code and is now working as expected (MTU is now honored) .

I do have some other issues tho. I'm trying to saturate the available bitrate which is not much (at most 10mbps) and it works intermittently: sometimes I can make that happen, sometimes it works well than suddenly stops completely. I do see SCTP data flowing, but seems like it gets stuck somewhere in the SCTP stack internals, as nothing comes in/out of SCTP.

Trying to capture both ends SCTP traffic, and create a proper bug report

**Comment by tuexen** [comment]
The code cited above works now. Closing this issue.
