### ISSUE TITLE
usrsctp_opt_info(...)

### ISSUE THREAD

**Issue by unlimitedcollabo** [sctplab/usrsctp#186]
Please implement this function, to be able to retrieve more information (like RTO via SCTP_GET_PEER_ADDR_INFO and so on).

**Comment by tuexen** [comment]
why don't you just use `usrsctp_getsockopt()` using the level `IPPROTO_SCTP` and the optname `SCTP_GET_PEER_ADDR_INFO`. It gives you everything you want.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/808cadd7503fa2a9d157f1b135fe4db8eb37b923.

**Comment by unlimitedcollabo** [comment]
This

```
struct sctp_paddrinfo status;
socklen_t opt_len = (socklen_t)sizeof(status);
if (usrsctp_getsockopt(sock, IPPROTO_SCTP, SCTP_GET_PEER_ADDR_INFO, &status, &opt_len) < 0) { 
     perror("getsockopt");                       
}
```

gives me:

> getsockopt: No such file or directory

**Comment by tuexen** [comment]
You have to fill the `spinfo_address` field in the `struct sctp_paddrinfo` to indicated which remote address you are interested in. See [RFC 6458](https://tools.ietf.org/html/rfc6458#section-8.2.2).
