### ISSUE TITLE
About Unused Defines

### ISSUE THREAD

**Issue by Kiddinglife** [sctplab/usrsctp#190]
Hi @tuexen and @everyone,

When I am going through source codes, I found something  at line 917 and 918 in file sctp_os_userspace.h shown below :
```c
/* (de-)register interface event notifications */
#define SCTP_REGISTER_INTERFACE(ifhandle, af)
#define SCTP_DEREGISTER_INTERFACE(ifhandle, af)
```
Those two macros not implemented but used in everywhere eg. in sctp_pcb.c,   **why is that ?**
```c
/* re-register address family type, if needed */
if ((sctp_ifap->ifn_p->num_v6 == 0) &&
   (sctp_ifap->ifn_p->registered_af == AF_INET6)) {
   SCTP_DEREGISTER_INTERFACE(sctp_ifap->ifn_p->ifn_index, AF_INET6);
   SCTP_REGISTER_INTERFACE(sctp_ifap->ifn_p->ifn_index, AF_INET);
```

Regards,
Jacky.

**Comment by tuexen** [comment]
Not sure. it seems to be empty on all platforms. Maybe it was used on a platform not supported anymore...
@stewrtrs Do you know?

**Comment by Kiddinglife** [comment]
@tuexen  thx.

**Comment by tuexen** [comment]
I removed the defines in https://github.com/sctplab/usrsctp/commit/733d535a079cb36f41ca599a49b17491034c4dbe.
