### ISSUE TITLE
About Particial Reliability

### ISSUE THREAD

**Issue by Kiddinglife** [sctplab/usrsctp#191]
Hi @tuexen and @everyone,

I pretty like usrsctp and I am now playing with source codes and rfc standards in my spare time.
I say sorry to you for having your time to response my 'simple' questions.

Basically I just want to know
 - If it is possible to create another 3 input queues for PR, unreliable unordered (same to udp) and unreliable sequenced transmission.  
 - Is it easier to implement PR by creating another input queue so that we do not have to mess up reliable ordered mechanism ?

I am happy to make contributions to usrsctp if you think it is a good idea to add unre-seq, re-seq, unre-seq and unre-unordered transmission into usrsctp.

Regards,
Jacky.

**Comment by tuexen** [comment]
I'm not sure why you want separate input queues. All the services you describe are supported...

**Comment by Kiddinglife** [comment]
Hi @tuexen, sctp seems not to support unreliable-sequenced message. 
eg. sender sends 1,2,3,4. receiver feels ok to receive 1,4 and 2,3 received after 1,4 will be discarded.

**Comment by tuexen** [comment]
The implementation supports the sending and receiving of unreliable ordered messages. So if the sender sends 1,2,3,4, the receiver receives 1, a FORWARD-TSN for 2, 3 and then a 4, it will deliver 1, 4 to the application. If that is not true, it is a bug. But it is supposed to work.
