### ISSUE TITLE
About Use of Lock

### ISSUE THREAD

**Issue by Kiddinglife** [sctplab/usrsctp#192]
Hi @tuexen and ### @everyone,

 > In Figure 1, ULP interactions to the various SCTP stack
implementations are represented by the dashed horizontal
line. In the methods we exposed to userspace, these ULP
interactions use locks to signal between the application and the
transport stack.  **When an application no longer has to block on   
either a send or receive, a wake-up occurs via these locks from the stack to the user.**
(cited from *Portable and Performant User space SCTP Stack conference paper july 2012*)

Is it possible to use lock-free queue right here instead of mutex or atomic operations?

Regards,
Jacky.

**Comment by tuexen** [comment]
Please note that the same source code is used in the FreeBSD kernel and you need to be intune with the locking and notification infrastructure there. Basically, usrsctp is the FreeBSD SCTP kernel stack running in user land.

**Comment by Kiddinglife** [comment]
@tuexen  thx.
