### ISSUE TITLE
Unable to cross compile usrsctp using arc-linux-uclibc toolchain in ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by sampathkumar81293** [sctplab/usrsctp#194]
Hi, I tried to cross compile usrsctp using arc-linux-uclibc toolchain in ubuntu 14.04 LTS. But the issue is that it errors out with the trace below at the end. 

``bin/bash ../libtool  --tag=CC   --mode=link arc-linux-uclibc-gcc  -g -O2 -std=c99 -pthread -D_GNU_SOURCE -pedantic -Wall -Werror -g -O0   -o tsctp tsctp.o ../usrsctplib/libusrsctp.la 
libtool: link: arc-linux-uclibc-gcc -g -O2 -std=c99 -pthread -D_GNU_SOURCE -pedantic -Wall -Werror -g -O0 -o .libs/tsctp tsctp.o  ../usrsctplib/.libs/libusrsctp.so -pthread -Wl,-rpath -Wl,/home/slingrooster/tars/open_source_libs_rooster/lib ``

``../usrsctplib/.libs/libusrsctp.so: undefined reference to `__sync_bool_compare_and_swap_4' ``
`` ../usrsctplib/.libs/libusrsctp.so: undefined reference to `__sync_fetch_and_sub_4' ``
`` ../usrsctplib/.libs/libusrsctp.so: undefined reference to `__sync_fetch_and_add_4' ``

Any leads are appreciated.
Thanks

**Comment by tuexen** [comment]
Possibly the code after https://github.com/sctplab/usrsctp/blob/master/usrsctplib/user_atomic.h#L87 does not work in your setup. You might need other implementations of the atomic operations...
