### ISSUE TITLE
Manual: usrsctp_socket documentation doesn't include ulp parameter

### ISSUE THREAD

**Issue by waywardmonkeys** [sctplab/usrsctp#198]
The documentation for `usrsctp_socket()` doesn't include the last parameter, the `ulp`.

I assume this is just a way for the application to store some data on the socket? But I didn't know what it stands for.

**Comment by waywardmonkeys** [comment]
If someone can say what `ulp` stands for and clarify the intent if it doesn't match what I suggested above, I will submit a PR to fix the docs.

**Comment by lgrahl** [comment]
It probably stands for *upper layer protocol info* and contains a pointer to some arbitrary context that's passed to the receive callback.

**Comment by waywardmonkeys** [comment]
Fixed by pull request #203.
