### ISSUE TITLE
Fix warnings found by -Wstrict-prototypes

### ISSUE THREAD

**Issue by ddkilzer** [sctplab/usrsctp#207]
Building usrsctp with clang and -Wstrict-prototypes shows two K&R C style function implementations in user_socket.c:  wakeup_one() and getsockaddr().

This was already changed in WebKit's copy of usrsctp:
https://bugs.webkit.org/show_bug.cgi?id=180757
https://trac.webkit.org/changeset/225958/webkit

**Comment by tuexen** [comment]
Thanks for bringing this to our attention. This should be fixed by https://github.com/sctplab/usrsctp/commit/081ef19f2b8363c9d98640b62053b8a4edeff764.
