### ISSUE TITLE
Resetting both incoming and outgoing stream locally

### ISSUE THREAD

**Issue by lgrahl** [sctplab/usrsctp#212]
I stumbled upon [this bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=559394) which resets both sides locally. Shouldn't [this](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctptransport.cc?rcl=76d9bd5b459ba9b4af728b3587104badcc94d432&l=808-818) be *illegal* in the API and return an error in the call to `usrsctp_setsockopt`?

**Comment by tuexen** [comment]
Why? This is completely valid as described in [RFC6525](https://tools.ietf.org/html/rfc6525#section-6.3.2).

The point is that you should not reset both direction when you use Stream Reconfig in the
context of data channels as described in [draft-ietf-rtcweb-data-channel-13](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.7).

**Comment by lgrahl** [comment]
Didn't know that but it makes perfect sense. :+1:
