### ISSUE TITLE
sendspace/recvspace functions

### ISSUE THREAD

**Issue by lgrahl** [sctplab/usrsctp#214]
The functions `usrsctp_sysctl_set_sctp_sendspace` and `usrsctp_sysctl_set_sctp_recvspace` don't seem to work for me (or I'm misunderstanding their purpose).

Raising the buffer to 1 MiB with an RTT of 10ms results in the same throughput as if it were at the default settings. Setting the buffer sizes via `usrsctp_setsockopt(socket, SOL_SOCKET, ...)` however works (and significantly improves throughput).

**Comment by tuexen** [comment]
The intended semantic is that using `usrsctp_sysctl_set_sctp_sendspace` and `usrsctp_sysctl_set_sctp_recvspace` set the default value for the send space and receive space used when creating sockets with the `usrsctp_socket()` call. It has no impact on already existing sockets. Can you provide an example where this does not work as intended?

**Comment by lgrahl** [comment]
Foolish me created the socket before calling these functions (without realising it). :wink:

**Comment by tuexen** [comment]
https://github.com/sctplab/usrsctp/commit/d89882d04900c80860874b5eb389b3ed3a0bca3d implements a workaround if INVARIANTS is not defined until there is a chance to fix the real cause of the problem.
