### ISSUE TITLE
Missing defines related to RFC8260

### ISSUE THREAD

**Issue by weinrank** [sctplab/usrsctp#217]
The declaration of I-DATA related defines are missing in `usrsctp.h`:
`SCTP_INTERLEAVING_SUPPORTED `
`SCTP_STREAM_SCHEDULER `
`SCTP_STREAM_SCHEDULER_VALUE `

**Comment by shiretu** [comment]
Oh, okay. I see that is producing the I-DATA chunks anyways. And works, in the sense that it transports the data. I have load balancing for the streams on app level too, probably that's what saves the day.

**Comment by lgrahl** [comment]
So, does it just use the I-DATA chunks but not do any kind of interleaving when applying this workaround?

**Comment by lgrahl** [comment]
@shiretu No, I was just wondering what happens in that case. :slightly_smiling_face:

**Comment by tuexen** [comment]
Just to be clear: The usage of I-DATA channels should be fine. What is missing is the interleaving feature of the stream schedulers. But I want to get the non-interleaving DATA and I-DATA handling stable at the receiver side before enabling the new feature on the sender side.

**Comment by shiretu** [comment]
We are using it in an environment where e we push data over many channels. Stream-like data. So far works without problems
