### ISSUE TITLE
Fix memory leak due to early return in usrsctp_connect()

### ISSUE THREAD

**Issue by ddkilzer** [sctplab/usrsctp#230]
The clang static analyzer detects a memory leak due to an early return  in usrsctp_connect().

More info in this bug and patch from the WebKit project:
https://bugs.webkit.org/show_bug.cgi?id=186009
https://trac.webkit.org/changeset/232236

Note that the leak from user_mbuf.c in clust_constructor_dup() was fixed differently upstream, and the leak in mb_ctor_clust() doesn't currently happen due to commented-out code.

**Comment by weinrank** [comment]
Regarding the change to `usrsctp_connect()`:
We're also seeing this report in our CI system.
I think you fixed a false positive.

The memory for the `sa` pointer is allocated within the `getsockaddr()` function.
If the `copyin()` operation fails, the allocated memory gets freed before `getsockaddr()` returns.
See: https://github.com/sctplab/usrsctp/blob/master/usrsctplib/user_socket.c#L695

**Comment by ddkilzer** [comment]
Yep, missed that originally. Feel free to close this then.

**Comment by tuexen** [comment]
Thanks for the feedback. Closing it...
