### ISSUE TITLE
Partial reliability configuration using usrsctp with WebRTC DataChannel

### ISSUE THREAD

**Issue by hjastenger** [sctplab/usrsctp#233]
I was wondering if it is possible to configure the sctp socket to have a maximum of retransmit tries on a message before failing to send the message. WebRTC DataChannel have this option configurable[1].

I noticed in the readme that you do have an option to set the failure limits[2]. But besides this it will probably close the association / connection I am not sure if the default values are easily changed to a custom value, please correct me if I'm wrong. I would prefer kind of like UDP behaviour, where I could specify SCTP to not retransmit any failed messages but keep the socket from closing.

1. https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/maxRetransmits
2. https://github.com/sctplab/usrsctp/blob/master/Manual.md#set-failure-limits

**Comment by lgrahl** [comment]
Certainly you can do that in usrsctp, see https://github.com/rawrtc/rawrtc/blob/master/src/librawrtc/sctp_transport.c#L405:L410
If you set the partial reliability value to `0` it doesn't retransmit.

If you're interested in a data channel implementation that you can use on top of ICE/DTLS, check out https://github.com/rawrtc/rawrtc-data-channel.

**Comment by lgrahl** [comment]
You're very welcome.

**Comment by hjastenger** [comment]
@lgrahl Sorry, first priority was closing the tickets. Thanks for the help, your solution works like a charm!

**Comment by hjastenger** [comment]
Is there a possibility that the current implementation has a bug regarding setting TTL on a connection? Currently I am facing conflicting connection characteristics when setting the pr_policy with SCTP_PR_SCTP_TTL and adding 0x00 to the pr_value. None of the packets on  this connection are dropped, the connection actually behaves reliable. I have noticed, using netem and tc, when setting an x percentage of packet loss that under the configuration with TTL of zero actually none of the packets are dropped. Setting the value for pr_value with another low value, either 1 or 2, makes the connection 'unreliable', I can see packets being dropped on this configuration.

**Comment by tuexen** [comment]
Using the value of 0 is special, it means that the message a unlimited lifetime. I agree that it seems to be unexpected in the context of `sctp_sendv()`, but the reason is that it is used that way in `sctp_sendmsg()` as specified in [RFC6458](https://tools.ietf.org/html/rfc6458#section-5.3.2) in the description of the `sinfo_timetolive` field.
