### ISSUE TITLE
error: unknown type name ‘kvaddr_t’

### ISSUE THREAD

**Issue by jevian-ma** [sctplab/usrsctp#246]
git clone https://github.com/sctplab/usrsctp
cd usrsctp
./bootstrap
./configure --prefix=/usr && make && make install

but
In file included from ./netinet/sctp.h:617:0,
                 from ./netinet/sctp_os_userspace.h:1059,
                 from user_environment.c:36:
./netinet/sctp_uio.h:1218:2: error: unknown type name ‘kvaddr_t’
  kvaddr_t socket;

**Comment by samkusin** [comment]
Same here (Ubuntu 16.04) .   Checkout the commit before the latest and try again for now.
https://github.com/sctplab/usrsctp/commit/40d3b40d6b91150480bbf8cc190f41b21c3a1893

**Comment by tuexen** [comment]
Should be fixed now. Sorry for the breakage.
