### ISSUE TITLE
Confusions about the use of mutex locker and condition in struct sockbuf 

### ISSUE THREAD

**Issue by Kiddinglife** [sctplab/usrsctp#261]
Hi mate,

```c++
struct sockbuf {
    /* __Userspace__ Many of these fields may
    * not be required for the sctp stack.
    * Commenting out the following.
    * Including pthread mutex and condition variable to be
    * used by sbwait, sorwakeup and sowwakeup.
    */
    /* struct	selinfo sb_sel;*/ /* process selecting read/write */
    /* struct	mtx sb_mtx;*/	/* sockbuf lock */
    /* struct	sx sb_sx;*/	/* prevent I/O interlacing */
    userland_cond_t sb_cond; /* sockbuf condition variable */
    userland_mutex_t sb_mtx; /* sockbuf lock associated with sb_cond */
    ..... ignored
} so_rcv, so_snd;
```

1. For me, two seprate threads processing recv and send routine should be thread safe.
So, can you tell me why we use **sb_mtx** to protect so_recv and so_snd?
2. If each apllication has its own unique copy of usrlib(enps udp socket inclusive) and register receive_cb to usrsctp , can we get ride of  the use of all the mutex lockers?

Regards.

**Comment by tuexen** [comment]
I'm sure one could do that, but you need to be careful... Not sure what else has to change, since I never looked into that direction...

**Comment by Kiddinglife** [comment]
Thank you for you quick reply. In order to make it more specific and clear, I refined and repharsed my words.

In terms of tcp/ip socket programming, an application process sends/receives ulp data to/from socket buffer and then notify tcp/ip process via signal for furture processing in which case process-level mutex locker and condition should be applied on the socket buffer for the prevention of race condition. 
Compared with usrsctp in terms of the rule above, :

0. The application of  
``` c++
  userland_cond_t sb_cond; /* sockbuf condition variable */
  userland_mutex_t sb_mtx; /* sockbuf lock associated with sb_cond */
 ```
makes sense **only when** it is serving multi application processes as same as tcp/ip stack does. Am I right?
1. If my application uses sctp_accept() to have a newly created scoket buffer, this means the ulp data must pass by socket buffer before processed by usrsctp library **(not usrsctp process)**. I guess this is a kind of compromise that caters for socket api standards (eg. socket(), listen(), bind() and more...), which should  have a negative impact on the application performances. So, what is the most efficient way to use usrsctp library in application process?  using primitives and recting to notifications defined in section _10. Interface with Upper Layer in RFC4960_?
2. If my application uses primitives and recting to notifications defined in section 10. Interface with Upper Layer of RFC4960 **plusing each application having its ow usrsctp library instance**, is it safe to get ride of `sb_cond` and `sb_mtx`?

Regards.
