### ISSUE TITLE
Message is split into multiple receive_cb notifications when larger than 66356 bytes

### ISSUE THREAD

**Issue by somtin** [sctplab/usrsctp#267]
Hi,

When sending a message that is larger than 66356 bytes, I get multiple callbacks on the receive callback.

To reproduce, change BUFFER_SIZE in ekr_client to 66357 and run the server and client with:

```
$ ./ekr_server 127.0.0.1 11111 127.0.0.1 22222

$ ./ekr_client 127.0.0.1 22222 127.0.0.1 11111
```

Output of ekr_server shows the following:

```
O 15:35:11.547723 0000 13 89 ef aa f4 e4 bd 27 ab b2 11 96 03 00 00 10 f7 00 36 89 00 01 00 b0 00 00 00 00 # SCTP_PACKET
Msg of length 66356 received via 0x7ffc4ebbccac:61354 on stream 1 with SSN 0 and TSN 4143986262, PPID 39, context 0.

O 15:35:11.548124 0000 13 89 ef aa f4 e4 bd 27 66 91 2d c4 03 00 00 10 f7 00 36 8a 00 01 ff 00 00 00 00 00 # SCTP_PACKET
Msg of length 1 received via 0x7ffc4ebbccac:61354 on stream 1 with SSN 0 and TSN 4143986262, PPID 39, context 0.

```

Ideally we'd like to receive the callback for that packet containing the entire packet - is this possible? Otherwise the only solution would be for me to implement fragmentation on top of SCTP, which seems silly.

**Comment by lgrahl** [comment]
The usrsctp buffer has a fixed size, so in case your datagram is larger, it will always be split up into chunks. You are supposed to look at the `MSG_EOR` flag that tells you whether the datagram is complete. See also #188.

**Comment by somtin** [comment]
Ah I see, was not aware of the MSG_EOR flag. Thanks for that!
