### ISSUE TITLE
sctp in Tizen OS

### ISSUE THREAD

**Issue by guypaskar** [sctplab/usrsctp#269]
Hello,

It seems that the Chromium web engine in Tizen was taken without the sctp library and therefore webrtc datachannels can't use it. I was wondering if there's a way to add sctp via NaCl (like in here - https://developer.samsung.com/tv/develop/extension-libraries/nacl/overview)

Thanks

**Comment by lgrahl** [comment]
You are probably aware that this would have to be embedded into an extension to Chromium. I would not recommend using NaCl here since that is deprecated in favour of WASM. Since this library is very much tied to OS APIs (sockets, files, ...), it will be ton of work before you would be able to compile it to WASM.

**Comment by guypaskar** [comment]
Hello,
Thank you for the reply.
I'm not aware that nacl is deprecated in Tizen. In fact, I know that they plan to keep supporting it (as opposed to chrome who ditched it)

If I want to compile it to nacl, would it still be ton of work?

**Comment by lgrahl** [comment]
In that case I guess it depends on whether the usual OS APIs are supported by NaCl. Easiest way to find out is to try and compile it for that. :slightly_smiling_face:
But I suspect that you will encounter problems very early. Even if you can get it to work at some point, you still need a data channel implementation, define API interfaces, etc. And once you're done with that, you still need to throw it onto an ICE/DTLS stack and I'm not sure you can easily access that (if it's included in the build at all).

It would probably be much easier to go the official way and get Chromium for Tizen to build with usrsctp.

**Comment by guypaskar** [comment]
You are probably right :)

**Comment by tuexen** [comment]
If there is still an issue, please re-open.
