### ISSUE TITLE
sctp_os_macosx.h missing?

### ISSUE THREAD

**Issue by mollyling** [sctplab/usrsctp#27]
`netinet/sctp_os.h` references `netinet/sctp_os_macosx.h`, but that file doesn't exist.  I don't know how this built before on mac os!

**Comment by tuexen** [comment]
This file is only needed when you build the network kernel extension, not the userland stack. You should be able to compile the userland stack on Mac OS X by just running
./bootstrap
./configure
make
At I can...

**Comment by mollyling** [comment]
This is for a separate build procedure.  Is `sctp_os.h` also not supposed to be needed when building in-kernel?

**Comment by tuexen** [comment]
sctp_os.h is used when building a kernel stack or a userland stack. You can use  a different build environment, but make sure you use the same -D and -U parameters as provided in the example build environment. Have a look at
https://github.com/sctplab/usrsctp/blob/master/configure.ac#L39
and
https://github.com/sctplab/usrsctp/blob/master/configure.ac#L43
for building on Mac OS X.

**Comment by mollyling** [comment]
Ah, great, thank you!
