### ISSUE TITLE
usrsctp_sysctl_set_sctp_strict_data_order is not defined

### ISSUE THREAD

**Issue by weishuyin** [sctplab/usrsctp#279]
I want to use ordered message delivery. As Manual.md says, I need to call usrsctp_sysctl_set_sctp_strict_data_order function. But this function is not defined. 
    I found that this function is deleted by commit d1f18af6d513d5e4f89691ef609263d42a4f92d5 in May 12, 2016.
    So, how to config ordered or unordered message delivery?

**Comment by tuexen** [comment]
That `systcl` variable only enforced that control chunk are located before data chunk. This is not related to order or unordered message delivery. Without specifying that you want unordered delivery, you get ordered delivery. So you don't have to do anything to get what you want.

**Comment by tuexen** [comment]
Have a look at the Socket API specification: [sctp_sendv](https://tools.ietf.org/html/rfc6458#section-9.12). The corresponding function `usrsctp_sendv()` is similar.

**Comment by weishuyin** [comment]
> Have a look at the Socket API specification: [sctp_sendv](https://tools.ietf.org/html/rfc6458#section-9.12). The corresponding function `usrsctp_sendv()` is similar.

Thank you, the Socket API specification is very useful. Now I understand it.
