### ISSUE TITLE
Unable to shutdown sctp

### ISSUE THREAD

**Issue by twisted89** [sctplab/usrsctp#28]
I'm having an issue where usrsctp_finish will never return 0 and shutdown cleanly. The code causing the problem is 
    if (SCTP_INP_INFO_TRYLOCK()) {
		if (!LIST_EMPTY(&SCTP_BASE_INFO(listhead))) {
			SCTP_INP_INFO_RUNLOCK();
			return (-1);
    }

Where listhead is never emptied and therefor gets stuck in a loop. Before calling usrsctp_finish I've tried using 
    usrsctp_shutdown(sctpSocket, SHUT_WR)
and
    usrsctp_deregister_address(ulp_info);
    usrsctp_close(sock);
Or combinations of the two without any success. I'm not sure if this is a bug or something I've missed? I'm using it under usermode windows.

**Comment by tuexen** [comment]
Calling shutdown(fd, SHUT_WR) or calling close() initiates the teardown of the association. You can only teardown the stack after all associations are gone. So you need to wait until the associations are terminated. If you don't want to wait, you can use the SO_LINGER option to force the sending of ABORTs when calling close(). That way you don't have to wait, but messages can get lost.

**Comment by twisted89** [comment]
My technical knowledge of SCTP is limited so sorry for my lack of understanding but what do you mean by associations? Are you referring to the binding of sctp to UDP port? As closing that first has no effect for me. 
No matter how long I wait usrsctp_finish never returns 0 so surely something is stuck somewhere?

**Comment by tuexen** [comment]
With association I mean an SCTP association (connections in the context of SCTP are called SCTP associations). If you just call usrsctp_close() you need to wait until the association has terminated. This can take a while... Just calling usrsctp_shutdown(SHUT_WR) initiates the teardown, but the end-point doesn't go away. If you want to use the non-graceful shutdown, you can use the SO_LINGER option.
See https://tools.ietf.org/html/rfc6458#section-8.1.4

**Comment by twisted89** [comment]
Ok, maybe this isn't right but I managed to finally get it to shutdown properly using both commands one after the other. 
usrsctp_shutdown(sctpSocket, SHUT_WR);
usrsctp_close(sctpSocket);

I'll set this to closed now.

**Comment by pppaulpeter** [comment]
> With association I mean an SCTP association (connections in the context of SCTP are called SCTP associations). If you just call usrsctp_close() you need to wait until the association has terminated. This can take a while... Just calling usrsctp_shutdown(SHUT_WR) initiates the teardown, but the end-point doesn't go away. If you want to use the non-graceful shutdown, you can use the SO_LINGER option. See https://tools.ietf.org/html/rfc6458#section-8.1.4

how long does it take usually? one seconds or one mintues?

**Comment by tuexen** [comment]
When you terminate the association in a non-graceful way, a packet with an ABORT chunk is sent, queued messages are reported to the upper layer and the association is gone.

**Comment by pppaulpeter** [comment]
> When you terminate the association in a non-graceful way, a packet with an ABORT chunk is sent, queued messages are reported to the upper layer and the association is gone.

Hi Tuexen,

thanks for the quick feedback. Is this a good way to close the sctp socket?
         usrsctp_deregister_address(sctp);
         usrsctp_shutdown(sctp->sock, SHUT_RDWR);
         usrsctp_close(sctp->sock);
now i have one problem is that after i close the sctp socket several times, i can't create the sctp socket any more with this function usrsctp_socket, the errno is 93. Any clue? Many thanks!
]Error creating usrsctp socket... (93)

**Comment by tuexen** [comment]
It doesn't make sense to call `usrsctp_shutdown()` right before `usrsctp_close()`. The functionality of the first call is part of the second.

The value of `errno` is platform specific. What are the parameters are you using when you call `usrsctp_socket()`? What is the output of `perror()` after hitting the error condition?

**Comment by pppaulpeter** [comment]
> It doesn't make sense to call `usrsctp_shutdown()` right before `usrsctp_close()`. The functionality of the first call is part of the second.
> 
> The value of `errno` is platform specific. What are the parameters are you using when you call `usrsctp_socket()`? What is the output of `perror()` after hitting the error condition?

Hi,

(sock = usrsctp_socket(AF_CONN, SOCK_STREAM, IPPROTO_SCTP, janus_sctp_incoming_data, NULL, 0, (void *)sctp))
i will print out the perror right now,thanks!

**Comment by tuexen** [comment]
> > It doesn't make sense to call `usrsctp_shutdown()` right before `usrsctp_close()`. The functionality of the first call is part of the second.
> > The value of `errno` is platform specific. What are the parameters are you using when you call `usrsctp_socket()`? What is the output of `perror()` after hitting the error condition?
> 
> Hi,
> 
> (sock = usrsctp_socket(AF_CONN, SOCK_STREAM, IPPROTO_SCTP, janus_sctp_incoming_data, NULL, 0, (void *)sctp)) i will print out the perror right now,thanks!

The call looks OK to me...

**Comment by pppaulpeter** [comment]
> > > It doesn't make sense to call `usrsctp_shutdown()` right before `usrsctp_close()`. The functionality of the first call is part of the second.
> > > The value of `errno` is platform specific. What are the parameters are you using when you call `usrsctp_socket()`? What is the output of `perror()` after hitting the error condition?
> > 
> > 
> > Hi,
> > (sock = usrsctp_socket(AF_CONN, SOCK_STREAM, IPPROTO_SCTP, janus_sctp_incoming_data, NULL, 0, (void *)sctp)) i will print out the perror right now,thanks!
> 
> The call looks OK to me...

Hi,

this is the perror:
_**Error creating usrsctp socket... strerror:Protocol not supported**_
it is quite stranger, the first few times connection are ok, then it return this error.

**Comment by tuexen** [comment]
That is `EPROTONOSUPPORT`. So I guess you either have not yet called `usrsctp_init()` or you already called `usrsctp_finish()`. Is that possible?

**Comment by pppaulpeter** [comment]
> usrsctp_init

yes, i called the usrsctp_finish(). it is my problem. i just want to close the socket nicely.  
But the orignal issue still exist which is after several times connection(create socket, connect socket and close socket), the thread just stuck in the call  usrsctp_socket. before the code work nicely, but recently probably is because the upgrading of chrome version, i got this problem. no idea how to sovle it. at the begining, i thougt the reason is i didn't close the scoket properly.

**Comment by pppaulpeter** [comment]
> > usrsctp_init
> 
> yes, i called the usrsctp_finish(). it is my problem. i just want to close the socket nicely. But the orignal issue still exist which is after several times connection(create socket, connect socket and close socket), the thread just stuck in the call usrsctp_socket. before the code work nicely, but recently probably is because the upgrading of chrome version, i got this problem. no idea how to sovle it. at the begining, i thougt the reason is i didn't close the scoket properly.

May i know is there any possibility the thread will be blocked in usrsctp_bind calling? i can't find any lock in usrsctp_bind, but my thread was blocked in this calling, any thoughts? many thanks! @tuexen
