### ISSUE TITLE
PR-SCTP issue if start fragment of a data chunk goes missing

### ISSUE THREAD

**Issue by smayoral** [sctplab/usrsctp#286]
Hi,

I will try to describe the problem I have using an unordered channel either with 
DATA_CHANNEL_RELIABLE_UNORDERED or with DATA_CHANNEL_PARTIAL_RELIABLE_REXMIT_UNORDERED.

My SCTP implementation sends:
DataChunk0Fragment0    TSN=0  Start/End
DataChunk1Fragment0    TSN=1  Start
DataChunk1Fragment1    TSN=2  End
DataChunk2Fragment0    TSN=3  Start/End
DataChunk3Fragment0    TSN=4  Start
DataChunk3Fragment1    TSN=5  End
DataChunk4Fragment0    TSN=6  Start/End
DataChunk5Fragment0    TSN=7  Start
DataChunk5Fragment1    TSN=8  End

usrsctp receives: (TSN=1 goes missing which is a start fragment)
DataChunk0Fragment0    TSN=0
DataChunk1Fragment1    TSN=2
DataChunk2Fragment0    TSN=3    (express delivery, highest_tsn_inside_nr_map=3, cumulative_tsn=0)
DataChunk3Fragment0    TSN=4    (Start Flag, fsn_included=4, top=4) 
DataChunk3Fragment1    TSN=5    
DataChunk4Fragment0    TSN=6    (express delivery, highest_tsn_inside_nr_map=6, cumulative_tsn=0)
DataChunk5Fragment0    TSN=7
DataChunk5Fragment1    TSN=8

I (sender) get following SACK Messages:
CumTsnAck CumTsn=0 Gap Start=2 End=2
CumTsnAck CumTsn=0 Gap Start=2 End=3
CumTsnAck CumTsn=0 Gap Start=2 End=4
CumTsnAck CumTsn=0 Gap Start=2 End=5
CumTsnAck CumTsn=0 Gap Start=2 End=6
CumTsnAck CumTsn=0 Gap Start=2 End=7
CumTsnAck CumTsn=0 Gap Start=2 End=8

My problem is that I have no idea what to send in the ForwardTSN message. I think I tried every possible combination but I never get the right DataChunks.
I would expect to get DataChunk2, DataChunk3, DataChunk4 and DataChunk5 but I get 

- DataChunk2 and DataChunk4 always since they are unfragmented.
- DataChunk5 depending of Tsn in ForwardTSN Message
- DataChunk3Fragment1 which is wrong since SCTP is configured reliable. SCTP must ensure the integrity of the data chunks.

Could you please give me some advice about the ForwardTSN Message? According to the RFC3758 cumTsn+StartGap-1 should be ok for the receiver.

Best Regards,
Sergio 

EDIT: I finally found a working case and this is when I select DATA_CHANNEL_RELIABLE and I send Data Chunks with the Unordered Flag unset. 
In this case the receiving queue will not be processed if a fragment gets lost and my ForwardTSN Message (cumTsn+StartGap-1) does what I expected.

**Comment by tuexen** [comment]
You wouldn't send a `FORWARD-TSN` chunk in case of a `DATA_CHANNEL_RELIABLE_UNORDERED` data channel or a `DATA_CHANNEL_PARTIAL_RELIABLE_REXMIT_UNORDERED` with a `Reliability Parameter` > 0. In both cases you would retransmit `TSN`=1 after receiving the third loss indication:
```
CumTsnAck CumTsn=0 Gap Start=2 End=4
```
This is describes as Fast Retransmission in RFC 4960.
Only for `DATA_CHANNEL_PARTIAL_RELIABLE_REXMIT_UNORDERED` with a `Reliability Parameter` = 0 you would send a `FORWARD-TSN` chunk in the above example. In that case you would abandon `TSN`=1 and `TSN`=2. So the `New Cumulative TSN` would be 2 and the stream identifier listed would be the one of the `DATA` chunk with `TSN`=1 and `TSN`=2. See the description in RFC 3758.

**Comment by smayoral** [comment]
Hi,
thank you very much for you reply.

the problem is that usrsctp library ignores my TSN=1 and TSN=2 because the library received TSN=4 before (start of a fragmented data chunk)

When the library gets my TSNs, the function **sctp_flush_reassm_for_str_seq** is called and following condition is checked:

if (!asoc->idata_supported && !ordered && **SCTP_TSN_GT(control->fsn_included, cumtsn)**) {

control->fsn_included is equal to 4 and cumtsn is equal to 2 and the Forward-TSNs are apparently ignored.

Another question is why you implemented express delivery for unfragmented data chunks but not for DataChunk3 or DataChunk5 is the example above since they were received completely. I think there is no reason to keep these data chunks in the queue.

Best regards,
Sergio.

**Comment by tuexen** [comment]
> Hi,
> thank you very much for you reply.
> 
> the problem is that usrsctp library ignores my TSN=1 and TSN=2 because the library received TSN=4 before (start of a fragmented data chunk)
Wasn't TSN=1 dropped on the wire? Are you saying TSN=2 is dropped by the SACK even though it was acked in a GAP?
> 
> When the library gets my TSNs, the function **sctp_flush_reassm_for_str_seq** is called and following condition is checked:
> 
> if (!asoc->idata_supported && !ordered && **SCTP_TSN_GT(control->fsn_included, cumtsn)**) {
> 
> control->fsn_included is equal to 4 and cumtsn is equal to 2 and the Forward-TSNs are apparently ignored.
fsn_included means fragment sequence number. Why are you referring to FORWARD-TSN?
> 
> Another question is why you implemented express delivery for unfragmented data chunks but not for DataChunk3 or DataChunk5 is the example above since they were received completely. I think there is no reason to keep these data chunks in the queue.
The implementation might not be optimal...

Best regards
Michael
> 
> Best regards,
> Sergio.

**Comment by smayoral** [comment]
Hi Michael,
I think it is difficult to explain the problem in this way. I will reproduce the problem again and send you the call stack of the usrsctp library after receiving each fragment.
But this should be easily reproduced:

- Send a sequence like the example above without waiting for SACKs (all fragments at once)
- Drop DataChunk1Fragment0 (Start Fragment) on the wire
- Use ForwardTSN to tell the receiver to ignore DataChunk1 and keep processing the received data

At the receiving side:

- I expect DataChunk0, DataChunk2, DataChunk3, DataChunk4, DataChunk5

- I actually get DataChunk0, DataChunk2 and DataChunk4 (fragment data chunks are not processed)

Hopefully the call stack adds some clarity to the problem. 

Best regards,
Sergio.

**Comment by tuexen** [comment]
> Hi Michael,
> I think it is difficult to explain the problem in this way. I will reproduce the problem again and send you the call stack of the usrsctp library after receiving each fragment.
> But this should be easily reproduced:
> 
> * Send a sequence like the example above without waiting for SACKs (all fragments at once)
> * Drop DataChunk1Fragment0 (Start Fragment) on the wire
> * Use ForwardTSN to tell the receiver to ignore DataChunk1 and keep processing the received data
> 
> At the receiving side:
> 
> * I expect DataChunk0, DataChunk2, DataChunk3, DataChunk4, DataChunk5

I agree.
> * I actually get DataChunk0, DataChunk2 and DataChunk4 (fragment data chunks are not processed)
> 

OK.

I can write a packetdrill script in the next days and test it on the FreeBSD kernel stack, which should behave identical to the usrsctp stack.

I'll post it here and will report whether it reproduces the issue you are seeing.

Best regards
Michael
> Hopefully the call stack adds some clarity to the problem.
> 
> Best regards,
> Sergio.

**Comment by tuexen** [comment]
The following `packetdrill` shows how the stack currently behaves:
```
 0.0 `sysctl -w net.inet.sctp.ecn_enable=0`
+0.0 `sysctl -w net.inet.sctp.pr_enable=1`
+0.0 `sysctl -w net.inet.sctp.asconf_enable=0`
+0.0 `sysctl -w net.inet.sctp.auth_enable=0`
+0.0 `sysctl -w net.inet.sctp.reconfig_enable=1`
+0.0 `sysctl -w net.inet.sctp.nrsack_enable=0`
+0.0 `sysctl -w net.inet.sctp.pktdrop_enable=0`

+0.0 socket(..., SOCK_STREAM, IPPROTO_SCTP) = 3
+0.0 fcntl(3, F_GETFL) = 0x2 (flags O_RDWR)
+0.0 fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK) = 0
+0.1 connect(3, ..., ...) = -1 EINPROGRESS (Operation now in progress)
+0.0 > sctp: INIT[flgs=0, tag=1, a_rwnd=..., os=..., is=..., tsn=1, ...]
+0.1 < sctp: INIT_ACK[flgs=0, tag=2, a_rwnd=1500, os=1, is=1, tsn=0, STATE_COOKIE[len=5, val=...]]
+0.0 > sctp: COOKIE_ECHO[flgs=0, len=5, val=...]
+0.1 < sctp: COOKIE_ACK[flgs=0]
+0.0 getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
// First complete message is received.
+0.0 < sctp: DATA[flgs=UBE, len=1468, tsn=0, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[], dups=[]]
+0.0 recv(3, ..., 2000, 0) = 1452
// First fragment of second message is missing.
+0.0 < sctp: DATA[flgs=UE, len=1116, tsn=2, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:2], dups=[]]
// Third complete message is received.
+0.0 < sctp: DATA[flgs=UBE, len=1416, tsn=3, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:3], dups=[]]
+0.0 recv(3, ..., 2000, 0) = 1400
// Fourth fragmented message is received. Could be delivered, but isn't.
+0.0 < sctp: DATA[flgs=UB, len=1416, tsn=4, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:4], dups=[]]
+0.0 < sctp: DATA[flgs=UE, len=1416, tsn=5, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:5], dups=[]]
+0.0 recv(3, ..., 3000, 0) = -1 EAGAIN (Resource temporarily unavailable)
// Fifth complete message is received.
+0.0 < sctp: DATA[flgs=UBE, len=1316, tsn=6, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:6], dups=[]]
+0.0 recv(3, ..., 2000, 0) = 1300
// Sixth fragmented message is received. Could be delivered, but isn't.
+0.0 < sctp: DATA[flgs=UB, len=1216, tsn=7, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:7], dups=[]]
+0.0 < sctp: DATA[flgs=UE, len=1216, tsn=8, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:8], dups=[]]
+0.0 recv(3, ..., 3000, 0) = -1 EAGAIN (Resource temporarily unavailable)
// Missing first fragment of second message is received.
+0.0 < sctp: DATA[flgs=UB, len=1116, tsn=1, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=8, a_rwnd=..., gaps=[], dups=[]]
// Second reassembled message gets delivered.
+0.0 recv(3, ..., 3000, 0) = 2200
// Fourth reassembled message gets delivered.
+0.0 recv(3, ..., 3000, 0) = 2800
// Sixth reassembled message gets delivered.
+0.0 recv(3, ..., 3000, 0) = 2400
// Tear down the association
+0.0 close(3) = 0
+0.0 > sctp: SHUTDOWN[flgs=0, cum_tsn=8]
+0.1 < sctp: SHUTDOWN_ACK[flgs=0]
+0.0 > sctp: SHUTDOWN_COMPLETE[flgs=0]
```
Basically, reassembled unordered messages might not get delivered as soon as possible. This is a limitation of the current implementation. I can try to look at removing this limitation...

**Comment by smayoral** [comment]
Hi,
you write "Missing first fragment of second message is received."
What if this message really gets lost? 
Did you try to use ForwardTSN? The library should deliver queued messages after processing ForwardTSN message but it doesn't.

In my tests, using ForwardTSN, the fragmented messages get never delivered, probably because the missing messages never arrive.

Thanks again for testing this issue.

**Comment by tuexen** [comment]
The point is if the first fragment is lost, it is retransmitted by the peer, if it is not abandoned.

However, if it is abandoned, you are right, there is a bug. The following scripts does NOT run:
```
 0.0 `sysctl -w net.inet.sctp.ecn_enable=0`
+0.0 `sysctl -w net.inet.sctp.pr_enable=1`
+0.0 `sysctl -w net.inet.sctp.asconf_enable=0`
+0.0 `sysctl -w net.inet.sctp.auth_enable=0`
+0.0 `sysctl -w net.inet.sctp.reconfig_enable=1`
+0.0 `sysctl -w net.inet.sctp.nrsack_enable=0`
+0.0 `sysctl -w net.inet.sctp.pktdrop_enable=0`

+0.0 socket(..., SOCK_STREAM, IPPROTO_SCTP) = 3
+0.0 fcntl(3, F_GETFL) = 0x2 (flags O_RDWR)
+0.0 fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK) = 0
+0.1 connect(3, ..., ...) = -1 EINPROGRESS (Operation now in progress)
+0.0 > sctp: INIT[flgs=0, tag=1, a_rwnd=..., os=..., is=..., tsn=1, ...]
+0.1 < sctp: INIT_ACK[flgs=0, tag=2, a_rwnd=1500, os=1, is=1, tsn=0, FORWARD_TSN_SUPPORTED[], STATE_COOKIE[len=5, val=...]]
+0.0 > sctp: COOKIE_ECHO[flgs=0, len=5, val=...]
+0.1 < sctp: COOKIE_ACK[flgs=0]
+0.0 getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
// First complete message is received.
+0.0 < sctp: DATA[flgs=UBE, len=1468, tsn=0, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[], dups=[]]
+0.0 recv(3, ..., 2000, 0) = 1452
// First fragment of second message is missing.
+0.0 < sctp: DATA[flgs=UE, len=1116, tsn=2, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:2], dups=[]]
// Third complete message is received.
+0.0 < sctp: DATA[flgs=UBE, len=1416, tsn=3, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:3], dups=[]]
+0.0 recv(3, ..., 2000, 0) = 1400
// Fourth fragmented message is received. Could be delivered, but isn't.
+0.0 < sctp: DATA[flgs=UB, len=1416, tsn=4, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:4], dups=[]]
+0.0 < sctp: DATA[flgs=UE, len=1416, tsn=5, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:5], dups=[]]
+0.0 recv(3, ..., 3000, 0) = -1 EAGAIN (Resource temporarily unavailable)
// Fifth complete message is received.
+0.0 < sctp: DATA[flgs=UBE, len=1316, tsn=6, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:6], dups=[]]
+0.0 recv(3, ..., 2000, 0) = 1300
// Sixth fragmented message is received. Could be delivered, but isn't.
+0.0 < sctp: DATA[flgs=UB, len=1216, tsn=7, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:7], dups=[]]
+0.0 < sctp: DATA[flgs=UE, len=1216, tsn=8, sid=0, ssn=0, ppid=53]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[2:8], dups=[]]
+0.0 recv(3, ..., 3000, 0) = -1 EAGAIN (Resource temporarily unavailable)
// Second message was abandoned by peer.
+0.0 < sctp: FORWARD_TSN[cum_tsn=2, ids=[{0,0}]]
+0.0 > sctp: SACK[flgs=0, cum_tsn=8, a_rwnd=..., gaps=[], dups=[]]
// Fourth reassembled message gets delivered.
+0.0 recv(3, ..., 3000, 0) = 2800
// Sixth reassembled message gets delivered.
+0.0 recv(3, ..., 3000, 0) = 2400
// Tear down the association
+0.0 close(3) = 0
+0.0 > sctp: SHUTDOWN[flgs=0, cum_tsn=8]
+0.1 < sctp: SHUTDOWN_ACK[flgs=0]
+0.0 > sctp: SHUTDOWN_COMPLETE[flgs=0]
```
It hangs at the `recv()` call for the fourth message. Will look into it.

**Comment by smayoral** [comment]
That is exactly the problem I am having, nice that you could also reproduce it.
