### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by nxrighthere** [sctplab/usrsctp#287]
I just performed code analysis using PVS-Studio, and the application detected up to 560 warnings with various levels.

Here's a beautiful and convenient HTML report for you:
[usrsctp_analysis.zip](https://github.com/sctplab/usrsctp/files/2709132/usrsctp_analysis.zip)

**Comment by nxrighthere** [comment]
I believe that there are many false positive warnings, but still, maybe you will find something that deserves some attention.

**Comment by tuexen** [comment]
Thanks for providing the information. There are false positives in the area of `struct sockaddr` handling, but I'll go through the list. I also realised that PVS-Studio provides a free license for Open Source project. So we might be able to integrate this into our CI. We currently use the clang static analyzer and Coverity. Adding one more would be great if possible.

**Comment by weinrank** [comment]
@tuexen I’ll try to implement the PVS-Studio in our CI System.

**Comment by tuexen** [comment]
@weinrank Cool!

**Comment by weinrank** [comment]
PVS-Studio seems to be a commercial product without a free license.
I'll skip this tool.

**Comment by tuexen** [comment]
@weinrank: Really? Isn't  https://www.viva64.com/en/b/0600/ one? It is not yet 2019, but we can see next year...
