### ISSUE TITLE
compile error: variable shadowing 

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#288]
```
usrsctplib/netinet/sctp_input.c: In function 'sctp_handle_stream_reset_response':
usrsctplib/netinet/sctp_input.c:3964:112: error: declaration of '__bsv' shadows a previous local [-Werror=shadow]
usrsctplib/netinet/sctp_input.c:3964:65: error: shadowed declaration is here [-Werror=shadow]
usrsctplib/netinet/sctp_input.c:3964:119: error: declaration of '__bsx' shadows a previous local [-Werror=shadow]
usrsctplib/netinet/sctp_input.c:3964:72: error: shadowed declaration is here [-Werror=shadow]
```

This is on an older arm compiler, but not sure about the exact version. I will come back with the necessary version info if required, but i believe that the error is quite self explanatory

**Comment by weinrank** [comment]
Thanks for the report, which OS?

**Comment by shiretu** [comment]
That is linux based on OpenWRT

**Comment by shiretu** [comment]
It was arm gcc 4.7.0 with uclibc .
Removed the -Wshadow for that particular case. I hope it does not have weird side effects. For the record, I’ve made a test by “correcting” that statement using an intermediate variable, but it complained about the same “error” in a different place. This time a variable name was shadowing a static global function.

**Comment by shiretu** [comment]
And happy new year for everyone involved. Grateful for this library, keep up the standards, this is good!

**Comment by tuexen** [comment]
I consider this compiler warning as a false positive.
