### ISSUE TITLE
Connection between client and server started in one process using UDP_ENCAPS

### ISSUE THREAD

**Issue by proller** [sctplab/usrsctp#29]
I want make some game working via sctp.
now game can works in next modes:
client (will connect to remote server)
server
server-client (start server; then start client and connect to server; allow connect other players)
singleplayer ( start server; then start client and connect to server ) (same as server-client, but deny external connects)

Now client and server works fine.
but server-client possible only in sudo mode without using udp_encaps

i found manual packet sending in ekr_loop.c is this only way?

**Comment by h8liu** [comment]
Hi @proller ,

Like you, I did not make it work the first time, but have it (somehow) working now. Here are some tips I personally find to make it work in single process, without root:

- You still need to set the remote UDP encapsulation port, like the way you would do for two processes on the same machine.
- It might be helpful to turn off blackhole here.

**Comment by proller** [comment]
works now!
hints:
use only one usrsctp_init(port) with udp port of server 

use 
usrsctp_setsockopt(sock, IPPROTO_SCTP, SCTP_REMOTE_UDP_ENCAPS_PORT ...
only on clients
