### ISSUE TITLE
Backport event loop support from usrsctp-neat

### ISSUE THREAD

**Issue by lgrahl** [sctplab/usrsctp#292]
Would be the only thing left I need to be able to use the upstream usrsctp in RAWRTC. :slightly_smiling_face:

**Comment by weinrank** [comment]
PRs welcome! :)

**Comment by ibc** [comment]
> PRs welcome! :)

PR does exist: #38. It was just discarded because _"Support for external event loop is being worked on in the NEAT fork or usrsctp to get some experience. This will be merged eventually."_ However [usrsctp-neat](https://github.com/NEAT-project/usrsctp-neat/) is not active at all.

**Comment by lgrahl** [comment]
AFAIK they are not entirely identical approaches but I don't actually care about which is being merged... obviously, it should be the *better* one. Speaking for myself, I guess one of the reasons why it takes so long is that #38 is huge and should be split up into small, digestible PRs.

**Comment by ibc** [comment]
Well, we'll do it soon. And will also provide a PR to support GYP. But given that your Meson #300 PR was ignored I don't have any hope.

**Comment by lgrahl** [comment]
Maybe you should talk to @tuexen and @weinrank on how to approach the issue of backlogged PRs. Luckily, #300 is not a pressing issue for me at the moment.

**Comment by ibc** [comment]
We'll do separate and specific PRs for both single-thread and GYP support. We'll fight them once done :)

**Comment by dreibh** [comment]
Is there any update on merging the changes of usrsctp-neat, or making libneat work with the upstream version of usrsctp?

**Comment by tuexen** [comment]
I'm not sure if anyone is working on neat right now...

**Comment by ibc** [comment]
Hi, we forked usrsctp and added "single-thread" support. It's identical to PR #38 but does not include changes other than those to allow single thread operation:

https://github.com/sctplab/usrsctp/compare/master...versatica:single-thread

We are using it and works fine. Would you accept a PR?

**Comment by tuexen** [comment]
If it is a PR adding only that feature and not breaking backwards compatibility, I would love to integrate it.

**Comment by ibc** [comment]
Great, will do it soon.

**Comment by jmillan** [comment]
@tuexen,

Please find the PR #339 synchronised with master branch. It's essentially a cleanup of #38 with everything filtered but the the single thread implementation.

I can squash the commits into a single one if you like.

**Comment by tuexen** [comment]
@lgrahl Can this be closed since we have https://github.com/sctplab/usrsctp/commit/f6aa4b0859f7e55c9dc092f2d047d1129e09d66b in the master tree now?

**Comment by lgrahl** [comment]
Yup. If there's anything missing, I'll reopen.

**Comment by lgrahl** [comment]
Works well - thanks a lot!
