### ISSUE TITLE
Set SCTP thread names

### ISSUE THREAD

**Issue by ikonst** [sctplab/usrsctp#3]
It would be useful to name the threads created in usrsctplib/user_recv_thread.c.

Here's sample code for Linux:
```
    if (prctl (PR_SET_NAME, (unsigned long int) thread_name, 0, 0, 0))
      printf("Failed to set thread name");
```

For Darwin:
```
  if (pthread_setname_np (name))
      printf("Failed to set thread name");
```

For Windows:
```
void
SetThreadName (DWORD dwThreadID, LPCSTR szThreadName)
{
  THREADNAME_INFO info;
  info.dwType = 0x1000;
  info.szName = szThreadName;
  info.dwThreadID = dwThreadID;
  info.dwFlags = 0;

  __try {
    RaiseException (0x406D1388, 0, sizeof (info) / sizeof (DWORD),
        (DWORD *) & info);
  }
  __except (EXCEPTION_CONTINUE_EXECUTION) {
  }
}
```

**Comment by tuexen** [comment]
Which versions of Windows support this?

**Comment by ikonst** [comment]
I think this mechanism appeared around Visual Studio 2003, and [it's documented in a KB article](https://msdn.microsoft.com/en-us/library/xcb2z8hs.aspx).

[This blog post](http://blogs.msdn.com/b/stevejs/archive/2005/12/19/505815.aspx) explains some more, but basically it's a harmless SEH exception, since it's immediately caught with EXCEPTION_CONTINUE_EXECUTION. When a debugger is attached, however, since it intercepts exceptions, it recognizes this as a thread-name-setting API "by convention".

**Comment by tuexen** [comment]
Hmm. I haven't integrated the Windows part, since it requires C++, which I want to avoid, if possible, since it may result in problem for projects using this library.

**Comment by ikonst** [comment]
The Windows part requires SEH which is a Microsoft extension to C, and is expected to exist in any Windows-targeting C compiler. It is not the same as C++ exceptions -- i.e. the keyword is `__try` and `__except`, not `try` and `except`.

Therefore, your library will not require a C++ compiler or runtime by using these keywords. (Of course, they're only available on Windows, so the code should be in a proper #ifdef section.)

**Comment by ikonst** [comment]
btw, thanks for your work!
