### ISSUE TITLE
Advice for low-latency applications/fast-paced games

### ISSUE THREAD

**Issue by nxrighthere** [sctplab/usrsctp#302]
I'm building a new networking library on top of SCTP using one to one setup with no delay option and multiple streams for low-latency applications/fast-paced games, and in general, it works great. While experimenting with SCTP options I noticed that `sctp_rto_min_default` set to zero leads to faster packets transmission without any delay, datagrams delivered instantly. How this option affects transmission logic under the hood, it's fine to set it to zero?

Also, it would be great if you can advice tweaking any other options to achieve lower latencies/faster data delivery. Thanks!

**Comment by nxrighthere** [comment]
Despite the fact that I closed the issue, any info is still highly welcome. 😼

**Comment by nxrighthere** [comment]
@tuexen Is there any sense to switch the default congestion control to RTCC for networking games in order to minimize delays and better estimations for real-time communications?

**Comment by tuexen** [comment]
If I remember it correctly, it is an experimental CC developed by @stewrtrs . Possibly he can answer.

**Comment by grootgordon** [comment]
Could you share any advantage or disadvantage between default congestion(SCTP_CC_RFC2581) vs RTCC for your low-latency applications?
Thanks. @nxrighthere

**Comment by reececomo** [comment]
+1 to the above, also keen to read more about the MS QUIC datagram ext.

have a realtime physics game over webrtc and would love to cut any speed corners we can
