### ISSUE TITLE
Strange behavior with different compilers on Windows

### ISSUE THREAD

**Issue by nxrighthere** [sctplab/usrsctp#303]
I noticed a strange behavior while tuning SCTP options on Windows. When the library is compiled with GCC, these functions:
`usrsctp_sysctl_set_sctp_no_csum_on_loopback(1);`
`usrsctp_sysctl_set_sctp_nr_incoming_streams_default(10);`
`usrsctp_sysctl_set_sctp_nr_outgoing_streams_default(10);`
return zero. But when the library is compiled with MSVC they return `-1`.

Any idea why this happens?

**Comment by tuexen** [comment]
No.  You can use `printf` for debugging: Instrument the macro `USRSCTP_SYSCTL_SET_DEF`, which is defined in [user_socket.c:3558](https://github.com/sctplab/usrsctp/blob/master/usrsctplib/user_socket.c#L3558).
@weinrank Can you reproduce it on Windows?

**Comment by weinrank** [comment]
I'll check that...

**Comment by weinrank** [comment]
I can't reproduce the issue, would you provide more information about it?
- OS (Win32/Win64?)
- MSVC version
- CMAKE/Makefile?

I've added the following tests to our `ekr_loop` example program:
https://github.com/weinrank/usrsctp/commit/15f2be86438b980baa650af17415f012b1c3e3be?diff=split

Our Windows buildbot (Win7 - MSVC) output:
http://buildbot.nplab.de:48010/builders/windows-7/builds/97/steps/shell_9/logs/stdio

```
### [302] - RETVAL 0
### [305] - RETVAL 0
### [308] - RETVAL 0
Change send socket buffer size from 262144 to 4194304.
```

**Comment by nxrighthere** [comment]
Sorry, the problem in my fork for MinGW... 😓
