### ISSUE TITLE
Ignore incoming connection with one to one setup

### ISSUE THREAD

**Issue by nxrighthere** [sctplab/usrsctp#313]
I wonder, it's okay to not call `usrsctp_accept()` within the up-call on a server in order to ignore incoming connection or there's a better approach? My goal is to prevent any incoming connection for a while and then resume listening again.

**Comment by tuexen** [comment]
When you don't want to accept anymore, call `listen(fd, 0)`, when you want to accept again call `listen()` with a positive second argument... That should do the trick.

**Comment by nxrighthere** [comment]
Thanks, it seems that it works. 👍
