### ISSUE TITLE
usrsctp_getsockopt() always returns -1

### ISSUE THREAD

**Issue by ibc** [sctplab/usrsctp#322]
```c
char buffer[4096];
socklen_t bufferLen;
int ret;

// Check if SCTP_RESET_STREAMS has been negotiated.
ret = usrsctp_getsockopt(this->socket, IPPROTO_SCTP, SCTP_RESET_STREAMS, buffer, &bufferLen);
```

The remote peer **does** support `SCTP_RESET_STREAMS` (it's Chrome or Firefox, which use usrsctp). However the code above always returns -1. so, unless I'm doing something wrong above, it's kinda useless.

**Comment by lgrahl** [comment]
Untested but I think you forgot to initialise the length to a valid value. See also [RFC 6525, sec 6.3.2](https://tools.ietf.org/html/rfc6525#section-6.3.2).

**Comment by ibc** [comment]
> Untested but I think you forgot to initialise the length to a valid value. See also [RFC 6525, sec 6.3.2](https://tools.ietf.org/html/rfc6525#section-6.3.2).

This is about `usrsctp_getsockopt()` :)


> Edit: Oh, you want to check whether it has been negotiated... see https://github.com/rawrtc/rawrtc-data-channel/blob/c9fe19915a4e7342ed29cf2d66c78c2fbb2e7a4a/src/sctp_transport/transport.c#L773

Cool, so we can read it during the connection and store it somewhere instead of using the non-working `usrsctp_getsockopt()`. Thanks :)

> But you don't even need to do that. The reset stream call will just fail if you do it to close a WebRTC data channel.

Yes, I know. I just want to avoid a "warn" log in my server.

**Comment by lgrahl** [comment]
https://github.com/sctplab/usrsctp/blob/e111d19dd609d93a91a60c07a3d3ce26922688b6/Manual.md#socket-options-supported-by-usrsctp

Not marked as readable. But there are probably other ways to read the negotiated extensions.

**Comment by ibc** [comment]
> Not marked as readable.

Good point! 

> But there are probably other ways to read the negotiated extensions.

Who knows.

**Comment by tuexen** [comment]
You can use the `SCTP_RECONFIG_SUPPORTED` socket option to enable/disable negotiation before the association has been established and to check if support was negotiated after the association is up. The value has the type `struct sctp_assoc_value`.

**Comment by ibc** [comment]
Thanks @tuexen. So I'll use `usrsctp_getsockopt()` with `SCTP_RECONFIG_SUPPORTED`.

BTW do you also mean that `SCTP_RECONFIG_SUPPORTED` should be used in `usrsctp_setsockopt()`?

**Comment by ibc** [comment]
I don't see that `SCTP_RECONFIG_SUPPORTED` is defined at all:

```c
struct sctp_assoc_value av;

av.assoc_id    = SCTP_ALL_ASSOC; // No idea.
av.assoc_value = 1;

int ret = usrsctp_setsockopt(this->socket, IPPROTO_SCTP, SCTP_RECONFIG_SUPPORTED, &av, sizeof(av));
```

=> `error: use of undeclared identifier 'SCTP_RECONFIG_SUPPORTED'`

**Comment by tuexen** [comment]
Now they are (I was looking at the kernel implementation...): https://github.com/sctplab/usrsctp/commit/aae874823883fac1948e37b5436be496951d885a.

**Comment by tuexen** [comment]
> Thanks @tuexen. So I'll use `usrsctp_getsockopt()` with `SCTP_RECONFIG_SUPPORTED`.
> 
> BTW do you also mean that `SCTP_RECONFIG_SUPPORTED` should be used in `usrsctp_setsockopt()`?

Yes, you can. But on a one-to-one style socket (`SOCK_STREAM`) you can only use it on the listening socket or on an unconnected socket. In this case, `av.assoc_id` is ignored. When using on a one-to-many style socket (`SOCK_SEQPACKET`), you can use it for all future associations by setting `av.assoc_id` to `SCTP_FUTURE_ASSOC`.

**Comment by jmillan** [comment]
Hi,

using `usrsctp_getsockopt()` with `SCTP_RECONFIG_SUPPORTED` results on the function returning **-1** many times.

We could just do as in `/programs/` in order to know which features are supported in the association.

https://github.com/sctplab/usrsctp/blob/70b3cd7b759323a86f8341e1baa21fb7a7bc07e7/programs/programs_helper.c#L85

**Comment by lgrahl** [comment]
Coming back to this:

> > Untested but I think you forgot to initialise the length to a valid value. See also [RFC 6525, sec 6.3.2](https://tools.ietf.org/html/rfc6525#section-6.3.2).
> 
> This is about `usrsctp_getsockopt()` :)

I hope you set the length now. Otherwise, it can arbitrarily fail.

**Comment by ibc** [comment]
> > Thanks @tuexen. So I'll use `usrsctp_getsockopt()` with `SCTP_RECONFIG_SUPPORTED`.
> > BTW do you also mean that `SCTP_RECONFIG_SUPPORTED` should be used in `usrsctp_setsockopt()`?
> 
> Yes, you can. But on a one-to-one style socket (`SOCK_STREAM`) you can only use it on the listening socket or on an unconnected socket. In this case, `av.assoc_id` is ignored. When using on a one-to-many style socket (`SOCK_SEQPACKET`), you can use it for all future associations by setting `av.assoc_id` to `SCTP_FUTURE_ASSOC`.

Thanks @tuexen. We are using one-to-one style socket `SOCK_STREAM` (we use SCTP over DTLS and also SCTP directly over UDP).

May I know the difference between calling `usrsctp_setsockopt(..., SCTP_ENABLE_STREAM_RESET)` and `usrsctp_setsockopt(..., SCTP_RECONFIG_SUPPORTED)`?

[RFC 6525](https://tools.ietf.org/html/rfc6525#section-6.3.1) just defines `SCTP_ENABLE_STREAM_RESET`, `SCTP_RESET_STREAMS`, `SCTP_RESET_ASSOC`  and `SCTP_ADD_STREAMS`. I do not see any `SCTP_RECONFIG_SUPPORTED`.

**Comment by ibc** [comment]
> > This is about `usrsctp_getsockopt()` :)
> 
> I hope you set the length now. Otherwise, it can arbitrarily fail.

The length of what? `usrsctp_getsockopt()` receives a pointer to `socklen_t` so its value is supposed to be set by the lib.

```c
struct sctp_assoc_value av;
socklen_t paramLen;

av.assoc_id    = SCTP_ALL_ASSOC; // Ignored.
av.assoc_value = 1; // No idea if it must be 1 or what.

int ret = usrsctp_getsockopt(socket, IPPROTO_SCTP, SCTP_RECONFIG_SUPPORTED, &av, &paramLen);
```

Note `&paramLen` here.

**Comment by lgrahl** [comment]
No... have you never worked with `getsockopt` before? http://man7.org/linux/man-pages/man2/setsockopt.2.html

**Comment by jmillan** [comment]
This is it

```c++
  sctp_assoc_value av;
  memset(&av, 0, sizeof(av));
  socklen_t len = (socklen_t)sizeof(av);
  
  int ret = usrsctp_getsockopt(this->socket, IPPROTO_SCTP, SCTP_ENABLE_STREAM_RESET, &av, &len);

  MS_ERROR("SCTP_ENABLE_STREAM_RESET: %d, ret: %d", av.assoc_value, ret);
```

**Comment by ibc** [comment]
> optlen is a value-result argument, initially containing the size of the buffer pointed to by optval, and modified on return to indicate the actual size of the value returned.  If no option value is to be supplied or returned, optval may be NULL.

I may pass NULL then, right? I don't want to read any value but just get a proper `ret` 0 or -1 (whether the feature is supported or not).

**Comment by lgrahl** [comment]
@jmillan Have you tried using `SCTP_RECONFIG_SUPPORTED`?

@ibc Nah. Maybe code is easier to understand (hoping this is the correct place but you can easily verify that with adding a breakpoint): https://github.com/sctplab/usrsctp/blob/579db623fb3cf0b3c80fdc8075d92b03902161dc/usrsctplib/netinet/sctp_usrreq.c#L4237:L4263

**Comment by ibc** [comment]
Yes, we have tested `SCTP_RECONFIG_SUPPORTED`:

```c
sctp_assoc_value av;
auto len = static_cast<socklen_t>(sizeof(av));

memset(&av, 0, sizeof(av));

int ret = usrsctp_getsockopt(socket, IPPROTO_SCTP, SCTP_RECONFIG_SUPPORTED, &av, &len);
```

It **always** returns 0, even for SCTP clients not supporting RE_CONFIG.

**Comment by lgrahl** [comment]
Just hacked this into RAWRTC and it works fine:

```c
struct sctp_assoc_value option_value = {0};
socklen_t option_size = sizeof(option_value);  // PD point is int according to spec
if (usrsctp_getsockopt(
        transport->socket, IPPROTO_SCTP, SCTP_RECONFIG_SUPPORTED, &option_value, &option_size)) {
    DEBUG_WARNING("Could not retrieve whether stream reconfiguration has been negotiated, reason: %m\n", errno);
}
DEBUG_WARNING("SCTP_RECONFIG_SUPPORTED: %"PRIu32"\n", option_value.assoc_value);
```

`option_value.assoc_value` is `1` if supported, `0` if not.

**Comment by ibc** [comment]
ooohhh, my fault. So it's not the returned value of `usrsctp_getsockopt()` what must be checked, but `option_value.assoc_value`!!!

Let me check!

**Comment by ibc** [comment]
Thanks @lgrahl, stupid wrong usage here, it works perfectly as you said :)

**Comment by ibc** [comment]
Thanks @tuexen and @lgrahl, this is working. Let's close the issue.

**Comment by tuexen** [comment]
> Yes, we have tested `SCTP_RECONFIG_SUPPORTED`:
> 
> ```c
> sctp_assoc_value av;
> auto len = static_cast<socklen_t>(sizeof(av));
> 
> memset(&av, 0, sizeof(av));
> 
> int ret = usrsctp_getsockopt(socket, IPPROTO_SCTP, SCTP_RECONFIG_SUPPORTED, &av, &len);
> ```
> 
> It **always** returns 0, even for SCTP clients not supporting RE_CONFIG.

The return value only tells you if the get operation was successful or not. It is not an indication of the value. See the example from @lgrahl how to use it (thanks a lot for providing it!).

**Comment by ibc** [comment]
Yes, sure, it's clear and working now. Thanks!

**Comment by jmillan** [comment]
Thanks @tuexen, @lgrahl!
