### ISSUE TITLE
Apply checksum by default on loopback

### ISSUE THREAD

**Issue by lgrahl** [sctplab/usrsctp#327]
Something that caught me off guard while developing my micro SCTP stack is that the CRC32C checksum is not being applied by default. Simple question with a simple fix: Shouldn't `usrsctp_sysctl_set_sctp_no_csum_on_loopback` be set to `0` by default?

**Comment by tuexen** [comment]
In the kernel stack this means you are talking to yourself without a network being involved, so it is a performance optimisation. So are you having problems with this setting?

**Comment by lgrahl** [comment]
The issue was that my stack discarded all packets coming from usrsctp since both were running on raw sockets on the same machine.

Makes sense to not do it in the kernel, so perhaps we could just apply the checksum by default in userland?

**Comment by tuexen** [comment]
So running two stacks on the same machine with "out of the blue handling" disabled?

**Comment by lgrahl** [comment]
Not sure I can follow. Does OOTB play a role in that scenario? Basically, I received a packet with the expected destination port containing an `INIT` (or `INIT ACK`, I'm using simultaneous open) with a zero checksum which my stack rejected because the checksum doesn't match.

**Comment by tuexen** [comment]
The point you might be missing is the following: Assume you ran two SCTP stack (S1 and S2) on the same host. Now S1 sends an INIT to the loopback address. It is received by both stacks. So S2 will respond with an INIT-ACK, S1 will respond with an ABORT. And this will terminate the connection.

So for this scenario, a stack must not send an INIT to packets it does not expect. This is what I meant by "disable OOTB handling".

**Comment by lgrahl** [comment]
Ah, yes, that makes sense. Okay, so in this case there is no kernel stack and both SCTP stacks operate in client mode, therefore only listen on their assigned ports. So, OOTB handling should not affect this scenario.
That being said, in reality OOTB handling will usually be enabled and thus it doesn't really make sense to operate two SCTP stacks on the same machine. Hence, this optimisation only affects people doing weird stuff like me. With that, I'll leave it up to you if you want to close this. :wink:

**Comment by tuexen** [comment]
> Ah, yes, that makes sense. Okay, so in this case there is no kernel stack and both SCTP stacks operate in client mode, therefore only listen on their assigned ports and ignore everything else. So, 

If you follow that spec, you MUST do OOTB handling. It doesn't matter if you are client or server.

> OOTB handling should not affect this scenario as there is no entity that is listening on all ports.
> 
> That being said, in reality OOTB handling might be enabled and thus it doesn't really make sense to operate two SCTP stacks on the same machine. Hence, this optimisation only affects people doing weird stuff like me. With that, I'll leave it up to you if you want to close this. 😉

OK. Will think about it a day or two.

**Comment by tuexen** [comment]
OK, I think this is similar to disabling the OOTB handling via `usrsctp_sysctl_set_sctp_blackhole(2)`. So I added a corresponding `usrsctp_sysctl_set_sctp_no_csum_on_loopback(0)` to the programs. Both settings are affect the usecase of running multiple instances of an SCTP stack on a single host.
