### ISSUE TITLE
No releases (git tags)?

### ISSUE THREAD

**Issue by ibc** [sctplab/usrsctp#33]
I wonder why this project has no tags/releases. How to get a stable version?

**Comment by tuexen** [comment]
Just use the latest sources from the git repo. We don't do releases since that would required additional resources...

**Comment by ibc** [comment]
Additional resources? :)

This is what I do for my Git projects:

$HOME/bin/gitTag.sh:
```bash
#!/usr/bin/env bash

set -e

git tag -a $1 -m "$1"
git push
git push --tags
```

Usage:

```bash
~/src/projectFoo $ gitTag 1.0.2
```

:)

**Comment by tuexen** [comment]
But that doesn't give you much compared to using the version of some day or so.
I was thinking about using some release procedure which includes some more testing,
beta versions and so on.
