### ISSUE TITLE
Controlling list of source addresses in INIT chunk

### ISSUE THREAD

**Issue by rgbmrx** [sctplab/usrsctp#331]
Have Client/Server link between two machines using SCTP in multi-homing mode.
Client on QNX has 6 NICs but only want 2 of those source interface IPs ending up in the INIT.
Is binding the way to ensure this even though you only ever see this on the server side.
thanks

**Comment by tuexen** [comment]
You might want to try `sctp_bindx()`. But the routing must be configured appropriately, since the userland stack does not maintain an up to date copy of the routing table.

**Comment by rgbmrx** [comment]
Thanks for that.
