### ISSUE TITLE
Make *addr be NULL in global send callback

### ISSUE THREAD

**Issue by ibc** [sctplab/usrsctp#333]
Even if undocumented, the second argument of `usrsctp_init()` (used for SCTP over UDP/DTLS) looks as follows:

```c++
int on_send_sctp_data(void* addr, void* data, size_t len, uint8_t tos, uint8_t set_df)
```

The `addr` pointer gives a chance for the app to identify with "SCTP association" this data refers to. However, there are cases in which I'am deleting/freeing such a "SCTP association" and called `usrsctp_close(socket)` on it, and such a call to `usrsctp_close(socket)` will produce a SCTP close packet to be sent, so the `on_send_sctp_data` callback above is called to send it.

Within the `on_send_sctp_data` global callback, I'd like that `addr` becomes NULL in those cases so I just ignore such a SCTP packet. This is what I've tried with no luck so far:

```c++
SctpAssociation::~SctpAssociation()
{
	// Deregister ourselves from usrsctp.
	usrsctp_deregister_address(static_cast<void*>(this));

	if (this->socket)
	{
		usrsctp_set_ulpinfo(this->socket, nullptr);
		usrsctp_close(this->socket);
	}

	// [...]
}
```

I expected that `usrsctp_deregister_address()` would make `addr` in `on_send_sctp_data` be NULL, but it's not.

So, I'm fine as far as `on_send_sctp_data` is called **synchronously** after called `usrsctp_close(socket)` (because even if my `~SctpAssociation` destructor has being called, it's not destroyed yet).

Is it 100% guaranteed? I mean, will `usrsctp_close()` always trigger `on_send_sctp_data` in that exact moment? (and not later after any other pending operation or time delay)?

**Comment by tuexen** [comment]
`usrsctp_deregister_address()` doesn't change any pointer stored somewhere. Look at it like an IP-Address. You just say that the application does not refer it it anymore and therefore the implementation might free it, if there are no other references to it.

`usrsctp_close()` will trigger a graceful or non-graceful shutdown based on the setting of the SO_LINGER socket option (this is just the normal socket API). If non-graceful shutdown is selected, an ABORT will be sent. If a graceful shutdown is selected, all outstanding user data must be acknowledged by the peer, but the SHUTDOWN chunk will be sent, which is the first message of the three-way message exchange to terminate the SCTP association.

**Comment by ibc** [comment]
Thanks @tuexen. I understand what you say. Just to re-confirm:

Regardless I configure SO_LINGER to do graceful or non-graceful shutdown, I understand that there is **no way** to avoid that `usrsctp_close()` invokes the global send callback or, at least, that it invokes the global send callback with `addr = NULL`, is that correct?

Thanks a lot.

**Comment by tuexen** [comment]
You are right, calling `usrsctp_close()` will trigger the sending of at least one packet.

**Comment by ibc** [comment]
Thanks.
