### ISSUE TITLE
There is no "./configure"

### ISSUE THREAD

**Issue by ibc** [sctplab/usrsctp#34]
The manual says:

> Unix-like Operating Systems
>
In the folder usrsctp type
    $ ./configure
    $ make

But there is no "configure" script in the source (but "configure.am). The doc should tell how to get it.

**Comment by weinrank** [comment]
Run `./bootstrap` before `./configure` and `make`

**Comment by ibc** [comment]
Yes, I figured it out. I just meant that the doc is currently incorrect :)

**Comment by weinrank** [comment]
I'm creating a pull request right now! :smile:

**Comment by weinrank** [comment]
Solved by pull request #35 

@tuexen Close?

**Comment by tuexen** [comment]
Yes. Thanks.
