### ISSUE TITLE
timingsafe_bcmp only defined for macOS 10.12.1 or newer

### ISSUE THREAD

**Issue by benjwright** [sctplab/usrsctp#346]
Compilation on macOs failure with: usrsctp/usrsctplib/usrsctplib/netinet/sctp_auth.c:1733:6: error: 'timingsafe_bcmp' is only available on macOS 10.12.1 or newer [-Werror,-Wunguarded-availability]

**Comment by tuexen** [comment]
Which versions of Mac OS do you support?

**Comment by benjwright** [comment]
Hi tuxen, Chrome currently supports OS X Yosemite 10.10 or later. https://support.google.com/chrome/a/answer/7100626?hl=en

**Comment by tuexen** [comment]
@benjwright What do you think about using https://github.com/sctplab/usrsctp/commit/0509d636a162f6fc06265224ecc2b677a5b31410.

When using the sources in the FreeBSD kernel, the available `timingsafe_bcmp` is used. One could add a macro to provide platform specific versions of it, but in the end we will provide a private version for Mac OS X unless you only build for 10.12.1 or newer, which is not the case. So this seems to be the simplest approach. If you are fine with it, I'll merge  the branch into the master branch.

**Comment by benjwright** [comment]
Yep that works as well. Thanks for your help!

**Comment by tuexen** [comment]
Thanks for the feedback. Merged.

**Comment by taylor-b** [comment]
This doesn't prevent the warning for me... Even though the private version is defined, the compiler doesn't seem to know that at the point where it generates the warning.

Not sure how to fix this other than to use a function named something different like `os_timingsafe_bcmp`, which would call the platform function if available and usrsctp version if not.

**Comment by dirkz** [comment]
Last time I checked, the warning was still there when building for 10.10, even though the correct function gets called during runtime. So false alarm.

Do you want a pull request (probably just renaming the usrsctp version), or just ignore this?

**Comment by tuexen** [comment]
If acceptable, I would prefer to keep it as is. Apple only supports 10.15 and later...

**Comment by dirkz** [comment]
Yes, totally acceptable, in that case we will just ignore this warning.
