### ISSUE TITLE
single-thread API: add usrsctp_get_timeout()

### ISSUE THREAD

**Issue by ibc** [sctplab/usrsctp#349]
PR #339 makes usrsctp work in single thread environments by forcing the application call `usrsctp_handle_timers()` periodically. While it's good enough (it does work), the optimized way of doing it would be by having an API like [DTLSv1_get_timeout()](https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#DTLSv1_get_timeout) and [DTLSv1_handle_timeout](https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#DTLSv1_handle_timeout) in OpenSSL and BoringSSL.

usrsctp already has `usrsctp_handle_timers()` so the only missing API would be `usrsctp_get_timeout()`.

This is, the application provides an input to the lib (via `usrsctp_socket()`, `usrsctp_close()`, `usrsctp_connect()`, `usrsctp_conninput()`, etc) and retrieves from the lib (via `usrsctp_get_timeout()`) the time that must elapse **before** the lib (usrsctp) would need to do something (like sending a retransmission, a chunk or whatever). And then the app would set its own timer with that expiration value and call `usrsctp_handle_timers()` when it expires. This would be much more efficient that the current approach in which the app must call `usrsctp_handle_timers()` every N ms just in case the lib has something to do at that time.

As @tuexen said:

> `usrsctp_get_timeout()` should give the app the number of milliseconds until the next timer runs off. It should walk the (unordered) list of timers to compute that value. It would even be more efficient if the timer list would be ordered, but then starting a timer would be more complicated.

**IMPORTANT:** It should be very clear and well documented when the app should call `usrsctp_get_timeout()`, this is: the app should call `usrsctp_get_timeout()` and prepare a new timer after calling which usrsctp functions and after which usrsctp events.

**Comment by milahu** [comment]
why was this closed?

fixed by https://github.com/sctplab/usrsctp/pull/591

**Comment by ibc** [comment]
What do you mean? This issue was closed because it was done here: https://github.com/sctplab/usrsctp/issues/349

**Comment by milahu** [comment]
#339 adds

```c
static unsigned get_tick_count(void)
{
#ifdef _WIN32
	return GetTickCount();
#else
	struct timeval te;
	gettimeofday(&te, NULL); // get current time
	unsigned milliseconds = te.tv_sec*1000LL + te.tv_usec/1000; // calculate milliseconds
	return milliseconds;
#endif
}
```

but that looks very different from #591

```c
int
usrsctp_get_timeout(void)
{
	return sctp_get_next_tick();
}

int
sctp_get_next_tick(void)
{
	int ret;
	sctp_os_timer_t *c;

	SCTP_TIMERQ_LOCK();
	c = TAILQ_FIRST(&SCTP_BASE_INFO(callqueue));
	if (c) {
		uint32_t min_delta = UINT32_MAX;
		while (c) {
			uint32_t delta = c->c_time - ticks;
			min_delta = (delta < min_delta) ? delta : min_delta;
			c = TAILQ_NEXT(c, tqe);
		}
		ret = min_delta;
	} else {
		ret = -1;
	}
	SCTP_TIMERQ_UNLOCK();

	return ret;
}
```

`usrsctp_get_timeout` is used in [frida-core](https://github.com/frida/frida-core/blob/ab2581a0b7faea22d87a33c1cc6f2aab8bd88ece/lib/base/p2p-glue.c#L347)

**Comment by ibc** [comment]
@milahu do you mean that PR #591 (not merged and unfortunately obviously ignored) is not a replacement but an addition and improvement to make single thread behavior way better than before?
