### ISSUE TITLE
Integrate UsrSCTP into OSS-Fuzz

### ISSUE THREAD

**Issue by benjwright** [sctplab/usrsctp#353]
Given the recent fuzzing discoveries in UsrSCTP it seems like it would be useful to on board the project to OSS-Fuzz: https://github.com/google/oss-fuzz

#351, #352 and #255 could all benefit from having automated continuous fuzzing.

**Comment by weinrank** [comment]
Yep, I'm currently working on this. :)

**Comment by benjwright** [comment]
Awesome, just filling an issue here to track it since it was suggested in another bug.

**Comment by tuexen** [comment]
https://github.com/sctplab/usrsctp/commit/04d617c9c194666747d0294526a388db053edaa7 is the initial step within this project.

**Comment by weinrank** [comment]
The usrsctp library is getting fuzzed by the OSS-FUZZ project.
We haven't seen any bug reports.

I'll extend the collection of fuzzers and corpora in the future.
Another issue is the slow execution of the fuzzing targets in connected mode.
While the unconnected fuzzer reaches about 5,500 executions per second, the connected fuzzer only reaches about 50 executions per second.

**Comment by tuexen** [comment]
@weinrank Thanks a lot for your work! Can this issue be closed now that it is integrated in OSS-FUZZ?

**Comment by weinrank** [comment]
Yes, it can be closed.
We can probably recycle this issue for future discussions / status updates regarding the OSS-FUZZ project.
