### ISSUE TITLE
MemorySanitizer: use of uninitialized value in sctp_med_chunk_output

### ISSUE THREAD

**Issue by markwo** [sctplab/usrsctp#357]
MSAN detected this during fuzzing. Attaching a PCAP and the testcase data.

It seems to be at this location in sctp_med_chunk_output where chk->flags is being accessed:
```
				/* Do clear IP_DF ? */
				if (chk->flags & CHUNK_FLAGS_FRAGMENT_OK) {
					no_fragmentflg = 0;
				}
```

Packet data text:
```
I 12:53:47.307166 0000 13 88 13 88 00 00 00 00 d4 1b 26 17 01 00 00 56 47 25 d5 4e 00 02 00 00 00 04 00 04 68 a0 26 bf c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 95 80 6d 33 d9 ec b4 35 d0 aa c8 18 e1 4c e2 4a 25 7f 19 51 b8 91 92 12 db 99 30 2a 7e 9e cd 17 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 # SCTP_PACKET

O 12:53:47.307647 0000 13 88 13 88 00 00 00 00 00 00 00 00 01 00 00 14 01 00 00 00 00 00 20 00 00 08 00 08 00 00 00 01 # SCTP_PACKET

I 12:53:47.307762 0000 13 88 13 88 01 00 00 00 00 00 00 00 02 00 01 4c 47 25 d5 4e 00 02 00 00 00 04 00 04 68 a0 26 bf c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 53 f0 50 23 5c 7c 66 2f 49 09 2a 6f e0 d3 69 6d 5e 63 14 30 c5 5c ac 2b 49 2d c4 19 c5 91 2c 3f 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 00 07 00 f4 4b 41 4d 45 2d 42 53 44 20 31 2e 31 00 00 00 00 4b 8a 65 5d 00 00 00 00 fa b1 04 00 00 00 00 00 60 ea 00 00 05 93 a9 df b1 d3 f4 58 00 00 00 01 47 25 d5 4e 00 24 00 00 80 70 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 24 00 00 80 70 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 13 88 13 88 00 00 01 00 01 01 01 00 00 00 00 00 01 00 00 14 01 00 00 00 00 00 20 00 00 08 00 08 00 00 00 01 02 00 01 4c 47 25 d5 4e 00 02 00 00 00 04 00 04 68 a0 26 bf c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 53 f0 50 23 5c 7c 66 2f 49 09 2a 6f e0 d3 69 6d 5e 63 14 30 c5 5c ac 2b 49 2d c4 19 c5 91 2c 3f 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 a7 4e 8e 8e e5 8a 0f 83 9b 11 d2 dc 97 98 6f e7 a1 1b 9e 70 # SCTP_PACKET

O 12:53:47.308117 0000 13 88 13 88 47 25 d5 4e 00 00 00 00 c0 00 00 08 00 00 00 07 f9 00 00 04 00 04 # SCTP_PACKET
```
[repro.zip](https://github.com/sctplab/usrsctp/files/3547888/repro.zip)

**Comment by tuexen** [comment]
Can you provide `chk->rec.chunk_id.id` for the `chk` which has an uninitialised `chk->flags`?

**Comment by tuexen** [comment]
> Sure, `chk->rec.chunk_id.id = 9`

That means that the chunk was allocated in [sctp_output.c#L9488](https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_output.c#L9488), the `id` set in [https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_output.c#L9495](sctp_output.c#L9495) and `chk->flags` was initialised in [sctp_output.c#L9497](https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_output.c#L9497). Not sure why it is reported as uninitialised...

**Comment by tuexen** [comment]
Yes, I guess it was fixed in https://github.com/sctplab/usrsctp/commit/47dd39f84c7e70c29fa9be6004482c3f3146619d.

**Comment by weinrank** [comment]
@markwo I'm curious: why are you fuzzing against old sources of usrsctp?
Since we're already fuzzing for about a year, you'll probably run into more issues which are already fixed.
