### ISSUE TITLE
Retrieve an association index

### ISSUE THREAD

**Issue by nxrighthere** [sctplab/usrsctp#361]
While re-reading documentation, I can't find how to retrieve an association index at both ends in one to one setup. Is it possible?

**Comment by tuexen** [comment]
I guess you are referring to the association identifier. This is only used to identify a particular association on a one-to-many style socket. This field is ignored on a one-to-one style socket, since there is no need to identify a particular association. There is only one...

**Comment by nxrighthere** [comment]
Yes, but I found this identifier while inspecting packets on the wire and it's an identical thing to my abstraction of connection IDs in the layer on top, so I thought that I could just replace it with one that can be retrieved from SCTP instead of tracking/assigning IDs in custom logic.

Anyway, thanks for clarifying this.
