### ISSUE TITLE
usrsctp_sysctl_set_sctp_auth_disable() function not defined.

### ISSUE THREAD

**Issue by weinrank** [sctplab/usrsctp#362]
```
Scanning dependencies of target fuzzer_connect_data_sent
[ 69%] Building C object fuzzer/CMakeFiles/fuzzer_connect_data_sent.dir/fuzzer_connect.c.o
/Users/weinrank/Documents/GitHub/usrsctp/fuzzer/fuzzer_connect.c:245:2: error: implicit declaration of function 'usrsctp_sysctl_set_sctp_auth_disable' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        usrsctp_sysctl_set_sctp_auth_disable();
        ^
/Users/weinrank/Documents/GitHub/usrsctp/fuzzer/fuzzer_connect.c:245:2: note: did you mean 'usrsctp_sysctl_set_sctp_auth_enable'?
/Users/weinrank/Documents/GitHub/usrsctp/usrsctplib/usrsctp.h:1081:1: note: 'usrsctp_sysctl_set_sctp_auth_enable' declared here
USRSCTP_SYSCTL_DECL(sctp_auth_enable)
^
/Users/weinrank/Documents/GitHub/usrsctp/usrsctplib/usrsctp.h:1072:5: note: expanded from macro 'USRSCTP_SYSCTL_DECL'
int usrsctp_sysctl_set_ ## __field(uint32_t value);\
    ^
<scratch space>:26:1: note: expanded from here
usrsctp_sysctl_set_sctp_auth_enable
^
/Users/weinrank/Documents/GitHub/usrsctp/fuzzer/fuzzer_connect.c:245:2: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
        usrsctp_sysctl_set_sctp_auth_disable();
        ^
```

**Comment by tuexen** [comment]
Why do you think there should exist a function with name `usrsctp_sysctl_set_sctp_auth_disable`? On FreeBSD there is a `sysctl`-variable with the name `net.inet.sctp.auth_enable` which can take `0` or `1` as values to disable or enable the AUTH extension per default on new end points.
To disable the extension, you would use
```
sysctl net.inet.sctp.auth_enable=0
```
The way to do the equivalent in the userland stack would be to call
```
usrsctp_sysctl_set_sctp_auth_enable(0);
```
In the userland stack you have for each (supported) `sysctl`-variable a function with the same name as the `sysctl`-variable, but preprended with the prefix `usrsctp_sysctl_set_`. The argument of this function is the value you set the `sysctl`-variable to.

**Comment by weinrank** [comment]
Because of the [Readme](https://github.com/sctplab/usrsctp/blob/master/Manual.md#usrsctp_sysctl_set_sctp_auth_disable). :)

Thanks for the clarification.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/7cd64a3c92745001fd7f3a47d82e0d70606565f5. Can this issue be closed?
