### ISSUE TITLE
oss-fuzz integration

### ISSUE THREAD

**Issue by bshastry** [sctplab/usrsctp#387]
Hello,

I noticed that usrsctp is marked as a security critical dependency in chromium and that you already actively fuzz the library. Would you be interested in upstream oss-fuzz integration?

Thank you.

**Comment by weinrank** [comment]
Hi @bshastry,

usrsctp is already part of the oss-fuzz project.
See https://github.com/google/oss-fuzz/tree/master/projects/usrsctp
