### ISSUE TITLE
Logic error in usrsctp

### ISSUE THREAD

**Issue by randomascii** [sctplab/usrsctp#41]
The VC++ /analyze builder for Chromium is reporting a logic error in usrsctp. Specifically it points out that the last line of this code fragment from third_party\usrsctp\usrsctplib\usrsctplib\user_socket.c is buggy:

struct socket *
usrsctp_socket(int domain, int type, int protocol,
	       int (*receive_cb)(struct socket *sock, union sctp_sockstore addr, void *data,
                                 size_t datalen, struct sctp_rcvinfo, int flags, void *ulp_info),
	       int (*send_cb)(struct socket *sock, uint32_t sb_free),
	       uint32_t sb_threshold,
	       void *ulp_info)
{
	struct socket *so;

	if ((protocol = IPPROTO_SCTP) && (SCTP_BASE_VAR(sctp_pcb_initialized) == 0)) {

The line unconditionally assigns to protocol, instead of comparing against it. This was reported in November of 2014 to Michael Tüxen <t00fcxen@googlemail.com> and was fixed upstream but that fix seems to have gone away? The original fix was in https://code.google.com/p/sctp-refimpl/source/detail?r=9063 but there is no apparent sign of it in the history.

The bug is apparently not causing any current problems in Chromium but it is incorrect and could be causing problems elsewhere.

The warning is:
third_party\usrsctp\usrsctplib\usrsctplib\user_socket.c(1365) : warning C6282: Incorrect operator:  assignment of constant in Boolean context. Consider using '==' instead.

**Comment by randomascii** [comment]
Correction: this bug was *not* reported last year. That was a different logic bug in the same source file.

This bug was introduced in July 2014 in commit 4fde7c3.

I don't know what the consequences of this bug or of fixing it are.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/8e59da4daf6b8627a7d04a40092e0f9bb036283f.
Thanks for reporting it. The function is expected to be called with protocol == IPPROTO_SCTP, so the only consequence of the bug is when usrsctp_socket() is called with protocol != IPPROTO_SCTP, the error was not detected and the socket was considered an SCTP socket.
