### ISSUE TITLE
sctp deadlock

### ISSUE THREAD

**Issue by sancane** [sctplab/usrsctp#414]
Hi,
I come across a situation where the whole stack gets locked when trying to get the lock of an sctp_tcb structure. Having a look at the trace it looks like there is a sctp_tcb structure whose mutex is locked and never unlocked so any attemp to get the mutex later on ends up locking the thread causing a deadlock in the stack.
I've been trying to follow all usages of above structure in the code trying to debug this issue but I'm afraid that I'm not too familirized with the code. I attached the stack trace i could recover from my server. I've deployed a version of the library from commit https://github.com/sctplab/usrsctp/commit/913de3599feded8322882bdae69f346da5a258fc
Here is the stack trace of all threads locked in sctp:

Thread 38 (Thread 0x7fd4f37ee700 (LWP 4624)):
#0  0x00007fd51c6354fd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd51c630ddb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd51c630ca8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fd50d46c09b in sctp_findassoc_by_vtag (from=0x7fd4f37ed480, to=0x7fd4f37ed470, vtag=2992747646, inp_p=0x7fd4f37ed308, netp=0x7fd4f37ed300, rport=34835, lport=34835, skip_src_check=0, vrf_id=0, remote_tag=0) at netinet/sctp_pcb.c:2528
#4  0x00007fd50d46c319 in sctp_findassociation_addr (m=0x7fd494197e30, offset=12, src=0x7fd4f37ed480, dst=0x7fd4f37ed470, sh=0x7fd494197e80, ch=0x7fd494197e8c, inp_p=0x7fd4f37ed308, netp=0x7fd4f37ed300, vrf_id=0) at netinet/sctp_pcb.c:2609
#5  0x00007fd50d445bea in sctp_common_input_processing (mm=0x7fd4f37ed468, iphlen=0, offset=12, length=32, src=0x7fd4f37ed480, dst=0x7fd4f37ed470, sh=0x7fd494197e80, ch=0x7fd494197e8c, compute_crc=1 '\001', ecn_bits=0 '\000', vrf_id=0, port=0) at netinet/sctp_input.c:5791
#6  0x00007fd50d41417a in usrsctp_conninput (addr=0x7fd4b4117e30, buffer=0x7fd49c046420, length=32, ecn_bits=0 '\000') at user_socket.c:3525
#7  0x00007fd4f0124539 in sctp_association_incoming_packet (self=self@entry=0x7fd4b4117e30, buf=<optimized out>, length=<optimized out>) at sctpassociation.c:481

Thread 32 (Thread 0x7fd4897fa700 (LWP 4639)):
#0  0x00007fd51c6354fd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd51c630ddb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd51c630ca8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fd50d46bfdd in sctp_findassoc_by_vtag (from=0x7fd4897f9480, to=0x7fd4897f9470, vtag=4094046840, inp_p=0x7fd4897f9308, netp=0x7fd4897f9300, rport=34835, lport=34835, skip_src_check=0, vrf_id=0, remote_tag=0) at netinet/sctp_pcb.c:2503
#4  0x00007fd50d46c319 in sctp_findassociation_addr (m=0x7fd484037000, offset=12, src=0x7fd4897f9480, dst=0x7fd4897f9470, sh=0x7fd484037050, ch=0x7fd48403705c, inp_p=0x7fd4897f9308, netp=0x7fd4897f9300, vrf_id=0) at netinet/sctp_pcb.c:2609
#5  0x00007fd50d445bea in sctp_common_input_processing (mm=0x7fd4897f9468, iphlen=0, offset=12, length=32, src=0x7fd4897f9480, dst=0x7fd4897f9470, sh=0x7fd484037050, ch=0x7fd48403705c, compute_crc=1 '\001', ecn_bits=0 '\000', vrf_id=0, port=0) at netinet/sctp_input.c:5791
#6  0x00007fd50d41417a in usrsctp_conninput (addr=0x7fd4c013a740, buffer=0x7fd484031c40, length=32, ecn_bits=0 '\000') at user_socket.c:3525
#7  0x00007fd4f0124539 in sctp_association_incoming_packet (self=self@entry=0x7fd4c013a740, buf=<optimized out>, length=<optimized out>) at sctpassociation.c:481

Thread 29 (Thread 0x7fd478ff9700 (LWP 5036)):
#0  0x00007fd51c6354fd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd51c630ddb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd51c630ca8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fd50d46bfdd in sctp_findassoc_by_vtag (from=0x7fd478ff8480, to=0x7fd478ff8470, vtag=520042073, inp_p=0x7fd478ff8308, netp=0x7fd478ff8300, rport=34835, lport=34835, skip_src_check=0, vrf_id=0, remote_tag=0) at netinet/sctp_pcb.c:2503
#4  0x00007fd50d46c319 in sctp_findassociation_addr (m=0x7fd4d0041e40, offset=12, src=0x7fd478ff8480, dst=0x7fd478ff8470, sh=0x7fd4d0041e90, ch=0x7fd4d0041e9c, inp_p=0x7fd478ff8308, netp=0x7fd478ff8300, vrf_id=0) at netinet/sctp_pcb.c:2609
#5  0x00007fd50d445bea in sctp_common_input_processing (mm=0x7fd478ff8468, iphlen=0, offset=12, length=28, src=0x7fd478ff8480, dst=0x7fd478ff8470, sh=0x7fd4d0041e90, ch=0x7fd4d0041e9c, compute_crc=1 '\001', ecn_bits=0 '\000', vrf_id=0, port=0) at netinet/sctp_input.c:5791
#6  0x00007fd50d41417a in usrsctp_conninput (addr=0x7fd4b4154180, buffer=0x7fd480454630, length=28, ecn_bits=0 '\000') at user_socket.c:3525
#7  0x00007fd4f0124539 in sctp_association_incoming_packet (self=self@entry=0x7fd4b4154180, buf=<optimized out>, length=<optimized out>) at sctpassociation.c:481

Thread 24 (Thread 0x7fd471ffb700 (LWP 5242)):
#0  0x00007fd51c6354fd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd51c630ddb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd51c630ca8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fd50d46bfdd in sctp_findassoc_by_vtag (from=0x7fd471ffa480, to=0x7fd471ffa470, vtag=2827999444, inp_p=0x7fd471ffa308, netp=0x7fd471ffa300, rport=34835, lport=34835, skip_src_check=0, vrf_id=0, remote_tag=0) at netinet/sctp_pcb.c:2503
#4  0x00007fd50d46c319 in sctp_findassociation_addr (m=0x7fd4dc106000, offset=12, src=0x7fd471ffa480, dst=0x7fd471ffa470, sh=0x7fd4dc106050, ch=0x7fd4dc10605c, inp_p=0x7fd471ffa308, netp=0x7fd471ffa300, vrf_id=0) at netinet/sctp_pcb.c:2609
#5  0x00007fd50d445bea in sctp_common_input_processing (mm=0x7fd471ffa468, iphlen=0, offset=12, length=32, src=0x7fd471ffa480, dst=0x7fd471ffa470, sh=0x7fd4dc106050, ch=0x7fd4dc10605c, compute_crc=1 '\001', ecn_bits=0 '\000', vrf_id=0, port=0) at netinet/sctp_input.c:5791
#6  0x00007fd50d41417a in usrsctp_conninput (addr=0x7fd4b4117ab0, buffer=0x7fd49415baf0, length=32, ecn_bits=0 '\000') at user_socket.c:3525
#7  0x00007fd4f0124539 in sctp_association_incoming_packet (self=self@entry=0x7fd4b4117ab0, buf=<optimized out>, length=<optimized out>) at sctpassociation.c:481

Thread 15 (Thread 0x7fd46afed700 (LWP 5358)):
#0  0x00007fd51c632975 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fd50d420da9 in sctp_iterator_thread (v=0x0) at netinet/sctp_bsd_addr.c:151
#2  0x00007fd51c62ede5 in start_thread () from /lib64/libpthread.so.0
#3  0x00007fd510aaff1d in clone () from /lib64/libc.so.6

Thread 11 (Thread 0x7fd4687e8700 (LWP 5363)):
#0  0x00007fd51c6354fd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd51c630ddb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd51c630ca8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fd50d49a33b in sctp_timeout_handler (t=0x7fd4fc133ed8) at netinet/sctputil.c:1728
#4  0x00007fd50d421646 in sctp_handle_tick (elapsed_ticks=10) at netinet/sctp_callout.c:242
#5  0x00007fd50d4217e0 in user_sctp_timer_iterate (arg=0x0) at netinet/sctp_callout.c:299
#6  0x00007fd51c62ede5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007fd510aaff1d in clone () from /lib64/libc.so.6

Thread 9 (Thread 0x7fd45f7d7700 (LWP 7551)):
#0  0x00007fd51c632975 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fd50d421439 in sctp_os_timer_stop (c=0x7fd4fc133ed8) at netinet/sctp_callout.c:203
#2  0x00007fd50d45bc6e in sctp_chunk_output (inp=0x7fd4b4191310, stcb=0x7fd4fc133e00, from_where=0, so_locked=1) at netinet/sctp_output.c:10612
#3  0x00007fd50d46714f in sctp_lower_sosend (so=0x7fd4b4166eb0, addr=0x7fd45f7d6960, uio=0x7fd45f7d6850, i_pak=0x0, control=0x0, flags=0, srcv=0x7fd45f7d6880) at netinet/sctp_output.c:14820
#4  0x00007fd50d410364 in usrsctp_sendv (so=0x7fd4b4166eb0, data=0x7fd480ae0480, len=50, to=0x7fd45f7d6960, addrcnt=1, info=0x7fd45f7d6970, infolen=32, infotype=4, flags=0) at user_socket.c:943
#5  0x00007fd4f0124634 in sctp_association_send_data (self=self@entry=0x7fd4b4117e30, buf=0x7fd480ae0480 "\003\001", length=50, stream_id=<optimized out>, ppid=ppid@entry=50, ordered=ordered@entry=1, pr=SCTP_ASSOCIATION_PARTIAL_RELIABILITY_NONE, reliability_param=0) at sctpassociation.c:517

Thread 3 (Thread 0x7fd46dff3700 (LWP 11315)):
#0  0x00007fd51c6354fd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd51c630ddb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd51c630ca8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fd50d46c918 in sctp_inpcb_alloc (so=0x7fd4d813d900, vrf_id=0) at netinet/sctp_pcb.c:2788
#4  0x00007fd50d4821e9 in sctpconn_attach (so=0x7fd4d813d900, proto=132, vrf_id=0) at netinet/sctp_usrreq.c:850
#5  0x00007fd50d410e0c in socreate (dom=123, aso=0x7fd46dfef648, type=1, proto=132) at user_socket.c:1320
#6  0x00007fd50d410f66 in usrsctp_socket (domain=123, type=1, protocol=132, receive_cb=0x7fd4f01230f0 <receive_cb>, send_cb=0x0, sb_threshold=0, ulp_info=0x7fd49800b8c0) at user_socket.c:1449
#7  0x00007fd4f0123f6b in create_sctp_socket (self=0x7fd49800b8c0) at sctpassociation.c:602
#8  sctp_association_start (self=self@entry=0x7fd49800b8c0) at sctpassociation.c:413
#9  0x00007fd4f0125178 in on_sctp_association_state_changed (sctp_association=0x7fd49800b8c0, pspec=<optimized out>, self=0x7fd4b4de66e0) at sctpassociation.c:768

**Comment by mstyura** [comment]
@sancane from the thread backtraces you've provided I can conclude that you've encountered the bug #325. I've proposed fix for it in PR #397, but it's not yet reviewed and merged. But the process of review is started as I understand.
It would be really helpful if you could check and confirm that version from branch related to #397 fixes issue for you. Thanks a lot in advance!

**Comment by sancane** [comment]
I'll give it a try, but it will take me time until i could set it in prod. I'll let you know once we test it
