### ISSUE TITLE
High round trip times during packet loss?

### ISSUE THREAD

**Issue by apatole** [sctplab/usrsctp#416]
Hello, I have been experimenting with USRSCTP and observed that round trip times under packet loss are on higher side as compared to similar libraries like Enet, not sure if it is an issue or expected behavior so just want to confirm. Below are details:
1. I have client server test app. Client just keeps sending packets to server, server on receiving resends packets. Client on receiving packets back, calculates RTTs.
2. Packets are of small size like 64 bytes. And using reliable/ordered mode.
3. When I simulated a network packets drop situation, I see very high RTT values for packets that were sent during that time. For example, when network was completely down for 50ms, and when average RTT on local network was less than 1msec, I see few packets RTT even bigger than 70msec during packets loss. I was expecting it to be at max 51/52 msec (50msec network down time + 1 msec averate RTT + some delay because of congestion, etc)

**Comment by tuexen** [comment]
Can you provide a .pcap file from the sender side covering the 50 ms network outage?

**Comment by apatole** [comment]
@tuexen Thanks for quick response. Attaching .pcap file.
[usrsctp_wireshark_dump_undep_packet_loss.zip](https://github.com/sctplab/usrsctp/files/4015282/usrsctp_wireshark_dump_undep_packet_loss.zip)

Test was run for 1 minute. And packet loss simulation model is - after every 5secs there is 100% packets loss for 50msec. Thanks.

**Comment by apatole** [comment]
Any updates on this? thanks.

**Comment by apatole** [comment]
Few more details:
Messages are being sent at 8ms interval. I tried to analyse above wireshark dump. I see re-transmission of packets for which SACK is not received, is started once SACKs are received for few sent data chunks after network outage. I thought it would be just after receiving first SACK after network outage.

**Comment by apatole** [comment]
Here is .pcap with latest usrsctp. Earlier one was with old usrsctp version.
[wireshark_capture_latest_usrsctp_under_network_loss.zip](https://github.com/sctplab/usrsctp/files/4038894/wireshark_capture_latest_usrsctp_under_network_loss.zip)

Retransmission starts bit late which can be observed from lines like below from .pcap:
...
                [Expert Info (Note/Sequence): Retransmitted TSN]
                [Retransmitted after: 0.069050000 seconds]
...

**Comment by apatole** [comment]
After looking more into the issue, I see that packets are re-transmitted only after receiving three SACKs  everytime, can be observed in .pcap. And this looks expected behavior as per the spec (https://tools.ietf.org/html/rfc4960#section-7.2.4):

"
...Whenever an endpoint receives a SACK that indicates that some TSNs
   are missing, it SHOULD wait for two further miss indications (via
   subsequent SACKs for a total of three missing reports) on the same
   TSNs before taking action with regard to Fast Retransmit.
...
"

**Comment by tuexen** [comment]
Sorry for taking some time... Yes, this is expected behaviour. You are sending approximately a message every 8 ms. So after 50 ms, you need to approximately 2.5 times 8 ms, which is 20 ms plus an RTT of 1 ms before the sender got three gap reports and retransmits everything. This gives a time of about 70 ms.

@weinrank is experimenting with a different loss recovery algorithm, which is RACK for SCTP, which would recover after the first SACK is received, which would be after 50 ms + 4 ms  + 1 ms. This is implemented in a simulation environment right not, not yet in the SCTP stack.

**Comment by apatole** [comment]
Ok, thanks Michael for confirmation. I will keep watching this repo for new recovery algorithm.

**Comment by tuexen** [comment]
OK, closing the issue.

**Comment by apatole** [comment]
@weinrank  @tuexen , one quick question, do we have any doc/spec describing new loss recovery algorithm, RACK for SCTP. Or it is same as RACK for TCP.

**Comment by stewrtrs** [comment]
Having implemented Rack for TCP and having
a small bit of knowledge left on SCTP, I would expect the 
Rack document should apply exactly. If
not I would ask the implementor why not?

R

> On Jan 21, 2020, at 12:23 AM, Arun Patole <notifications@github.com> wrote:
> 
> @weinrank @tuexen , one quick question, do we have any doc/spec describing new loss recovery algorithm, RACK for SCTP. Or it is same as RACK for TCP.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by tuexen** [comment]
@weinrank wrote a paper about, which is under review and therefore not publically available. We are considering putting up an Internet Draft which describes how to use RACK in combination with SCTP.

**Comment by apatole** [comment]
Thanks @stewrtrs , @tuexen.

**Comment by stewrtrs** [comment]
Let us know when the paper is out.. I would love
to read it :)

R

> On Jan 21, 2020, at 2:24 AM, Michael Tüxen <notifications@github.com> wrote:
> 
> @weinrank wrote a paper about, which is under review and therefore not publically available. We are considering putting up an Internet Draft which describes how to use RACK in combination with SCTP.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by weinrank** [comment]
@apatole are you interested in a specific part of RACK for SCTP or generally interested?

**Comment by apatole** [comment]
@weinrank Generally interested as it seems re-transmission times for packets would decrease with this.

With current 3 SACKs based recovery algorithm, it looks bit unsuitable for use cases where we want lowers RTTs.
