### ISSUE TITLE
Is there anything like http_server?

### ISSUE THREAD

**Issue by aquatoney** [sctplab/usrsctp#426]
Hi, I'm new to SCTP and I found usrsctp a very solid codebase. 

`http_client.c` is where I start from, but I didn't find anything like http_server, 
while there are discard_server/client and echo_server/client which can communicate with each other.

I considered to set up an HTTP server over kernel SCTP stack, but as far as I know, Linux kernel stack does not support the UDP encap, so it may not work with the encap-usrsctp. 

Is there any way we can fast build a simple testbed to send and receive HTTP messages over usrsctp (especially with UDP-encap)?

Many thanks.

**Comment by tuexen** [comment]
We use [thttpd](https://github.com/nplab/thttpd) running on the FreeBSD kernel implementation, which also supports UDP encapsulation.

**Comment by aquatoney** [comment]
Thanks for your quick response and I will take a look.
BTW I think this information is very helpful and can be posted in README or manual.

Thanks again!
