### ISSUE TITLE
Remove ifdefs from public headers or replace with config.h that lists correct defines

### ISSUE THREAD

**Issue by pps83** [sctplab/usrsctp#428]
I think usrsctp has multiple issues

 - any ifdef checks in headers that can be included by code that uses usrsctp shouldn't rely on users of the library to specify correct defines that were used to build usrsctp. Currently, it's easy to build the lib and then use it with with non-matching or missing defines. If there are any "public" defines, then these must be stored in some sort of config.h and that config has to be included (just don't call it config.h obviously)
 - apple's webkit includes usrsctp though webrtc dependency. I have no idea how it ended to be so, but I find it absolutely outlandish that [usrsctp requires to be build](https://github.com/WebKit/webkit/blob/master/Source/ThirdParty/libwebrtc/Configurations/usrsctp.xcconfig) with `__APPLE__` undefined (which is always defined when targeting anything apple related). Does usrsctp really require that, or apple's engineers messed it up for no reason?
 - libraries that provide cmake file are good because any user lib can simply include such cmake file and simply specify that a target depends/links to a target specified by such cmake. cmake file will automatically specify "public" defines/include paths that will need to be enabled in user code. The problem with [cmake file that comes with usrsctp](https://github.com/sctplab/usrsctp/blob/master/CMakeLists.txt) is that it will totally mess things up: it poisons all globals and any library that simply include cmake file from usrsctp will have some irrelevant include path or defines added all over the place. Instead, usrscpt should define targets that it has (like libusrcpt) and set compiler settings/include path for its own targets only, and not globally!

**Comment by tuexen** [comment]
Please note that the only include file which should be used by library users is `usrsctp.h`. The includes used there are:

- `__cplusplus`
- `_WIN32`
- `_WIN64`
- `_MSC_VER`
- `IPPROTO_SCTP`
- `SCTP_DEBUG`

`IPPROTO_SCTP` is protected by an `#ifndef`, so this leaves `SCTP_DEBUG`. If you build the library with debug support, but don't use it in the application, that is fine. Which of the above defines do you think need to be removed?

Please note that when compiling `usrsctp`, some defines have to be defined, some have to be undefined (like `__APPLE__` on MacOS). We provide examples how to build the library for various build systems. But this is local stuff to the library.

**Comment by tuexen** [comment]
The unconventional way of undefining platform specific defines has been removed. You only need to define `__Userspace__` when compiling the library. So I'm closing this issue. If you have suggestions for the cmake script, please open a new issue for that.
