### ISSUE TITLE
error: unknown type name ‘bool’

### ISSUE THREAD

**Issue by lminiero** [sctplab/usrsctp#429]
Hi,

apparently, [this commit](https://github.com/sctplab/usrsctp/commit/61f66833b255c52f6536e1603368f41d33673c1e) from a few hours ago (which I believe is part of #417?) breaks the compilation on gcc with the following error:

```
In file included from user_socket.c:37:
./netinet/sctputil.h:180:54: error: unknown type name ‘bool’
  180 | void sctp_stop_association_timers(struct sctp_tcb *, bool);
      |                                                      ^~~~
make[1]: *** [Makefile:658: libusrsctp_la-user_socket.lo] Error 1
```

This was intercepted by the Travis CI we recently added to Janus. It looks like an easy fix, since you just need to add a

```
#include <stdbool.h>
```

to `sctputils.h`.

**Comment by lminiero** [comment]
As a side note, this might require some more code in case the compiler does not support C99 (ref. https://stackoverflow.com/a/8161641 )

**Comment by lminiero** [comment]
@tuexen looks like the fix was made in a different repo and not this?

**Comment by tuexen** [comment]
> @tuexen looks like the fix was made in a different repo and not this?

The code is shared between several repos. The last push went to the usrsctp repository.

Thanks for reporting the issue.

**Comment by lminiero** [comment]
> The code is shared between several repos. The last push went to the usrsctp repository.
> 
> Thanks for reporting the issue.

Apologies, I should have realized from the references that started appearing here after your fix... I can confirm it builds fine now, thanks for taking care of this!
