### ISSUE TITLE
SCTP stream blocks up intermittently with large packets

### ISSUE THREAD

**Issue by somtin** [sctplab/usrsctp#432]
Our use case is to use SCTP to send large frames as well as lots of very small frames. The large and small frames are on different SCTP streams to avoid head-of-line blocking. However, we have observed that occasionally the stream with which we are sending large frames on blocks up, and we no longer receive any more data.

This seems to happen when at the receiver a packet arrives on one stream in the middle of a fragmented packet arriving on another. Once that happens, we never again see callbacks[1] to the upper layer from usrSCTP on that particular stream.

I have attached two files from the receiving usrSCTP stack:
* The first is a log of the usrSCTP output with SCTP_DEBUG defined
* The second is a wireshark capture on the interface where the packets arrive

Note that we have a custom header in between the UDP header and SCTP header which is 6 bytes big. The first two bytes of these is a packet type in LE, a value of 0 indicates a data packet to be passed to usrSCTP, anything else is not passed down to usrSCTP and can be ignored. I have attached a dissector for wireshark that will do this, set a filter of "cw_header.type == 0" to ignore the irrelevant packets.

The point where we see the failure is on packet 44384 of the capture, which is received at line 373715 of the log file. There are a couple of received fragmented packets, then the off-stream packet arrives (packet 44393, line 373787) and when the last fragment arrives (packet 44409, line 373817), we never get a callback on the high-data stream again.

I will be investigating this deeper next week to try and resolve the issue, but any thoughts or ideas would be very helpful!

The files mentioned above are uploaded in the following zip file.
[usrsctp_issues_files.zip](https://github.com/sctplab/usrsctp/files/4202328/usrsctp_issues_files.zip)

[1] We're using the callback API rather than recvv, to avoid running a thread per socket as we're opening a couple of sockets

**Comment by somtin** [comment]
It seems the issue is that the sending end is sending packets such that the TSN for the fragmented chunks of the message are not consecutive. This then throws off the receiving stack.

I spent some time digging around on the sender side of the stack. One thing to note is that when I was sending a 10 kB message, the stack would only emit 5 chunks to the send queue (I'm using NODELAY). This is quite a bit short, so I dug in a bit further, and found that the SS module is making some decisions on what stream to use in sctp_fill_outqueue, so I wonder if it's not emitting chunks for the complete message in one go? I'm using the priority scheduler rather than the default one, so I tried moving back to the default one and that seems to have fixed the issue!

**Comment by tuexen** [comment]
@somtin When using DATA chunks, the TSN assigned to the fragments of a user message must be consecutive. See https://tools.ietf.org/html/rfc4960#section-6.9.

If you want to interleave user message from different stream, I-DATA chunks must be used. See https://tools.ietf.org/html/rfc8260.
