### ISSUE TITLE
Error with -fsanitize=alignment

### ISSUE THREAD

**Issue by taylor-b** [sctplab/usrsctp#437]
Related WebRTC bug: https://bugs.chromium.org/p/webrtc/issues/detail?id=11405

The issue is with sctp_getaddresses, when casting addr to a sockaddr_conn.

On a 64 bit system, sockaddr_conn is 8-byte aligned due to one of its members being a pointer. However, sockaddr is only 4-byte aligned, so the compiler doesn't know it needs to insert four bytes of padding.

Fix on the way.

**Comment by tuexen** [comment]
Is this a compile time or run time thing? Which compiler does provide it?

**Comment by weinrank** [comment]
@tuexen It's a compile flag which detects undefined behavior at run time, similar to the memory and address sanitizers.
Supported e.g. by clang 

https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks

**Comment by tuexen** [comment]
@weinrank This means we need to use it in one of the examples on the buildbots (assuming that we run the undefined sanitizer there).

**Comment by weinrank** [comment]
Yep! 👍

**Comment by tuexen** [comment]
I have committed a change to `ekr_loop` such that it triggers the bug on our buildbots. Next step is to fix it.

**Comment by taylor-b** [comment]
Reminder that I have a PR: https://github.com/sctplab/usrsctp/pull/438/files

**Comment by tuexen** [comment]
Fixed by https://github.com/sctplab/usrsctp/commit/63d620ae9ab818cf51448c9ad0a04f9688c5f28b after cleaning up sctp_bindx(). Thanks for reporting and providing a patch!
