### ISSUE TITLE
MTU issues

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#442]
Hi all,

I'm trying to leverage larger MTUs and get high speeds in LAN environment. For the immediate tests, I'm using loopback interface which in my case has 16K MTU. I have determined that the real MTU is actually ~9000 (can't remember the exact number). Above that, I get IP fragmentation.

All those above are some explanations to offer a context to my problem. Here is the problem. Suppose we have pre-determined MTU of 5000. Consider it is determined out of band, well known and stable (does not change). There will be no IP fragmentation nor any fragmentation anywhere along the stack, including protocols like DTLS (I have tested it).

I am setting the HB and MTU like this, in one go:
```
//setup PMTUD and heartbeat
struct sctp_paddrparams params;
memset(&params, 0, sizeof (params));
memcpy(&params.spp_address, &_destAddress, sizeof (_destAddress));
params.spp_assoc_id = 0;
params.spp_flags = SPP_HB_ENABLE //HB info
		| SPP_PMTUD_DISABLE //we don't want PMTUD. We have it detected already
		;
params.spp_hbinterval = 1000; //Send a HB once a second
params.spp_pathmaxrxt = 10; //max of 10 HB missing after which the connection is terminated
params.spp_pathmtu = 5000;
usrsctp_setsockopt(_pSCTPSocket, IPPROTO_SCTP, SCTP_PEER_ADDR_PARAMS, 
	&params, sizeof (params));
```

When sending stuff with `usrsctp_sendv` I always send 4900 bytes chunks. That number is subjective and arbitrary. I've thought I should just allow 100 bytes extra, because I don't know what is the protocol overhead, and seems there is no way to find that information. And here is the issue: instead of sending a single SCTP packet with a single DATA chunk in it, the library is sending a sequence like this:

![Screen Shot 2020-03-15 at 17 12 36](https://user-images.githubusercontent.com/7860758/76704726-a6301600-66e3-11ea-8795-c50c798dbf6c.png)

I have tried to use SCTP_MAXSEG with both 5000 and 4900 and it still sends 4 `DATA` chunks per packet instead of one.

I'm expecting to send a single `DATA` chunk per SCTP packet. And no matter what I have tried so far, I can not convince the library to do that.

Running the head of master (`d520eafea3039ba883f3a449f55c4fb0283594f7`)

Best regards,
Andrei

**Comment by shiretu** [comment]
Follow up: despite my attempt to overcome that 10 bytes overshoot by sending 4900 bytes only instead of 5000 which is the MTU, I still overshoot the hard imposed target of 5000. As we can see, the pkts have 5010 bytes. I would love to know how can I impose that hard limit of X bytes per SCTP packet and how to convince the library to send a single large `DATA` chunk per SCTP packet.

**Comment by shiretu** [comment]
Followup 2:
Same conditions explained above, but instead of sending 4900 bytes, I thought I would send 1252 bytes per `usrsctp_sendv` call. I pretty soon get a connection abort. Attached the pcap files from both sides.

[Archive.zip](https://github.com/sctplab/usrsctp/files/4334474/Archive.zip)

**Comment by shiretu** [comment]
Followup 3:
More data on the issue:
```
sctpstat::sctps_sendpackets: 0
sctpstat::sctps_sendsacks: 0
sctpstat::sctps_senddata: 0
sctpstat::sctps_sendretransdata: 0
sctpstat::sctps_sendfastretrans: 0
sctpstat::sctps_sendmultfastretrans: 0
sctpstat::sctps_sendheartbeat: 0
sctp_status::sstat_primary::spinfo_state: 1
sctp_status::sstat_primary::spinfo_cwnd: 4380
sctp_status::sstat_primary::spinfo_srtt: 0
sctp_status::sstat_primary::spinfo_rto: 0
sctp_status::sstat_primary::spinfo_mtu: 5000
sctp_status::sstat_assoc_id: 3
sctp_status::sstat_state: 2
sctp_status::sstat_rwnd: 5000000
sctp_status::sstat_unackdata 0
sctp_status::sstat_penddata: 0
sctp_status::sstat_instrms: 0
sctp_status::sstat_outstrms: 1023
sctp_status::sstat_fragmentation_point: 1252
```

Every time I send exactly `sctp_status::sstat_fragmentation_point` bytes, I get immediately disconnected, even with the standard MTU (no other MTU options applied on the socket). Here are the pcap files: 
[Archive.zip](https://github.com/sctplab/usrsctp/files/4334494/Archive.zip)

**Comment by tuexen** [comment]
@shiretu I see your point. Configuring the MTU for the SCTP/DTLS stack might not work. The Browser vendors wanted a static setup which always works...
Path MTU discovery right now does not work (there is no ICMP feedback), but we have patches on the way.
However, static configuration should work. I'll look into it.

**Comment by shiretu** [comment]
@tuexen : Thanks for looking into that. The static MTU setting has now become my secondary concern (regarding that DATA fragmentation). The main issue became the one described in **Followup 2** and **Followup 3**. Those are show stoppers, at least for me. I can see how sending few packets of those exact size might trigger some unwanted dropouts.

**Comment by shiretu** [comment]
@tuexen: on large MTU (like explicitly configured LAN or loopback), I get well in excess of 1gbps. Seen 1.4gbps :)

**Comment by shiretu** [comment]
@tuexen : I am now performing PMTUD through STUN, completely outside of DTLS/SCTP :)
I'm able to determine the exact UDP payload size between the 2 points, byte accurate, with chrome on one side and my lib on the other side. Having that max UDP packet payload size, I can now compute max DTLS packet payload size as well, because OpenSSL has some primitives to spit out DTLS protocol overhead. Knowing this value, I would like to apply it to SCTP. However, I'm lacking the theoretical protocol overhead number, so, while knowing DTLS max payload size, I still can't compute the max SCTP DATA chunk size.

I would love to be able to compute that. It will make things so much better, especially on certain ISPs.

Also, it is paramount that once an MTU was set on the SCTP socket, the SCTP stack must not exceed it, under any circumstances. That will break the chain of computations upwards of it, in DTLS and finally in UDP. I can see that this rule is currently broken: setting MTU of 5000 yields SCTP packets of 5010 bytes long. 

Best regards,
Andrei

**Comment by tuexen** [comment]
What you provide in `spp_pathmtu` is what is written in the [RFC 6468](https://tools.ietf.org/html/rfc6458#section-8.1.12): It is the number of bytes available in an SCTP packet for chunks. So if you use `spp_pathmtu = 9000`, and you are using DATA chunks, your maximum number of bytes of a user message is `9000 - 16`. The overall SCTP packet will be `9000` bytes plus the size of the common header, which is `12`. So without fragmentation, you can get `8984` bytes in a packet of size `9012` bytes.
If you set the MTU using the `setsockopt()` call, before calling `connect()` or `accept()`, you will see DATA chunks of size `9000` bytes (including DATA chunk header). However, if you call `setsockopt()` after the association has been established, you will see a lot of bundled fragments. This is a limitation of the current code. When you establish the association, the default MTU will be used, which is `1280 - 12 = 1268`. Then the `setsockopt()` call will increase the path MTU or even all path MTUs, but not the association MTU. This association MTU is used for fragmentation.
Allowing also to increase the association MTU is a change coming with the PMTUD fix. If needed, I can put that in sooner. So let me know if you can set the MTU early enough... or if my description does not work in your setup.
Here is an example how to set the MTU on an end-point: https://github.com/sctplab/usrsctp/commit/0c9e6498e223c9e69bcea739ccef80f91ddf9e70.

**Comment by shiretu** [comment]
@tuexen: I can confirm: setting the MTU before bind/accept/connect solved the multi-DATA on the same SCTP packet issue.

**Comment by shiretu** [comment]
```
1584505171800 ms; global IN/OUT: speed:  -1/  2gbps; amounts: 0/1373707520
1584505176800 ms; global IN/OUT: speed:  -1/  2gbps; amounts: 0/2746695604
1584505181800 ms; global IN/OUT: speed:  -1/  2gbps; amounts: 0/4077255856
```

@tuexen : that's what a 9000 MTU does 👍

**Comment by tuexen** [comment]
Thanks for the feedback!
