### ISSUE TITLE
GAP Ack Blocks

### ISSUE THREAD

**Issue by paniksystem** [sctplab/usrsctp#443]
There is something i don't understand regarding gap ack blocks.
I send unordered DATA chunks against chrome 80. When there is missing packets i get something like this:
TSN: 9, gaps: [11,11][11,13]

If i understand correctly the only missing TSN is 10, but i get 2 gap blocks. 
Later when TSN 10 is finally received, TSN 12 is marked as missing even if it was "SACKED" and no packets were reneged.

When logging packets on the javascript side of chrome, i also see TSN 12 missing.

Is this gap ack blocks format normal ?

**Comment by shiretu** [comment]
Minor question: `When logging packets on the javascript side of chrome, i also see TSN 12 missing.`

How do you do that? I'm also interested in doing that. AFAIK, there's no such low level access in JS.

**Comment by paniksystem** [comment]
I just send packets < MTU with no bundling

**Comment by shiretu** [comment]
Oh, okay. That makes sense, I thought you had access to SCTP internals from JS. So you watch payloads contents, not really low level stuff. Got confused a bit

**Comment by tuexen** [comment]
Can you provide a .pcapng file or the debug output with packet information such that I can build a .pcang file? A trace from the data receiver, which is the sender of the SACKs would be good.
The SACK you describe is not how it should be:
https://tools.ietf.org/html/rfc8540#section-3.47.

**Comment by paniksystem** [comment]
i am sorry but i have no idea how to do that :D

**Comment by paniksystem** [comment]
It looks like it follows a rule:
gap % 2 are in fact missing TSNs

**Comment by paniksystem** [comment]
I get the same result with firefox:

```
< chunk cum_tsn_ack: 408, gap blocks: [
    {"start":410,"end":431}, // gap 1, received
    {"start":431,"end":434}, // gap 2, 432 surely missing
    {"start":434,"end":440},
    {"start":440,"end":442},
    {"start":442,"end":447},
    {"start":447,"end":449},
    {"start":449,"end":471},
    {"start":471,"end":473},
    {"start":473,"end":480},
    {"start":480,"end":482}
]
> send 409 // we should advance to 482 on the next SACK if 409 is received
< cum_tsn_ack: 431, gap blocks: [ // nope, 432 is missing as expected !
    {"start":434,"end":440},
    {"start":440,"end":442},
    {"start":442,"end":447},
    {"start":447,"end":449},
    {"start":449,"end":471},
    {"start":471,"end":473},
    {"start":473,"end":480},
    {"start":480,"end":482},
    {"start":482,"end":483}
]
```

**Comment by paniksystem** [comment]
Is this how usrsctp "misses" this when receiving SACKs from another usrsctp ?

```
if (frag_strt <= prev_frag_end) {
	/* This gap report is not in order, so restart. */
	 tp1 = TAILQ_FIRST(&asoc->sent_queue);
}
```

**Comment by tuexen** [comment]
I don't know the above notation. Are these SACK chunks or FORWARD-TSN chunks? What is triggering the sending of these chunks? Can you provide the incoming and outgoing packets? Then it is easy for me to reproduce the issue...

**Comment by paniksystem** [comment]
I don't use FORWARD-TSN capability.
I am just sending DATA chunks under the MTU (unfragmented) as unordered and reliable packets, all with the SACK IMMEDIATLY flag set to get instant feedback.
I then simulate packet loss and get these gap reports.
All of this on the same machine (Windows 10).

**Comment by paniksystem** [comment]
If i ignore each gap%2 and reports them as missing, everything goes smoothly but i was intrigued that i needed to do that to avoid slow retransmit timeouts. The above snippet is from sctp_indata.c (sctp_handle_segments)

**Comment by tuexen** [comment]
Are you running SCTP/UDP/IP or SCTP/DTLS/UDP/IP?

**Comment by paniksystem** [comment]
SCTP/DTLS/UDP/IP yes

**Comment by tuexen** [comment]
If you are using Firefox, you should be able to follow https://github.com/nplab/WebRTC-Data-Channel-Playground#trace-with-wireshark to get debug output and the information for the pcapng file.

**Comment by paniksystem** [comment]
I don't get it but NSPR_LOG_MODULES is set to SCTP:5,DataChannel:5 but i get 4 empty files:

firefox
firefox.child-1
firefox.child-1.moz_log
firefox.moz_log

am i missing something obvious ?

**Comment by tuexen** [comment]
Are they still empty after tearing down Firefox gracefully (like Quitting the application).
@weinrank Any ideas?

**Comment by paniksystem** [comment]
All right, documentation is not up to date, should be 
MOZ_LOG_FILE
MOZ_LOG

**Comment by paniksystem** [comment]
Ok, i'm a dumb dumb, sorry for wasting your time, i am off by an offset of 2 when reading start and end from the SACK...that's why my gaps starts where my last one ends

**Comment by tuexen** [comment]
Thanks for letting us know. Does the documentation for traffic capturing need an update?

**Comment by paniksystem** [comment]
yes:

`NSPR_LOG_MODULES` is now `MOZ_LOG`
`NSPR_LOG_FILE` is now `MOZ_LOG`

**Comment by tuexen** [comment]
@weinrank Can you update the documentation?
