### ISSUE TITLE
Build not possible: variable 'netp' set but not used 

### ISSUE THREAD

**Issue by maxboehm** [sctplab/usrsctp#447]
I am currently tinkering around with webrtc and janus. Two days ago building usrsctp was perfectly fine, since your latest commits it does not work anymore. 

Just uncomment the line where i checkout the version of a few days ago and it will work

Dockerfile:
```
FROM debian:buster

RUN apt-get update -y \
    && apt-get upgrade -y

RUN apt-get install -y \
    build-essential \
    autotools-dev \
    automake \
    git \
    libtool

RUN cd ~ \
    && git clone https://github.com/sctplab/usrsctp \
    && cd usrsctp \
    # Just uncomment the following line, and it will work
    #&& git checkout `git rev-list -n 1 --first-parent --before="2020-03-17 13:37" master` \
    && ./bootstrap \
    && ./configure --prefix=/usr \
    && make \
    && make install
```

Error: 

> netinet/sctp_usrreq.c: In function 'sctp_disconnect':
> netinet/sctp_usrreq.c:1279:23: error: variable 'netp' set but not used [-Werror=unused-but-set-variable]
>      struct sctp_nets *netp;
>                        ^~~~
> netinet/sctp_usrreq.c: At top level:
> cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
> cc1: all warnings being treated as errors
> make[1]: Leaving directory '/root/usrsctp/usrsctplib'
> make[1]: *** [Makefile:775: netinet/libusrsctp_la-sctp_usrreq.lo] Error 1
> make: *** [Makefile:407: all-recursive] Error 1

**Comment by apietrzak** [comment]
The same error here.

**Comment by lminiero** [comment]
See #448

**Comment by tuexen** [comment]
Thanks for the report. Should be fixed now.
