### ISSUE TITLE
Very low throughput

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#459]
Hi all,

We have noticed very low throughput when one of the ends is on BritishTelecom.

The BT side has 50mbps up and a lot more down (around 500mbps). We can barely reach 250kbps up or down via SCTP (within WebRTC).

```
IN/OUT: speed: 156kbps/ -1; amounts: 98908/0
IN/OUT: speed: 160kbps/ -1; amounts: 210336/0
IN/OUT: speed: 202kbps/ -1; amounts: 393128/0
IN/OUT: speed: 239kbps/ -1; amounts: 615984/0
IN/OUT: speed: 224kbps/ -1; amounts: 736176/0
IN/OUT: speed: 234kbps/ -1; amounts: 916464/0
IN/OUT: speed: 240kbps/ -1; amounts: 1092996/0
IN/OUT: speed: 254kbps/ -1; amounts: 1313348/0
IN/OUT: speed: 264kbps/ -1; amounts: 1532448/0
IN/OUT: speed: 266kbps/ -1; amounts: 1710232/0
```

The data sender is on BT side, the data receiver is somewhere else, with very good peering  (tested with iperf).

### Sender stats:
```sctpstat::sctps_sendpackets: 0
sctpstat::sctps_sendsacks: 6
sctpstat::sctps_senddata: 1406
sctpstat::sctps_sendretransdata: 464
sctpstat::sctps_sendfastretrans: 407
sctpstat::sctps_sendmultfastretrans: 8
sctpstat::sctps_sendheartbeat: 5
sctp_status::sstat_primary::spinfo_state: 1
sctp_status::sstat_primary::spinfo_cwnd: 3816
sctp_status::sstat_primary::spinfo_srtt: 56
sctp_status::sstat_primary::spinfo_rto: 1000
sctp_status::sstat_primary::spinfo_mtu: 1268
sctp_status::sstat_assoc_id: 3
sctp_status::sstat_state: 8
sctp_status::sstat_rwnd: 3988068
sctp_status::sstat_unackdata 9
sctp_status::sstat_penddata: 0
sctp_status::sstat_instrms: 1023
sctp_status::sstat_outstrms: 1023
sctp_status::sstat_fragmentation_point: 1252
```

### Receiver Stats:
```
sctpstat::sctps_sendpackets: 0
sctpstat::sctps_sendsacks: 1397
sctpstat::sctps_senddata: 20
sctpstat::sctps_sendretransdata: 0
sctpstat::sctps_sendfastretrans: 0
sctpstat::sctps_sendmultfastretrans: 0
sctpstat::sctps_sendheartbeat: 26
sctp_status::sstat_primary::spinfo_state: 1
sctp_status::sstat_primary::spinfo_cwnd: 3804
sctp_status::sstat_primary::spinfo_srtt: 89
sctp_status::sstat_primary::spinfo_rto: 1000
sctp_status::sstat_primary::spinfo_mtu: 1268
sctp_status::sstat_assoc_id: 3
sctp_status::sstat_state: 8
sctp_status::sstat_rwnd: 3997687
sctp_status::sstat_unackdata 0
sctp_status::sstat_penddata: 0
sctp_status::sstat_instrms: 1023
sctp_status::sstat_outstrms: 1023
sctp_status::sstat_fragmentation_point: 1252
```

I would like to disable waiting for 3 `SACK` with gaps before sending the missing `DATA`, and send it right away, but I don't know how. There is an enormous amount of time (more then 150ms) between when the sender gets the news of a gap via an SACK from receiver, and the sender trying to fill that gap with a retransmission.

The used version is the head of master (https://github.com/sctplab/usrsctp/commit/83dcca61125fce4c94d1279659c9dae07434f469)

I also have detailed capture files taken on both ends with tcpdump, along with the necessary crt file to decrypt the DTLS layer. This will show the timings, the pkts send (attempts) and what is actually received.

If access to those is needed, please let me know, and I will make them available via email.

**Comment by tuexen** [comment]
Yes, please send me a packet capture. The "3" in the "3" gaps is not a configurable parameter. So you can't switch that easily. Why is the RTT 150 ms?

**Comment by shiretu** [comment]
@tuexen: I have measured the RTT with a simple UDP based tool I have created. The RTT has a sufficiently steady value between 46 and 56 millis. The deviating values are very very few. Average is 52ms.

The RTT was measured by sending 100 packets with X seconds between the sends. That X was then halved, and another 100 pkts sent using a new silence duration. And so forth. Basically accelerating the sends. Starting X was 5  seconds. Ending X was 1ms.

So, to answer your question, RTT is ~50ms. What we see there, is the cumulated 3 SACKs needed to send the missing pkt again. Which is a huge 150ms.

Also, the RWND is almost always at high value, which indicates that the receiver has plenty of space to accommodate new incoming pkts, yet is not getting them.

**Comment by tuexen** [comment]
@shiretu Thank you. Do you have an idea what the packet loss rate is? It seems that there is an extreme high packet loss rate...

**Comment by tuexen** [comment]
@shiretu Are you running a request response protocol in the application? Or is the sender trying to send data without needing a trigger form the peer?

**Comment by shiretu** [comment]
@tuexen: The protocol is quickly put together. I send 1400 bytes UDP pkts, with the first 16 bytes as follows:
1. 64 bits counter
2. 64 bits CLOCK_MONOTONIC value

The responder simply sends the received packet back, without touching it in any way, the moment it gets it.

The sender will get that back, gets a brand new 64 bits CLOCK_MONOTONIC reading from the system, and compares it with the one it just received back. Boilerplate classic RTT.

So this is actually worst case when both inbound and outbound bitrate is exercised to the maximum. The full 1400 pkts are sent back.

I will also do measure the pkts loss, don't know to give you a value in this very moment. The counter is there, but not yet used.

This was made to get a feeling of what is the actual RTT, and it seems the same as the SCTP reports.

**Comment by shiretu** [comment]
@tuexen: Also, it is strange that when doing WebRTC over VPN, this low throughput goes away, and we get much higher throughput. This is what the customer told me. I need to check that, but I have no reason to not believe him.

**Comment by tuexen** [comment]
@shiretu Do you observer with your UDP test app any kind of packet loss? I guess you can get that from observing your counter.

The question about the application layer is related to what you do over WebRTC, not your UDP test app. SCTP needs three gap reports, but not three round trip times. You would have three gap reports after one round trip time and three inter-sending times.

**Comment by shiretu** [comment]
@tuexen : Inside the app, I feed the SCTP until it can't take no more (returns EAGAIN) and then I stop.

When traffic comes in, I get rid of the DTLS layer, and feed the SCTP raw bytes into the SCTP stack. After doing this, because that rawSCTP data might contain some SACKs, and things might get ACKed and removed from SCTP stack, I try to force feed it again. Same thing: feed it until I get EAGAIN again. And the cycle keeps repeating.

Because of this, the send space for that connection is alway filled to the brim, it always has data to send.

**Comment by shiretu** [comment]
@tuexen : What I have noticed is that the callback for sending data is 99% executed from the thread where I pump the incoming raw SCTP bytes into the stack (using `usrsctp_conninput`), or where I call `usrsctp_sendv`. Both of those places are the same thread actually. So in my env, I have the main thread doing that (calling `usrsctp_sendv` and `usrsctp_conninput`) and the internal SCTP thread which I understand that takes care of timers and other things.

I rarely see that raw bytes SCTP outbound callback called from SCTP internal thread. Probably on timers and other things

**Comment by shiretu** [comment]
@tuexen : Another piece of info: I read the MTU from the SCTP stack, and that is the size of all my messages. I never send a message longer that. In other words, I do not have any message spanning across DATA chunks. Every DATA chunk is a well defined complete message. All the aggregation of larger logical messages is done on upper layers. This is because we do multimedia streaming, and n o matter what, those big frames will never fit into a single DATA. Also, if I send a full frame it might actually exceed the 128KB limit. And even if that's not a problem, suppose we make it megabytes in size though some obscure APIs, we still have the biggest problem: lack of interleaving. So if a stream puts a large frame on a webrtc data channel , it will basically starve the rest of the streams. So I'm forced to do chunking, and do round robin on the data channels, and offer them equal chances to send little chunks.

**Comment by shiretu** [comment]
```
rtt: 51.999 ms; speed: 45 mbps/sec; missing: 0/1597
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 0/5742
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 0/9927
rtt: 120.000 ms; speed: 35 mbps/sec; missing: 0/13775
rtt: 132.000 ms; speed: 51 mbps/sec; missing: 0/17879
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 0/22433
Missing 2 packets.
Out of order -1 packets
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/26639
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/30845
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/35033
rtt: 51.999 ms; speed: 46 mbps/sec; missing: 2/39245
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/43451
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/47624
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/51806
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/56018
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 2/60219
Missing 2 packets.
Out of order -1 packets
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 4/64406
rtt: 52.000 ms; speed: 45 mbps/sec; missing: 4/68600
Missing 2 packets.
Out of order -1 packets
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/72687
rtt: 95.999 ms; speed: 40 mbps/sec; missing: 6/76613
rtt: 56.000 ms; speed: 46 mbps/sec; missing: 6/80964
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/85185
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/89396
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/93592
rtt: 52.000 ms; speed: 45 mbps/sec; missing: 6/97785
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/101972
rtt: 51.999 ms; speed: 47 mbps/sec; missing: 6/106173
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/110326
rtt: 52.000 ms; speed: 46 mbps/sec; missing: 6/114516
```

That speed is computed using ACK-ed RTTs, to be sure that is real data which reached the dest, not the sending speed.

The RTT line is printed once a second, the missing packets line is printed every time it happens.

So, to answer your question, we have about 6 packets missing out of 114516 sent.

**Comment by shiretu** [comment]
In the pic below, we can clearly see how we have periodic 50ms sleeps, without any data flowing. By the time that happens, as explained above, the SCTP stack has plenty of data to send, yet is only sending 3-4 DATA pkts, waits 50ms, sends another 3-4 DATA, waits again, etc.

At that point, there are no packet drops.

![Screen Shot 2020-05-02 at 14 24 39](https://user-images.githubusercontent.com/7860758/80862891-1ccba780-8c81-11ea-9d22-57af4f2ebbdb.png)

**Comment by tuexen** [comment]
That is perfectly fine. The limiting factor here is the congestion control and the burst mitigation in particular. `net.inet.sctp.maxburst` limits the number of packets allowed to be sent at one send opportunity to 4, which is the default. You might think this is bad, but I'm looking at the packet losses, which are actually bad. There is massive packet loss.

I have observed that the sender sets the I bit on all DATA chunks. So we see a SACK chunk 

Look at the sender tracefile you sent. In Frame 209, 210, 211, and 112 the sender sends four data chunks. The `TSN` ends with 55, 56, 57, and 58. The last packet of these is dropped by the network. 

About 50 ms later in total five SACK are received, each ACKing one of `TSN` 53, 54, 55, 56, and 57. During this period the sender sends `TSN`s 59, 60, 61, 62, 63, 64. Please note that this phase takes only 527 mirco seconds. From these 6 packet sent, the past four are dropped. Again, this is a tail loss in a phase of sending.

About 50 ms later, we get the a SACK (triggered by reception of `TSN` 59) reporting the loss of `TSN` 58 first, and another one (triggered by the reception of `TSN` 60, which report the loss of `TSN` 58 for the second time. The reception of the SACKs triggers the sending of two DATA chunks with `TSN` 65 and `TSN` 66. Please note that the second is dropped. Again, a tail loss.

About 50ms later, a SACK arrives (triggered by the reception of `TSN` 65, which reports that `TSN 58` is missing for the third time and a fast retransmit is triggered.

This takes about 150 ms.

The problem for me is not how long it takes to retransmit packets. This would happen fast with RACK, for example, but the problem is why the packets are dropped. It is always tail loss. This means the sender is sending the packets too fast. I guess you don't experience the loss with your test tool, since you are waiting 1 ms between each packet. I guess, I you send batches of packets without waiting between them, you will also be able to measure packet loss.

I'm not sure where the packet loss happens and why. If you say the problem disappears if you use a VPN, this could mean that the processing time of the VPN increases the time between the sending of the packet and reduces the packet loss. That would be a problem on the sending host. Or it could be that some node in the network doesn't apply any more the traffic shaping because it does not classify the VPN traffic and the non-VPN traffic the same way.

How to improve things: The goal should be to reduce the packet dropping. You could try to reduce  `net.inet.sctp.maxburst` to 2, but I'm not sure this will really help. Not sure if you could sleep a short time between sending the packets (a very trivial from of pacing them out).

**Comment by shiretu** [comment]
Thanks @tuexen . I will hack the pacing of pkts. In the UDP test, there is a 200us sleep between the pkts. I have lowered that from 1ms to reach the full potential of that link to 50mbps. With 1ms, is much lower.

**Comment by shiretu** [comment]
And there are no pkts drops. I mean nothing compared to when I do SCTP. It might also be the DTLS layer, it might try to send overall larger pkts!? I’ll inspect the resulted sizes

**Comment by tuexen** [comment]
> And there are no pkts drops. I mean nothing compared to when I do SCTP. It might also be the DTLS layer, it might try to send overall larger pkts!? I’ll inspect the resulted sizes

Can you send `n` packets in a row and then sleep for some micro seconds?

How did you capture the tracefile at the sender side? I guess you are running Wireshark or tcpdump...  If this is correct, I don't think the DTLS layer is doing anything strange, since you are capturing the packets after they have been processed by the SCTP, DTLS, UDP and IP layer.
We might can not conclude that they actually when on the wire. For that you would need to capture on a device which is not the sending host (like at the access router).

**Comment by shiretu** [comment]
The wrtc session is monitored on both ends using tcpdump. Did this because while the sender will register the pkts as sent, the other side might not actually get them. That’s why the archive contains sender.pcap and receiver.pcap. There are 2 additional pcap files resulted from the first 2, where I’ve filtered DTLS only, using wire shark and save them separately. So we can nicely decrypt them using the cert.

I do not have access to the NAT immediately in front of the sender. I have access to the NAT in front of the receiver tho.

And yes, I will do back to back sends in the UDP test app, and monitor the drops. I still have to overall stay below 50mbps, so instead of having smoothed our waits of 200us, I will have to wait something like 2ms after each 10pkts sent without waiting. Is this what you want to find out?

**Comment by tuexen** [comment]
> And yes, I will do back to back sends in the UDP test app, and monitor the drops. I still have to overall stay below 50mbps, so instead of having smoothed our waits of 200us, I will have to wait something like 2ms after each 10pkts sent without waiting. Is this what you want to find out?

Yes, I would like to see some values for the batch size `n`, but you can wait even longer than 2ms. In the SCTP case we have pauses of 50ms. So it is the tail drop which happens at the batches which bothers me.

**Comment by shiretu** [comment]
Sending 20 pkts back to back (no wait), followed by 1 second wait.

First number from each line represents the timestamp in seconds (gathered as us, but divided by 1000000.0)

```
197457.285082 - rtt: 56.000 ms; speed: 235 kbps/sec; missing pkts: 2; total sent pkts: 501
197458.233081 - Send pkt 20
197458.233081 - Send pkt 19
197458.233081 - Send pkt 18
197458.233081 - Send pkt 17
197458.233081 - Send pkt 16
197458.233081 - Send pkt 15
197458.233081 - Send pkt 14
197458.233081 - Send pkt 13
197458.233081 - Send pkt 12
197458.233081 - Send pkt 11
197458.233081 - Send pkt 10
197458.233081 - Send pkt 9
197458.233081 - Send pkt 8
197458.233081 - Send pkt 7
197458.233081 - Send pkt 6
197458.233081 - Send pkt 5
197458.233081 - Send pkt 4
197458.233081 - Send pkt 3
197458.233081 - Send pkt 2
197458.233081 - Send pkt 1
197458.285081 - rtt: 52.000 ms; speed: 235 kbps/sec; missing pkts: 2; total sent pkts: 521
197459.229080 - Send pkt 20
197459.229080 - Send pkt 19
197459.229080 - Send pkt 18
197459.229080 - Send pkt 17
197459.229080 - Send pkt 16
197459.229080 - Send pkt 15
197459.229080 - Send pkt 14
197459.229080 - Send pkt 13
197459.229080 - Send pkt 12
197459.229080 - Send pkt 11
197459.229080 - Send pkt 10
197459.229080 - Send pkt 9
197459.229080 - Send pkt 8
197459.229080 - Send pkt 7
197459.229080 - Send pkt 6
197459.229080 - Send pkt 5
197459.229080 - Send pkt 4
197459.229080 - Send pkt 3
197459.229080 - Send pkt 2
197459.229080 - Send pkt 1
197459.285080 - rtt: 56.000 ms; speed: 235 kbps/sec; missing pkts: 2; total sent pkts: 541
197460.233079 - Send pkt 20
197460.233079 - Send pkt 19
197460.233079 - Send pkt 18
197460.233079 - Send pkt 17
197460.233079 - Send pkt 16
197460.233079 - Send pkt 15
197460.233079 - Send pkt 14
197460.233079 - Send pkt 13
197460.233079 - Send pkt 12
197460.233079 - Send pkt 11
197460.233079 - Send pkt 10
197460.233079 - Send pkt 9
197460.233079 - Send pkt 8
197460.233079 - Send pkt 7
197460.233079 - Send pkt 6
197460.233079 - Send pkt 5
197460.233079 - Send pkt 4
197460.233079 - Send pkt 3
197460.233079 - Send pkt 2
197460.233079 - Send pkt 1
197460.285079 - rtt: 52.000 ms; speed: 235 kbps/sec; missing pkts: 2; total sent pkts: 561
```

**Comment by shiretu** [comment]
No EAGAIN/EWOULDBLOCK on the raw DTLS sending for WebRTC.

This is how the send callback is called. First column is absolute time in seconds, second column is the amount of data to be sent, and the 3rd column is the diff of absolute time between 2 consecutive sends. Marked with that color are the longer silence moments, when the value is bigger than 20ms

[sends.pdf](https://github.com/sctplab/usrsctp/files/4568633/sends.pdf)

**Comment by tuexen** [comment]
So the result is that only two packets were lost in total? If that is true, then we are still missing the reason why packets are dropped.

**Comment by tuexen** [comment]
> No EAGAIN/EWOULDBLOCK on the raw DTLS sending for WebRTC.

Which OS is being used on the sender side?

**Comment by shiretu** [comment]
yes, that's what it means. I'm trying to figure out what is going on. This is a very very strange thing... Noticed that the DTLS pkts are 1317 bytes long. Will adjust the SCTP data sizes so it becomes a multiple of 4 bytes, and also will remove SCTP_SACK_IMMEDIATELY.

The OS is ubuntu 18 x86_64 on both sides

**Comment by shiretu** [comment]
What is the send callback supposed to return? I see that it wants an integer. I currently return 0 on success and 1 on failure

**Comment by shiretu** [comment]
@tuexen : OMG Michael.......

i was setting TOS on the socket.........

**Comment by shiretu** [comment]
It really does not like `SOCKET_TOS_DSCP_EF`, which is a define which is 184 for me

![Screen Shot 2020-05-02 at 22 59 39](https://user-images.githubusercontent.com/7860758/80890843-c4b89380-8cc8-11ea-918e-f890571df67a.png)

**Comment by tuexen** [comment]
> @tuexen : OMG Michael.......
> 
> i was setting TOS on the socket.........

And that's it? It would explain why the VPN tunnel helped assuming that it was not copying the TOS byte to the outer header.

**Comment by shiretu** [comment]
Yep! full 50mpbs...... on webrtc

**Comment by shiretu** [comment]
and ofc.... was not setting TOS on the UDP testing tool....

**Comment by tuexen** [comment]
Glad you found it! I didn't catch it either although I was looking at the identification field in the IP header to see how many packets were sent in between. Next time I (and you also, I guess) will also have a look at the TOS byte.

**Comment by shiretu** [comment]
Man this was such a b#ch to find... Many many thanks for the guidance!!!
