### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by epsilon-0** [sctplab/usrsctp#460]
Is it possible to build this on OpenBSD?  
Currently it does not seem like support exists.

**Comment by tuexen** [comment]
Have you tried it? There is at least `__Userspace_os_OpenBSD` and I think I used that when I thought it might be right. But I haven't tested it. Give it a try and report if it works or not. Right now I have no OpenBSD setup for testing, but that could change if there is interest.

**Comment by tuexen** [comment]
@weinrank will setup a buildbot and we will see.

**Comment by tuexen** [comment]
It seems to build: http://buildbot.nplab.de:18010/#/builders/14

Please open separate issues if you find problems on OpenBSD.

**Comment by epsilon-0** [comment]
Great. Thanks a lot!!
