### ISSUE TITLE
Feature request: usrsctp_get_ulpinfo

### ISSUE THREAD

**Issue by taylor-b** [sctplab/usrsctp#465]
When creating a socket, you pass in a `void* ulp_info` which is also passed into the receive callback for that socket, which can conveniently be used to associate the socket with a C++ class or whatnot.

However, that pointer is not passed into the send callback. And although there is a `usrsctp_set_ulpinfo` function, there is no equivalent getter.

Is there any reason not to add one? Due to its absence, we've been using the `sockaddr_conn` address to store a pointer value, but it's come to our attention that [that's not a good idea](https://bugs.chromium.org/p/chromium/issues/detail?id=1076703).

**Comment by tuexen** [comment]
There is no reason not to have `usrsctp_get_ulpinfo()`. Simple to add. However, it makes a lot of sense to have it also available in the send callback. I'm almost inclined to break the API and to add it there. It should have been there right from the beginning... Any opinions?

**Comment by taylor-b** [comment]
I generally wouldn't be opposed to breaking the API, though due to the relationship between chromium, webrtc and usrsctp, I'd need to find some way for a single revision of webrtc code to compile successfully before and after the usrsctp change, which may be tricky. Meaning I'd need code that would automatically call `usrsctp_socket` with a callback with the correct number of arguments.

But I'll leave it up to you. I'm sure I can figure out something.

**Comment by taylor-b** [comment]
It turns out this was not enough for my needs, since the `conn_output` callback from `usrsctp_init` doesn't provide the socket handle *or* ulpinfo, just the socket address.

May file a new issue in the future regarding this.
