### ISSUE TITLE
ABORT when creating an association in rtLinux

### ISSUE THREAD

**Issue by daichundi** [sctplab/usrsctp#469]
There is an ABORT chunk sent out immediately by client when it receive INIT_ACK from server. This problem was only found on rtLinux OS, but return to normal when we remove RT patch from kernal.
the wireshark trace is like this:
![image](https://user-images.githubusercontent.com/20158894/82190063-054c1a00-9923-11ea-8d74-e441225aebcf.png)
ps: the verification tag in ABORT is the same as INIT_ACK. So it looks like the abort chunk is sent by usrsctp. But i can't find where it is from. The procedure is keep on and the COOKIE_ECHO is sent out as normal.

**Comment by tuexen** [comment]
It would be easier to look at the .pcap file. Are you using two different physical machines. If you see such an ABORT, it normally comes from having the kernel stack enabled in addition to using a userland stack.  I'm not sure about the two INIT-ACK chunks. Are they a timer based retransmission? A .pcap file would help here.

**Comment by daichundi** [comment]
sorry for my unclear description. I think two INIT_ACK chunks is due to repeat capturing, since the peer is run in VM_Ware. If I capture pcap in VM_Ware, we could see only one INIT_ACK.

**Comment by tuexen** [comment]
Are you running rtLinux as a VM in WMWare? Please provide a capture from within the VM.

**Comment by daichundi** [comment]
The rtLinux is running at client. The server is running on VMWare. This is the log captured within the VMWare. 
![image](https://user-images.githubusercontent.com/20158894/82294411-afd64280-99e0-11ea-969d-ab8fc3996854.png)


[usrsctp_conn_abort.zip](https://github.com/sctplab/usrsctp/files/4648705/usrsctp_conn_abort.zip)

**Comment by tuexen** [comment]
The client uses usrsctp, runs on the host OS and uses 172.28.14.240.

The server uses a Linux kernel stack, runs in the VM and uses 172.28.12.128.

What happens is that whenever you sent an SCTP packet from VM towards the host, some instance sends a packet with an ABORT chunk towards the the VM. So I guess that you have either on your host another SCTP stack running (could be a kernel stack, could be another instance of usrsctp) or you are using a NAT between the VM and the Host. In the first case, ensure you are running only a single instance of SCTP. What is the host OS? If it is Linux, you can check with `lsmod` what kernel modules are loaded. If SCTP is listed there, you have your other stack. To avoid NAT interactions, please use a bridged interface.

**Comment by daichundi** [comment]
yes. It shows sctp is loaded in the host OS by the command of lsmod. So does it means the kernal sctp service is also working? how can i remove it? when i use rmmod ,it shows sctp is in use. Thank you very much.

**Comment by tuexen** [comment]
Yes, the Linux kernel implementation is also active. I'm not a Linux expert, but at some point of time you could enforce the unload. The other possibility is to reboot the Linux system and avoid that the kernel extension is loaded. How you achieve this, depend on the reason why it was loaded.

I don't think I can help there a lot, since this is a linux admin problem for the host OS. So I'm closing this.
