### ISSUE TITLE
[Question] The purpose of `SCTP iterator` thread.

### ISSUE THREAD

**Issue by mstyura** [sctplab/usrsctp#471]
I'm curios what is the purpose of `SCTP iterator` thread. 
I'm currently trying to migrate to single threaded API when library is initialized via `usrsctp_init_nothreads` and `usrsctp_handle_timers` is explicitly invoked by user application.

I've noticed that `SCTP iterator` thread is created even when library is initialized via `usrsctp_init_nothreads`. 
I don't see it ever executed in a scenario of WebRTC's data channel.

Maybe `SCTP iterator` should not be started at all? Could you please clarify?

**Comment by tuexen** [comment]
The iterator thread deal with stuff, which would take too long to do it instantly. For example, if you have a 1-to-many style sockets with a lot of associations and you send a message on all associations. Or if you are adding an interface address. Then you need to do the ASCONF dance on all associations, which are not explicitly bound. This could take too long. The single thread support is a code contribution, so I don't know exactly how the handling of the iterator thread is intended in that case.
