### ISSUE TITLE
ifr_flags and ifr_prevflags definitions are indexing a short as if it were a an array

### ISSUE THREAD

**Issue by na-g** [sctplab/usrsctp#478]
See https://github.com/sctplab/usrsctp/blob/fbadabe48671c3273d2cf3e478e38cdd4d471c15/usrsctplib/netinet/sctp_os_userspace.h#L399

and https://github.com/sctplab/usrsctp/blob/fbadabe48671c3273d2cf3e478e38cdd4d471c15/usrsctplib/netinet/sctp_os_userspace.h#L413

**Comment by tuexen** [comment]
Fix by https://github.com/sctplab/usrsctp/commit/6ca54a97eb2727aa89e76aa8a84667170def2e62. Thanks for the report.
