### ISSUE TITLE
question about the library of ssl

### ISSUE THREAD

**Issue by ycyang1229** [sctplab/usrsctp#479]
hi, I am new here. I wonder is it possible to change the library of ssl from openssl to mbedtls? If I want to use mbedtls, what obstacles will I face? Thanks.

**Comment by tuexen** [comment]
I don't see what relationship between openssl and usrsctp you are thinking about? I don't see one...

**Comment by ycyang1229** [comment]
I went this project quickly, and I found one header file including openssl/sha.h. I guessed usrsctp may use some functionalities of ssl. Did I mistaken it?
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_sha1.h#L57

**Comment by tuexen** [comment]
Ahh, I see. You might be able (I did not test this) to use the SHA-1 implementation of OpenSSL instead of a private one...

**Comment by ycyang1229** [comment]
Hmm, let me dive it. Btw, if I add the part of mbedtls, will you have any interest in putting it back to upstream?

**Comment by tuexen** [comment]
if it is ifdefed appropriately, I'm fine to take it.

**Comment by ycyang1229** [comment]
Cool! Thanks!
