### ISSUE TITLE
No longer builds on Ubuntu 20.04

### ISSUE THREAD

**Issue by nazar-pc** [sctplab/usrsctp#493]
I was successfully building commit 79ce3f1e13cd1cb283871ec5a9f90cf4062d91d4, but with latest commit 7f179204cc871434d6751259bc0064e5416cb3fa it fails with:
```
The Meson build system
Version: 0.53.2
Source dir: /usrsctp
Build dir: /usrsctp/build
Build type: native build

meson.build:82:28: ERROR: Expecting rparen got rbracket.
    add_project_arguments([]], language: 'c')
                         ^__^
```
Apparently something broke in between those 2 snapshots.

**Comment by tuexen** [comment]
It was me... Sorry about that.
It should be fixed in https://github.com/sctplab/usrsctp/commit/2cb9d6e3ccbd11eadaabc0c8af53a917ecb0266f.
Thanks for reporting.
