### ISSUE TITLE
Potential memory leak if GetAdaptersAddresses() fails

### ISSUE THREAD

**Issue by jswirl** [sctplab/usrsctp#50]
Returning on error does not release allocated memory pointed to by `pAdapterAddrs`:
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_userspace.c#L188
and
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_userspace.c#L222.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/52165cb8a0c1720d611f1816cc20324e082d70e7.
Thanks for the report.
