### ISSUE TITLE
Can you please remove this atrocity with -U__APPLE__?

### ISSUE THREAD

**Issue by pps83** [sctplab/usrsctp#508]
https://github.com/sctplab/usrsctp/blob/547d3b46c64876c0336b9eef297fda58dbe1adaf/meson.build#L190

That ridiculousness in usrsctp to undef platform defines was finally removed. However, some projects (notably webrtc) still link to usrsctp versions before it was removed. Because of that I'm getting weird compilation errors with latest iOS toolchain and the errors are somewhere deep inside system headers. Most likely due to internal checks for __APPLE__ in these headers which results in broken builds now. When I removed `-U__APPLE__` these errors disappeared. When I check usrsctp I still see this -U__APPLE__ in the project and this should be removed

**Comment by lgrahl** [comment]
I think that's an oversight, so thanks for reporting it.

But: Language. Be respectful. Thank you.

**Comment by pps83** [comment]
> I think that's an oversight, so thanks for reporting it.


By the way, webrtc was updated to usrsctp bee946a606752a443bd70bca1cb296527fed706d that doesn't have the fix for platform defines. They didn't update to latest for these reasons (from their commit log):

```
Update usrsctp to bee946a606752a443bd70bca1cb296527fed706d.

This incorporates over a year and a half of changes, including
several fixes for security vulnerabilities.

Had been prevented from updating it due to a deadlock issue,
however the commits that introduced that issue have been reverted.

Intentionally not updating to tip-of-tree since there are changes
in progress; will roll again when more confident things are stable.

Commit log since last roll:
https://chromium.googlesource.com/external/github.com/sctplab/usrsctp/+log/7a8bc9a90ca9..bee946a60675

Bug: chromium:1025302

```

**Comment by lgrahl** [comment]
And @taylor-b is/was actively working on resolving a couple of issues, so I suppose they're on it.

**Comment by tuexen** [comment]
The fix the webrtc was waiting for is https://github.com/sctplab/usrsctp/commit/939d48f9632d69bf170c7a84514b312b6b42257d. It seems to work, since I haven't heard any issue regarding that change.
