### ISSUE TITLE
Error count for %p now %d thresh:%d logs seen, but all the data is properly sent

### ISSUE THREAD

**Issue by jmillan** [sctplab/usrsctp#513]
We're seeing the error log from time to time when sending to the full capacity. This is, trying to keep the usrsctp send buffer as full as possible[*].

Everything arrives to the destination properly, so perhaps this is not an error as such, but maybe a warning or a log information.

 Here the log with some more context.

```txt
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Ok, Common input processing called, m:0x7fbc9a015610 iphlen:0 offset:12 length:28 stcb:0x7fbc98000400 +13ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | stcb:0x7fbc98000400 state:8 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | sctp_process_control: iphlen=0, offset=12, length=28 stcb:0x7fbc98000400 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | sctp_process_control: processing a chunk type=3, len=16 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | SCTP_SACK +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | SCTP_SACK process cum_ack:dd3b2fed num_seg:0 a_rwnd:129644 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Timer type 1 stopped: inp=0x7fbca000d600, stcb=0x7fbc98000400, net=0x7fbc8fc176d0. +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Timer type 1 started: ticks=1000, inp=0x7fbca000d600, stcb=0x7fbc98000400, net=0x7fbc8fc176d0. +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Check for chunk output prw:119536 tqe:1 tf=8316 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Calling chunk OUTPUT +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | m-c-o put out 1 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | m-c-o put out 1 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | m-c-o put out 1 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | m-c-o put out 1 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | m-c-o put out 0 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Ok, we have put out 4 chunks +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | chunk OUTPUT returns +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Timer type 5 goes off. +3ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Timer type 5 started: ticks=31144, inp=0x7fbca0855e00, stcb=0x7fbca0001c00, net=0x7fbc9fc087e0. +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | m-c-o put out 0 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Ok, we have put out 0 chunks +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Timer type 5 handler finished. +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Timer type 1 goes off. +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Error count for 0x7fbc9fc087e0 now 1 thresh:5 +0ms
  mediasoup:Channel [pid:87218] DepUsrSCTP::sctpDebug() | Overall error count for 0x7fbca0001c58 now 1 thresh:10 state:3 +0ms
  mediasoup:WARN:Channel [pid:87218] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP message sent failure [streamId:1, ppid:51, sent:yes, error:0x00000000, info:0x7d] +0ms
```

As a note, we use our own sockets, so usrsctp does not send anything itself.

Should we be worried about something not working properly?

[*]: We do this by maintaining the count of the buffered amount size of the send buffer in usrsctp, which we calculate using the new free buffer information provided by `send_cb` callback and also considering the data size we send over `usrsctp_sendv`.

**Comment by jmillan** [comment]
As long as we see, this error log is only shown when we apply network constraints to our scenario. If there are no network constraints it seems that the send buffer is drained fast enough and this error log does not appear.

**Comment by ibc** [comment]
So the thing is that, even controlling the sending buffer (by never telling `usrsctp` socket to send more than it can) we get the above error when calling `usrsctp_sendv()`, which defeats the purpose of using `send_cb`.

**Comment by tuexen** [comment]
What is the error you are referring to? I see in the above log that the retransmission timer fires. That is fine and happens if a packet was dropped and the loss can't be fixed by fast retransmission. I don't know, what
```
  mediasoup:WARN:Channel [pid:87218] RTC::SctpAssociation::OnUsrSctpReceiveSctpNotification() | SCTP message sent failure [streamId:1, ppid:51, sent:yes, error:0x00000000, info:0x7d] +0ms
```
means. `usrsctp` should not trigger a send failure notification in this case.

**Comment by jmillan** [comment]
We handle the usrsctp notifications [here](https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/SctpAssociation.cpp#L917). This particular notification is a 'SCTP_SEND_FAILED_EVENT' as you can see in the code.

As said, we are not loosing any packet (al least anyone sent reliably).

**Comment by tuexen** [comment]
OK. Then I think this is what happened:
* You send a user message unreliable, it gets sent but the packet is dropped in the network.
* The retransmission timer expires and the user message is abandoned. Therefore it will not be retransmitted, but reported as lost to the user application (assuming you subscribed to these notifications)

Looks like it the code does what it is supposed to do.

**Comment by jmillan** [comment]
Understood,

Makes sense. Let me close the issue.
