### ISSUE TITLE
Callbacks fired with invalid data

### ISSUE THREAD

**Issue by chadnickbok** [sctplab/usrsctp#52]
I've been banging my head against this all day, and I just can't seem to figure it out.

Basically, I'm trying to create a very simple ICE <-> DTLS <-> SCTP example to try and understand things better, and I just can't seem to get the sctp data-ready callback to work. ICE seems to work fine, I can finish my DTLS handshake fine, I can send the SCTP handshake packets (and cookie packets) back-and-forth, but the moment SCTP decides it wants to send something to my app it freaks out.

Here's an brief snippet from my log:

> Ok, Common input processing called, m:0xb5cdb00 iphlen:0 offset:12 length:136 stcb:0xb5bc640
> stcb:0xb5bc640 state:4
> sctp_process_control: iphlen=0, offset=12, length=136 stcb:0xb5bc640
> sctp_process_control: processing a chunk type=11, len=4
> SCTP_COOKIE-ACK, stcb 0xb5bc640
> sctp_handle_cookie_ack: handling COOKIE-ACK
> moving to OPEN state
> data of length 189316272 received on stream 123 with SSN 34835, TSN 0, PPID 2965129227 (bad callback with weird values)
> SCTP: Invalid user_data received (callback doesn't have my user_data set)
> data of length 189316272 received on stream 123 with SSN 34835, TSN 0, PPID 2965129227 (bad callback again)
> data of length 189316272 received on stream 123 with SSN 34835, TSN 0, PPID 2965129227 (and again)
> Check for chunk output prw:131072 tqe:0 tf=0
> Calling chunk OUTPUT
> SCTP: Data ready, encrypting 28 bytes
> SCTP: Connected (usrsctp_connect has returned successfully)
> m-c-o put out 1
> Ok, we have put out 1 chunks

Are there any caveats to using usrsctp with C++ code? That's the only thing I can think of right now that I'm doing any differently from other libraries I've seen and used.

And advice much appreciated!

**Comment by tuexen** [comment]
You should be able to use the library in a C++ project. But you need to compile it with the save defines.
So if the library has been compiled with -DINET and -DINET6, you need to do the same. At least for all files which include usrsctp.h. So if you use usrsctp for WebRTC, you can run
```
configure --disable-inet --disable-inet6
make
sudo make install
```
and you don't need to add any of the above defines.
Does this help?

**Comment by chadnickbok** [comment]
Not sure how I missed this one! It didn't occur to me that those defines needed to be consistent. Thank you so much for your quick response :)
