### ISSUE TITLE
Sctp socket connection refused

### ISSUE THREAD

**Issue by l-deptula** [sctplab/usrsctp#520]
Hello,
I'm pretty new to usrsctp and I'm facing problem. Here is my server code:
```
#include <usrsctp.h>
#include <cstring>

#include <boost/log/trivial.hpp>


static int
receive_callback(struct socket *sock, union sctp_sockstore addr, void *data,
                 size_t datalen, struct sctp_rcvinfo rcv, int flags, void *ulp_info)
{
    return 1;
}


int main()
{
    usrsctp_init(0, NULL, 0);
    usrsctp_sysctl_set_sctp_no_csum_on_loopback(0);
    struct socket* main_socket = usrsctp_socket(AF_INET, SOCK_STREAM, IPPROTO_SCTP, nullptr, nullptr, 0, nullptr);
    struct socket* client_socket;
    struct sockaddr_in6 addr;
    memset((void *)&addr, 0, sizeof(struct sockaddr_in6));
    addr.sin6_family = AF_INET;
    addr.sin6_port = htons(20000);
    addr.sin6_addr = in6addr_any;

    ::usrsctp_bind(main_socket, (struct sockaddr *)&addr, sizeof(struct sockaddr_in6));

    ::usrsctp_listen(main_socket, 5);

    while(1)
    {
        struct sockaddr remote_addr;
        socklen_t addr_len;
        if((client_socket = usrsctp_accept(main_socket, &remote_addr, &addr_len)) != nullptr)
        {
            BOOST_LOG_TRIVIAL(info) << "new connection";

        }
        else
        {
            BOOST_LOG_TRIVIAL(error) << errno;
        }
    }

    return 0;
}
```
It's pretty simple server that is expected to just accept incomming connetions and for each new connection print some message.
I'm running that code on machine with internal ip 10.0.0.3.
On the same machine I'm running Python client utilizing kernel sctp socket (through pysctp library):
```
import sctp
import socket
import time

SOCKET_ENDPOINTS = [("10.0.0.3", 20000)]

client_socket = sctp.sctpsocket_tcp(socket.AF_INET)
client_socket.nodelay = True
client_socket.connectx(SOCKET_ENDPOINTS)
buff = f"{time.time()}".encode('utf-8')
client_socket.sctp_send(buff)
fromaddr, flags, msg, notif = client_socket.sctp_recv(1024)
print(msg)
```

The problem I encounter is that when using client app from usrsctp everything works fine, but in case of pysctp I got connection refused:
```
~ python client_usrsctp.py
Traceback (most recent call last):
  File "client_usrsctp.py", line 12, in <module>
    client_socket.connectx(SOCKET_ENDPOINTS)
  File "/home/l.deptula/pysctp_env/lib/python3.6/site-packages/sctp.py", line 1073, in connectx
    _sctp.connectx(self._sk.fileno(), sockaddrs, assoc_id)
ConnectionRefusedError: [Errno 111] Connection refused
```
Also I observed that even tough I'm binding server to port 20000 I can't see any related entry in netstat:
```
~ netstat -pwan | grep app
raw        0      0 0.0.0.0:132             0.0.0.0:*               7           28234/app
raw6       0      0 :::132                  :::*                    7           28234/app
```

**Comment by tuexen** [comment]
You can't run a SCTP/IPv4 or SCTP/IPv6 userland stack on a machine which also has a kernel stack. All SCTP packets will be delivered to the kernel stack only. That is why you are getting ABORTs, they are just sent for the kernel stack. Also netstat can only report the kernel view. So all you see are the raw SCTP sockets.

**Comment by l-deptula** [comment]
Thank you for clarification. Just one more doubt here. In case of containerized deployments does this apply as well? I mean if we deploy two containers on single machine where one container is using userland and second one is using kernel stack will there be the same problem?

**Comment by tuexen** [comment]
To he honest: I don't know. I haven't played with containers yet.

**Comment by l-deptula** [comment]
Okay, anyway thank you for support!
