### ISSUE TITLE
usrsctp_getpaddrs fails with -1 and error message "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by l-deptula** [sctplab/usrsctp#523]
Hello,
I'm trying to obtain paddrs from received socket, unfortunately it doesn't work and I'm not able to detect reason of such behaviour. Also I couldn't find any reference in documentation. Following code snippet:
```
        usrsctp_init(0, nullptr, nullptr); // disable udp tunneling
        usrsctp_sysctl_set_sctp_no_csum_on_loopback(0);
        usrsctp_sysctl_set_sctp_logging_level(3);
        BOOST_LOG_TRIVIAL(info) << "UsrSctp initialized";


        socket *main_lb_socket = usrsctp_socket(AF_INET, SOCK_STREAM, IPPROTO_SCTP, nullptr, nullptr, 0, nullptr);
        if(main_lb_socket == nullptr)
            BOOST_LOG_TRIVIAL(error) << "Failed to create main socket due to " << errno;


        auto addrs {...};
        if(::usrsctp_bindx(this->main_lb_socket, addrs.data(), addrs.size(), SCTP_BINDX_ADD_ADDR) <0)
            BOOST_LOG_TRIVIAL(error) << "Failed to bind main socket due to " << errno;
         else
            BOOST_LOG_TRIVIAL(info) << "Successfully bind";

        if(::usrsctp_listen(this->main_lb_socket, 10) < 0)
        {
            BOOST_LOG_TRIVIAL(error) << "Failed to start listening on socket due to " << errno;
        }
        else
            BOOST_LOG_TRIVIAL(info) << "Started listening for incomming connections";


        while(true)
        {
            int n;
            struct socket *client_socket = ::usrsctp_accept(main_lb_socket, nullptr, nullptr);
            if(client_socket == nullptr)
            {
                BOOST_LOG_TRIVIAL(warning) << "Failed to accept incomming connection";
                continue;
            }
            BOOST_LOG_TRIVIAL(info) << "Accepted new connection";
            struct sockaddr *addr, *addrs;

            if((n = usrsctp_getpaddrs(client_socket, 0, &addrs)) < 0) {
                perror("usrsctp_getpaddrs");
            }
            else
                BOOST_LOG_TRIVIAL(info) << "paddrs successfull";
         }
```
Produces output:
```
[2020-09-04 13:05:23.558657] [0x00007f4d68b6e740] [info]    UsrSctp initialized
[2020-09-04 13:05:23.558777] [0x00007f4d68b6e740] [info]    Started accept loop
[2020-09-04 13:05:23.558906] [0x00007f4d68b6e740] [info]    Successfully bind to 127.0.0.1:20000;
[2020-09-04 13:05:23.558939] [0x00007f4d68b6e740] [info]    Started listening for incomming connections
[2020-09-04 13:05:30.807333] [0x00007f4d68b6e740] [info]    Accepted new connection
usrsctp_getpaddrs: Transport endpoint is not connected
```

**Comment by tuexen** [comment]
You find an example how to use `usrsctp_getpaddrs()` in `programs/ekr_loop.c`. Your code looks similar to it. Could it be that the association is gone by the time you call `usrsctp_getpaddrs()`? Can you run the above program with all debug output enabled and provide it? Maybe you have also enabled an SCTP kernel stack on the host you are running you program. The two stacks would interfere with each other....

**Comment by l-deptula** [comment]
According to manual (https://github.com/sctplab/usrsctp/blob/master/Manual.md) I shall set flag SCTP_DEBUG and execute method https://github.com/sctplab/usrsctp/blob/master/Manual.md#usrsctp_sysctl_set_sctp_debug_on however this name can't be resolved. Could you guide me how to enable usrsctp debug step by step?

**Comment by tuexen** [comment]
You need to do three things:
1. compile the library and program with `SCTP_DEBUG` being defined.
2. provide and printf-like function as the third argument of `sctp_init()`.
3. call `usrsctp_sysctl_set_sctp_debug_on(SCTP_DEBUG_ALL);`

See `programs/ekr_loop.c` as an example.

**Comment by l-deptula** [comment]
Okay, after capturing debug I realized that for it was discovering local IPs even those with down status. After executing ip a f (flushing ip address) paddrs are captured correctly. Again great thanks for help!
