### ISSUE TITLE
Build usrsctp without creating shared libraries

### ISSUE THREAD

**Issue by Ri0n** [sctplab/usrsctp#542]
Hi.
I believe in majority of cases libusrsctp is linked as a static library. So if cmake scripts build both static and shared libs it becomes error-prone since accidentally a wrong lib type might be linked.
Usually cmake projects accept `-DBUILD_SHARED_LIBS=OFF` flag to disable shared libs, so it would be nice for usrsctp to support exactly same flag.

**Comment by tuexen** [comment]
@weinrank Can you add this?

**Comment by weinrank** [comment]
Sure!
