### ISSUE TITLE
cmake/windows: mxe compatibility with iphlpapi

### ISSUE THREAD

**Issue by Ri0n** [sctplab/usrsctp#545]
Currently [our](https://github.com/psi-im/psi) project uses [mxe](https://github.com/mxe/mxe) to build Windows version on Linux.
`iphlpapi` is definitely there but the file name is `libiphlpapi.a`. 

So code like this
```
./usrsctplib/CMakeLists.txt:    target_link_libraries(usrsctp ws2_32 iphlpapi.lib)
```
doesn't look good. Any reason it's `iphlpapi.lib` and not `iphlpapi`, where cmake can do all the magic selecting proper filenames?

**Comment by tuexen** [comment]
@weinrank Can you take care of it?
