### ISSUE TITLE
Stream priority

### ISSUE THREAD

**Issue by rsecchi** [sctplab/usrsctp#56]
How do I assign a priority to a stream? I couldn't find any indication in the manual.

I wanted to use the  SCTP_SS_VALUE socket option but this is not in usrsctp.h, so maybe a better way exists.

Thanks in advance

**Comment by tuexen** [comment]
What are you referring to? Absolute priorities? Relative priorities? We do currently support a
strict priority scheduler, but not with interleaving. A relative one will be available once support for [I-DATA](https://tools.ietf.org/html/draft-ietf-tsvwg-sctp-ndata-04)  has been incorporated. This is currently under development. The API is specified in [Socket API](https://tools.ietf.org/html/draft-ietf-tsvwg-sctp-ndata-04#section-4).

**Comment by rsecchi** [comment]
I guess the following line currently enables the strict priority:
usrsctp_sysctl_set_sctp_default_ss_module(SCTP_SS_PRIORITY);

but then I wanted to assign priorities to streams. I tried with:

 
	

sv.assoc_id = last_assoc_id;
	sv.stream_value = 0;
	sv.stream_id = 0;
	rv = usrsctp_setsockopt(sk, IPPROTO_SCTP, SCTP_SS_VALUE, &sv, sizeof(sctp_stream_value));
	CHECK(rv<0, "SCTP_SS_VALUE");

**Comment by tuexen** [comment]
Can you provide a simple test programs which fails for you?
Please note that you can set the stream scheduler in the current code using the `SCTP_PLUGGABLE_SS` socket option.

**Comment by tuexen** [comment]
Does adding
```
/* RS - Pluggable Stream Scheduling Socket option */
#define SCTP_PLUGGABLE_SS		0x00001203
#define SCTP_SS_VALUE			0x00001204
```
to `usrsctp.h` solve your problem?

**Comment by rsecchi** [comment]
It also says:

server.c:41:71: error: ‘sctp_stream_value’ undeclared (first use in this function)
  rv = usrsctp_setsockopt(sk, IPPROTO_SCTP, SCTP_SS_VALUE, &sv, sizeof(sctp_stream_value));

**Comment by rsecchi** [comment]
Adding the struct as well, it appear to solve.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/d00dc1310054136ec4aa3aa71347e299483e0a4c.
Please test and close the issue...

**Comment by rsecchi** [comment]
Everything works fine. Thank you.
