### ISSUE TITLE
Possible infinite loop

### ISSUE THREAD

**Issue by korniltsev** [sctplab/usrsctp#570]
I've caught an infinite loop here.
https://github.com/sctplab/usrsctp/blob/7dab23aa0d8db86fedd222a308067439b03fad0f/usrsctplib/netinet/sctp_output.c#L5892

It seems like if `plen` is 0 then `offset` is not advanced

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/c08562ec9e5ee621756ccfdfe6230cc6c0af8b9f. Thanks for reporting.

How did you find the bug? By code review or did you use some tools?

**Comment by korniltsev** [comment]
fuzzing

**Comment by tuexen** [comment]
> fuzzing

Great. Let me know if you find more issues.
