### ISSUE TITLE
possible memory leak of struct socket

### ISSUE THREAD

**Issue by korniltsev** [sctplab/usrsctp#571]
I was able to reproduce it by "dropping/ignoring" DATA packets. It leads to an ABORT after sometime, which leads to a socket not beeing freed and EADDRINUSE.
See an attachment: both sockets are closed but only one is freed.
```
closing 0x14b1b50 0x14b2ca0
 >>>>>>>>> free(so : 0x14b2ca0)
 ```

[leak_repro.zip](https://github.com/sctplab/usrsctp/files/5898289/leak_repro.zip)

**Comment by tuexen** [comment]
I can reproduce the issue.

**Comment by tuexen** [comment]
Should be fixed by https://github.com/sctplab/usrsctp/commit/37a9dc3e18bfdcc972946dff0206155cee6b5dd0. Thanks for reporting.
