### ISSUE TITLE
usrsctp.pc points to the wrong includedir

### ISSUE THREAD

**Issue by mid-kid** [sctplab/usrsctp#574]
When installing this library using CMake, the resulting usrsctp.pc includes the line:
```
includedir=/usr/include/usrsctp
```
However, the header file is installed as `/usr/include/usrsctp.h`. This causes some build systems like cmake's `pkg_check_modules` to complain about the nonexisting directory.

**Comment by mid-kid** [comment]
The fix in a packaging script is simple enough:
```
sed -i -e '/^set(includedir /s/\/usrsctp//' usrsctplib/CMakeLists.txt
```

**Comment by tuexen** [comment]
@weinrank What do you think?

**Comment by tuexen** [comment]
@weinrank ping?

**Comment by Ri0n** [comment]
I can confirm the problem.

the fix:
```patch
diff --git a/usrsctplib/CMakeLists.txt b/usrsctplib/CMakeLists.txt
index aa99cf2..84bdee2 100644
--- a/usrsctplib/CMakeLists.txt
+++ b/usrsctplib/CMakeLists.txt
@@ -45,7 +45,7 @@ include(GNUInstallDirs)
 set(prefix ${CMAKE_INSTALL_PREFIX})
 set(exec_prefix ${prefix})
 set(libdir ${exec_prefix}/${CMAKE_INSTALL_LIBDIR})
-set(includedir ${prefix}/${CMAKE_INSTALL_INCLUDEDIR}/usrsctp)
+set(includedir ${prefix}/${CMAKE_INSTALL_INCLUDEDIR})
 
 set(CMAKE_REQUIRED_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR})
 set(CMAKE_MACOSX_RPATH 1)
```

**Comment by tuexen** [comment]
@weinrank ping!

**Comment by weinrank** [comment]
The fix looks good. 👍

**Comment by Ri0n** [comment]
@tuexen, I'm wondering if you can set a git tag after this fixed. So it won't necessary to have a patch in all the distros building with cmake.

**Comment by tuexen** [comment]
What is a git tag? Are you referring to make a release?

**Comment by Ri0n** [comment]
yes. a release.

**Comment by tuexen** [comment]
I don't think I want to do this for a change in one of the build systems considering the feedback last time. I suggest you just use a particular date or commit, if you want to have a particular fix.

**Comment by Ri0n** [comment]
ok. thanks.
I'll add a package to Gentoo Linux with a patch then.
