### ISSUE TITLE
How to run ekr_client on android ？

### ISSUE THREAD

**Issue by Supreness** [sctplab/usrsctp#576]
Question I  use usersctplib on android , I run ekr_client on android ,ekr_client run with a error in sctp_connect function.  to addr family can't be recognized. This error caused the link to not be established

unexcept case : which should be AF_CONF case but it is default case
  
in sctp_output.c  at line 5050
![image](https://user-images.githubusercontent.com/50078659/112274728-c9f44780-8cb9-11eb-91fd-9b38336ce6af.png)

**Comment by wudanfeng2021** [comment]
add this in cmake 
include_directories(usrsctplib)
add_definitions(-DINET)
add_definitions(-D__Userspace__)
add_definitions(-DSCTP_SIMPLE_ALLOCATOR)
add_definitions(-DSCTP_PROCESS_LEVEL_LOCKS)
add_definitions(-DINET)
add_definitions(-DHAVE_SYS_QUEUE_H)
add_definitions(-DCLIENT)
add_definitions(-DINET6)

**Comment by Supreness** [comment]
Nice，thankq!

> add this in cmake
> include_directories(usrsctplib)
> add_definitions(-DINET)
> add_definitions(-D__Userspace__)
> add_definitions(-DSCTP_SIMPLE_ALLOCATOR)
> add_definitions(-DSCTP_PROCESS_LEVEL_LOCKS)
> add_definitions(-DINET)
> add_definitions(-DHAVE_SYS_QUEUE_H)
> add_definitions(-DCLIENT)
> add_definitions(-DINET6)

**Comment by BruceeTao** [comment]
> Nice，thankq!
> 
> > add this in cmake
> > include_directories(usrsctplib)
> > add_definitions(-DINET)
> > add_definitions(-D__Userspace__)
> > add_definitions(-DSCTP_SIMPLE_ALLOCATOR)
> > add_definitions(-DSCTP_PROCESS_LEVEL_LOCKS)
> > add_definitions(-DINET)
> > add_definitions(-DHAVE_SYS_QUEUE_H)
> > add_definitions(-DCLIENT)
> > add_definitions(-DINET6)

how do u compile .so and head file for android
