### ISSUE TITLE
Homebrew: please create tags

### ISSUE THREAD

**Issue by ilovezfs** [sctplab/usrsctp#59]
In order to adopt the new GitHub repository as its upstream, the Homebrew formula will need a release tag that can be assigned to the stable spec. This allows a tarball of the tag to be downloaded from GitHub and the sha256 of the tarball to be recorded in the formula to ensure integrity.

**Comment by tuexen** [comment]
OK. Will do in 2 weeks or so when some cleanups have been merged.

**Comment by tuexen** [comment]
Done.

**Comment by ilovezfs** [comment]
Thank you: https://github.com/Homebrew/homebrew-core/pull/158
