### ISSUE TITLE
ECN support with old chunk format

### ISSUE THREAD

**Issue by kanakagrawal** [sctplab/usrsctp#594]
Hi,

We are using usrsctp to run sctp server. When connecting with linux kernel sctp client, sometimes, when there is congestion in the network, client sends ECNE packets but there is no reply to that by usrsctp. On looking at the source code, there is a check of chunk length [here](https://github.com/sctplab/usrsctp/blob/61365d57d39cfd141d12816baece5be38b93f0eb/usrsctplib/netinet/sctp_input.c#L5492). This is causing the ECNE packets to be dropped at usrsctp and no reply is sent. 

I know that we can just disable ECN support but we would like to have this feature and compatible with linux kernel sctp. Any ideas on how to fix it?

**Comment by tuexen** [comment]
Yepp, that check is too restrictive. Will fix that later today.

**Comment by tuexen** [comment]
Please report if the avove commit fixes the issue you. Thanks for reporting the issue.
