### ISSUE TITLE
protocol id not taken into account in usrsctp_sendv via the info* parameter

### ISSUE THREAD

**Issue by ptharan** [sctplab/usrsctp#635]
sinfo.sinfo_ppid is not taken into account, though its passed . The packets on the wire seem to have some unitialized values.
A snippet from wireshark.
Payload protocol identifier: Unknown (50331648)

The usage is a one to many socket sending data out.

**Comment by tuexen** [comment]
I agree with @lgrahl : The number you are reporting is the PPID for M3UA, which is 3, set on a litle endian system without converting it to network byte order. But it is strange that you refer to `sinfo.sinfo_ppid`, which seems to indicate that you are using `struct sctp_sndrcvinfo`, which is not supported by `usrsctp_sendv`. `usrsctp_sendv` uses the non-deprecated structure `struct sctp_sndinfo`. Could you share a code snippet you are using?

**Comment by tuexen** [comment]
You need to write
```
lsndinfo.snd_ppid = htonl(3);
```
instead of
```
lsndinfo.snd_ppid = 3;
```
See the description of `snd_ppid` in [RFC 6458](https://datatracker.ietf.org/doc/html/rfc6458#section-5.3.4).

**Comment by ptharan** [comment]
ok, thank you for the reference, and am sorry for the confusion.
