### ISSUE TITLE
Visual C++ multithreaded: srandom() generates the same values on different threads.

### ISSUE THREAD

**Issue by PROGrand** [sctplab/usrsctp#66]
Visual C++ runtime uses per-thread internal state, so it is safe to call srand() for each thread.
Having application with usrsctp_init called on main thread and usrsctp_connect called on different thread.
On subsequent application runs sctp.inital_vtag is always the same(41 for example), because srand() called only on main thread. It is deep hidden from application developers and produces many strange behaviors on subsequent and parallel application calls.

**Comment by tuexen** [comment]
Can you checkout the Issue66 branch and see if it fixes your issue?

**Comment by tuexen** [comment]
Closing due to no response. If the problem still exists, reopen.
