### ISSUE TITLE
Visual C++ multithreaded: srand(time(NULL)). Same seeding for one second.

### ISSUE THREAD

**Issue by PROGrand** [sctplab/usrsctp#67]
I have visual c++ application (at least VS2013+debug win64 libs) with usrsctp_init and usrsctp_connect performed immediately after launch. I start 10 apps at the same time. Each SCTP_INIT have the same initial vtag and 9 apps unable to connect.

This is because time(NULL) is the same for all 10 apps and is not appropriate choice for srand() seed.

usrsctplib need more complicated seed for srand.

**Comment by tuexen** [comment]
Can you checkout the Issue66 branch and see if it fixes your issue?

**Comment by tuexen** [comment]
Should be fixed by having merged branch issue66.
