### ISSUE TITLE
Examples don't work under Windows

### ISSUE THREAD

**Issue by CoolmanCZ** [sctplab/usrsctp#69]
Hi,

I tried to build and execute usrsctp library examples under Windows but they don't work. The examples was built by MSVC with Windows 10.
I found that problem was caused by commits "Use SOCKET for sockets on Windows" and "More SOCKET stuff". When these commits are disabled everything works OK.

Best regards, Radek

**Comment by tuexen** [comment]
Can you be more specific what you mean by "they don't work"? Can you give an example, how you call which program and what happens?

**Comment by CoolmanCZ** [comment]
Hi,

Examples are build by MSVC 2015 under Windows 10. In the build directory ../programs/Debug I run cmd.exe and execute the echo_server.exe with parameter 9899. In another cmd I execute client.exe with parameters <IP address> 7 5001 5002 9899.
Without changes communications failed and I can't see INIT from the client.
When I disable SOCKET for Windows mentioned above,communication works fine.

Radek

**Comment by tuexen** [comment]
Are you not providing an IP address as the first parameter of the client?

**Comment by CoolmanCZ** [comment]
Hi,

No I provide the IP address (10.0.0.56). It is the mistake during writing the post. I'm sorry.

Radek

**Comment by tuexen** [comment]
OK. Thanks. I'll try to reproduce this and understand why the changes broke the examples on Windows.

**Comment by tuexen** [comment]
OK. With the help of Felix we were able to reproduce and understand the problem. Can you verify that the branch `issue69` fixes the issue?

**Comment by CoolmanCZ** [comment]
Hi,

Examples now work as expected.

 Thanks, Radek
