### ISSUE TITLE
Use of standard socket functions

### ISSUE THREAD

**Issue by gedOHub** [sctplab/usrsctp#74]
Hello,

Is there possible with usrsctp to use standard socket functions as socket(), bind(), listen()?

**Comment by tuexen** [comment]
No. You need to use the corresponding functions with a `usrsctp` prefix.

**Comment by gedOHub** [comment]
Is it possible to use in select statement?

**Comment by tuexen** [comment]
No.

**Comment by tuexen** [comment]
Which OS are you using?

**Comment by gedOHub** [comment]
Now testing on windows 10

**Comment by tuexen** [comment]
OK. Then you can't use a kernel stack since MS doesn't provide one... So: no, you need to use a different API for SCTP socket then for UDP and TCP sockets.
