### ISSUE TITLE
Http_client not building on windows and fix

### ISSUE THREAD

**Issue by gedOHub** [sctplab/usrsctp#78]
Hello,
I don't know how to submit a fix, so I posted here. At current source http_client can't build. Error: 

> warning C4013: 'snprintf' undefined; assuming extern returning int

Fix:
Need to change
`if (argc > 6) {
		snprintf(request, sizeof(request), "%s %s %s", request_prefix, argv[6], request_postfix);
	} else {
		snprintf(request, sizeof(request), "%s %s %s", request_prefix, "/", request_postfix);
	}`
to
`if (argc > 6) {
		_snprintf(request, sizeof(request), "%s %s %s", request_prefix, argv[6], request_postfix);
	} else {
		_snprintf(request, sizeof(request), "%s %s %s", request_prefix, "/", request_postfix);
	}`

And insert 
`#ifdef _WIN32
#define _CRT_SECURE_NO_WARNINGS
#endif`

Becouse of:

> warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE
_NO_WARNINGS. See online help for details.

**Comment by weinrank** [comment]
Our buildsystem is fine with that code - which compiler/build system are you using?

**Comment by tuexen** [comment]
I committed a fix in https://github.com/sctplab/usrsctp/commit/60d8251b19d2cc08757cd04483f9f7fc8fff4830 since we use the same pattern in the other programs, too. So this is now consistent. I got warnings when using nmake with an older C compiler (Visual Studio based).

**Comment by gedOHub** [comment]
Got thease errors on cmake with Visual Studio 2013. After fixes builds and runs lika a charm :)
