### ISSUE TITLE
struct socket to int

### ISSUE THREAD

**Issue by gedOHub** [sctplab/usrsctp#80]
Hello,
Is it possible to get socket number from struct socket? Can't find struct socket declaration

**Comment by tuexen** [comment]
No, you can't. The reason is that there is none. For the userland stack the replacement is a pointer to the socket, which is opaque for users.
Why do you think you need the number?

**Comment by gedOHub** [comment]
Problem is that I have program implemented with select functionality. I need number for casting to SOCKET or adding directly to fd_set for selecting socket when data is receaved

**Comment by tuexen** [comment]
You can't SCTP sockets in combination with `select()`. The reason is that `select()` takes kernel sockets into considerations to which you refer to by an fd. The userland stack just deals with its own sockets, and therefore they don't exist in the kernel and can't be used in combination with `select()`.

**Comment by gedOHub** [comment]
Is there any plans to code kernel version?

**Comment by weinrank** [comment]
For Windows? No!

Linux and FreeBSD have SCTP kernel support out-of-the-box.

**Comment by gedOHub** [comment]
Why not? Problems from M$ side? Tell me more
2016 geg. 5 02:41 "Felix Weinrank" <notifications@github.com> rašė:

**Comment by tuexen** [comment]
SCTP is supported natively at least in the following operating systems:
* FreeBSD
*  Linux
* Solaris
* HP/UX
* AIX

The FreeBSD sources are also used for the
* userland stack usrsctp
* Network kernel extension supporting Mac OS X: [El Capitan](https://github.com/sctplab/SCTP_NKE_ElCapitan), [Yosemite](https://github.com/sctplab/SCTP_NKE_Yosemite)
* Windows kernel extension: [SctpDrv](http://www.bluestop.org/SctpDrv/)

However, the Windows kernel extensions is not maintained anymore. It just needs someone with Windows expertise to do the work.

SCTP is commercially used in telephony signalling networks, especially mobile networks, and therefore the above selection of operating systems makes sense. As far as I know, Microsoft is not active in that area. Recently, SCTP is also used as a transport protocol in WebRTC. For integrating it into Web browsers and running on top of DTLS, you need a userland implementation. Therefore, incentives for Microsoft to integrate SCTP into their operating system might be litte.

NAT traversal is another issue, but can be dealt with UDP encapsulation of SCTP. This is currently supported by usrsctp, the FreeBSD stack and the NKEs for Mac OS X.

**Comment by gedOHub** [comment]
thank you for answer :)
