### ISSUE TITLE
Examples under windows (again)

### ISSUE THREAD

**Issue by pravic** [sctplab/usrsctp#84]
Hi.

Trying to use sctp, but unsuccessful:

`start discard_server.exe 11111 22222`
`client 127.0.0.1 9 0 22222 11111` - just sleep at `usrsctp_connect`.

Well, try http_client example from #76:
`http_client 212.201.121.100 80 0 9899 9899` - works fine.
`http_client 212.201.121.100 80` - some infinite loop:

> ...
> chunk OUTPUT returns **<-- sleep 3 seconds**
recv_function_raw: Received 76 bytes. - calling sctp_common_input_processing with off=32
stcb:00000000 inp:00000000
stcb is 00000000
Timer type 5 goes off
Error count for 007D9590 now 1 thresh:5
Overall error count for 007D8B58 now 0 thresh:10 state:201
Timer now complete (type = 5)
Timer type 5 goes off
Error count for 007D9590 now 2 thresh:5
Overall error count for 007D8B58 now 0 thresh:10 state:201
Timer now complete (type = 5)
recv_function_raw: Received 76 bytes. - calling sctp_common_input_processing with off=32
stcb:00000000 inp:00000000
stcb is 00000000
Timer type 5 goes off
Error count for 007D9590 now 3 thresh:5
Overall error count for 007D8B58 now 0 thresh:10 state:201
Timer now complete (type = 5)
**... and so on**

Here is a logs: [http_client-sctp-raw.log](http://www.everfall.com/paste/id.php?236vmdg35s4l), [http_client-sctp-caps.log](http://www.everfall.com/paste/id.php?upk7teuyw0zl).

Windows 7 x64, http_client debug x86.

**Comment by tuexen** [comment]
Regarding your first question: I'm not sure if 127.0.0.1 works on Windows.
Regarding your second question: Are you running this with root privileges? Are you behind a NAT? That might a problem with native SCTP. You might want to use Wireshark to capture the traffic. That might provide some more information.
@weinrank Can you test the above on a Windows system?

**Comment by weinrank** [comment]
@pravic 
I assume from the logfile that you already run the examples with administrative privileges - good.
The native SCTP mode needs administrative privileges while udp-encaps doesn't.

**discard server and client**
Don't use 127.0.0.1 - it doesn't work with Windows. Try using the IP of your local NIC and it should work.

**http_client**
The SCTP connection seems to be established: timer type 5 is the heartbeat timer.
As Michael Tüxen mentioned obove a wireshark tracefile would be helpful.

What happens if you disable IPv6 support in USRSCTP?
Are you using CMAKE?

**Comment by pravic** [comment]
Yea, cmake. I'll try without ipv6

**Comment by pravic** [comment]
@tuexen

> Regarding your first question: I'm not sure if 127.0.0.1 works on Windows.
I took it from [manual](https://github.com/sctplab/usrsctp/blob/master/Manual.md). Whats difference between Linux and Windows with 127.0.0.1?

> Are you running this with root privileges? Are you behind a NAT?
Yes. Yes.

@weinrank

> Try using the IP of your local NIC and it should work.
It works. The local servers (like echo) works both with and without encapsulation.

> What happens if you disable IPv6 support in USRSCTP?
Nothing good: "usrsctp_socket: Unknown error", because all examples uses AF_INET6.

**Comment by tuexen** [comment]
The manual states that you can use 127.0.0.1 on Unix like OSes and not on Windows. Regarding the difference of 127.0.0.1 between Windows and Linux: On Unix like OSes there is an loopback interface
and an address. On Windows this seems to be different. I don't know why. (I don't know much about Windows).
Running native SCTP through NATs most likely is an issue. That is why we use UDP encapsulation there.

**Comment by pravic** [comment]
SCTP does not use/support NAT traversal?

Well, thanks for explanation.

**Comment by tuexen** [comment]
NATs must support SCTP, one way of doing this is specified in https://tools.ietf.org/html/draft-ietf-tsvwg-natsupp-09. It is supported, as far as I know, in FreeBSD.
For legacy NAT traversal use UDP encapsulation.
