### ISSUE TITLE
Receiving a complete unordered message while reassembling another message causes the association to be aborted

### ISSUE THREAD

**Issue by taylor-b** [sctplab/usrsctp#96]
I can reproduce this by simulating network reordering and alternating between sending messages that get fragmented (size greater than MTU) and smaller messages that aren't fragmented.

The problem seems to be this block of code:

```
		/* Its a complete segment. Lets validate we
		 * don't have a re-assembly going on with
		 * the same Stream/Seq (for ordered) or in
		 * the same Stream for unordered.
		 */
		SCTPDBG(SCTP_DEBUG_XXX, "chunk_flags:0x%x look for msg in case we have dup\n",
			chunk_flags);`
		if (find_reasm_entry(strm, msg_id, ordered, old_data)) {
			SCTPDBG(SCTP_DEBUG_XXX, "chunk_flags: 0x%x dup detected on msg_id: %u\n",
				chunk_flags,
				msg_id);

			goto err_out;
		}
```

I don't understand why this is necessary. If fragmented segments can be received while reassembling another fragmented message, why can't a complete segment be received? That seems the simpler case to handle. If I remove this condition, things work as expected.

**Comment by tuexen** [comment]
This is a check for mainly I-DATA chunks. If you are receiving a complete message with a MID, you can't have one in the reassembly queue with the same MID. It might go wrong with DATA chunks...
Are you using ordered or unordered messages?

**Comment by tuexen** [comment]
I added some testscripts (see https://github.com/sctplab/sctp-idata/commit/dd6d486a6aff034c0dee48fd67c8eddc83838b6b) testing the reassembly of
* a complete unordered messages followed by a fragmented unordered message
* a fragmented unordered message followed by a complete unordered message

using DATA chunks and all possible permutations of arriving packets. Some tests fail. I'm investigating.

**Comment by taylor-b** [comment]
I'm testing unordered messages (with DATA chunks). Which means find_reasm_entry will return something if there's anything in the unordered reassembly queue.

**Comment by tuexen** [comment]
The following commit https://github.com/sctplab/usrsctp/commit/4ce5badc821451f5dd5aa43fb75cbb93bacdf187 fixes the issues I saw with the test scripts I wrote.  Please retest with the above commit and let me know if you find any issues.

**Comment by taylor-b** [comment]
My tests are passing after this commit. Thanks for the quick fix!

**Comment by tuexen** [comment]
Thanks for testing and the report. Let me know if you find any further issues.
