### ISSUE TITLE
Unordered reassembly can add chunks to the wrong message.

### ISSUE THREAD

**Issue by taylor-b** [sctplab/usrsctp#97]
Suppose I send two messages, each getting split into two fragments, and they arrive in this order:

1. Message B fragment 1
2. Message A fragment 1
3. Message A fragment 2
4. Message B fragment 2

The result is that the first complete message assembled is: [A1]
And the second is: [B1][A2][B2]

The reason is that when receiving the "first" chunks out of order, this "swap the mbufs" code doesn't modify tail_mbuf:

```
/* swap the mbufs */
tdata = control->data;                                                                       
control->data = chk->data;                                                                   
chk->data = tdata;
```

As a result, when adding A2 to tail_mbuf, it's actually being appended onto B1 instead of A1.

I think this can be fixed by just adding sctp_setup_tail_pointer; that's working for me so far. If you agree, I can make a pull request.

**Comment by tuexen** [comment]
Isn't this part of
https://github.com/sctplab/usrsctp/commit/fdcf790d13be13aa1ada67461449d0051fbacd41

**Comment by tuexen** [comment]
I added a packetdrill test script for the above message flow [sctp-idata-118.pkt](https://github.com/sctplab/sctp-idata/blob/master/tests/sctp-idata-118.pkt) which runs fine on FreeBSD head in the kernel. So could it be that you are missing the above fix?

**Comment by taylor-b** [comment]
Oh, you're right, this is already fixed. I've been debugging on a slightly older version.
