### ISSUE TITLE
How to get the remote UDP encapsulation port when receiving a message?

### ISSUE THREAD

**Issue by highfly22** [sctplab/usrsctp#98]
It is necessary to know the remote UDP encapsulation port in a P2P application.

**Comment by tuexen** [comment]
Which address family are you using in the `usrsctp_socket()` call? `AF_INET`,`A_INET6`, or `AF_CONN`?

**Comment by highfly22** [comment]
I passed AF_INET6  to usrsctp_socket() like in the example discard_server.

**Comment by tuexen** [comment]
Have a look at https://tools.ietf.org/html/rfc6951#section-6.1 and use usrsctp_[gs]etsockopt().

**Comment by highfly22** [comment]
I have try this method. The SCTP_REMOTE_UDP_ENCAPS_PORT always gives 0 in the sue_port field. Did I miss anything?

						{
							struct sctp_udpencaps encaps;
							socklen_t len = sizeof(encaps);
							memset(&encaps, 0, sizeof(struct sctp_udpencaps));
							encaps.sue_assoc_id = rcv_info.rcv_assoc_id;
							if (usrsctp_getsockopt(sock, IPPROTO_SCTP, SCTP_REMOTE_UDP_ENCAPS_PORT, (void*)&encaps, &len) < 0) {
								perror("usrsctp_setsockopt SCTP_REMOTE_UDP_ENCAPS_PORT");
							}

							printf("ENCAPS %d\n", ntohs(encaps.sue_port));
						}

**Comment by tuexen** [comment]
The remote encapsulation port is per remote address. So you need to provide the remote address in the encaps structure when calling `usrsctp_getsockopt()`.
